using DeutschQuiz.Domain;

namespace DeutschQuiz.Application;

/// <summary>
/// Independent quiz catalogue for Menschen A2.2 (Lektionen 13–24).
/// Prompts are original for DeutschQuiz and are not copied from the textbook.
/// </summary>
public static class MenschenA22QuizContentCatalog
{
    public static IReadOnlyList<QuizContentLesson> Lessons { get; } =
    [
        CreateLesson(13, "Feste und Traditionen",
            V("Was ist ein Fest?", ["Eine Feier mit Menschen", "Ein Werkzeug", "Ein Fahrplan"], "Eine Feier mit Menschen", "Ein Fest ist eine Feier."),
            V("Zu Weihnachten schmückt man oft einen ...", ["Baum", "Briefkasten", "Fahrstuhl"], "Baum", "Der Weihnachtsbaum ist Tradition."),
            V("Was macht man an einem Geburtstag oft?", ["Geschenke geben", "Steuern zahlen", "Züge reparieren"], "Geschenke geben", "Geburtstage gehören zu Festen."),
            V("Eine Tradition ist etwas, das man ...", ["regelmäßig weitergibt", "nur einmal erfindet", "sofort vergisst"], "regelmäßig weitergibt", "Traditionen werden weitergegeben."),
            V("Silvester feiert man am ...", ["31. Dezember", "1. Mai", "24. Juni"], "31. Dezember", "Silvester ist der Jahreswechsel."),
            V("Was isst man oft auf einem Fest?", ["Kuchen oder Buffet", "Benzin", "Schrauben"], "Kuchen oder Buffet", "Feste haben oft Essen."),
            V("Ein Brauch ist eine ...", ["gewohnte Handlung", "technische App", "mathematische Formel"], "gewohnte Handlung", "Brauch ≈ Tradition."),
            V("Zur Hochzeit gehören oft ...", ["Braut und Bräutigam", "Lehrer und Tafel", "Pilot und Cockpit"], "Braut und Bräutigam", "Hochzeit = Heiratsfeier."),
            V("Was bedeutet feiern?", ["Ein Fest machen", "Leise lernen", "Schnell laufen"], "Ein Fest machen", "Feiern = Party/Fest."),
            V("Karneval kennt man besonders im ...", ["Rheinland", "Weltraum", "Kühlschrank"], "Rheinland", "Karneval ist dort stark."),
            G("___ ich Kind war, habe ich Ostern geliebt.", ["Als", "Wenn", "Ob"], "Als", "Als + Vergangenheit = einmalig."),
            G("Immer ___ es schneit, freuen sich die Kinder.", ["wenn", "als", "damit"], "wenn", "Wenn = wiederholt/bedingt."),
            G("Wir backen Kuchen, ___ Gäste kommen.", ["wenn", "als", "wohin"], "wenn", "Bedingung mit wenn."),
            G("___ dem Fest putzen wir die Wohnung.", ["Vor", "Ohne", "Gegen"], "Vor", "Vor + Dativ: Zeit."),
            G("Die Gäste kommen ___ Abend.", ["am", "im", "zum"], "am", "Am Abend."),
            G("Ich schenke dir etwas, ___ du Geburtstag hast.", ["weil", "obwohl", "ohne dass"], "weil", "Grund mit weil."),
            G("Traditionell ___ man Kerzen an.", ["zündet", "zünden", "zündest"], "zündet", "Man zündet ... an."),
            G("Wir treffen uns, ___ zu feiern.", ["um", "für", "bei"], "um", "Um ... zu + Infinitiv."),
            G("___ Neujahr wünschen wir uns Glück.", ["Zu", "Mit", "Aus"], "Zu", "Zu + Festtag."),
            G("Die Kinder ___ schon auf den Kuchen.", ["freuen sich", "freuen", "freut"], "freuen sich", "Sich freuen auf.")),

        CreateLesson(14, "Kultur und Film",
            V("Was ist ein Film?", ["Eine Geschichte in Bildern", "Ein Möbelstück", "Ein Getränk"], "Eine Geschichte in Bildern", "Film = bewegte Bilder."),
            V("Im Kino kauft man oft ein ...", ["Ticket", "Sofa", "Rezept"], "Ticket", "Eintrittskarte für den Film."),
            V("Ein Regisseur ...", ["führt den Film", "kocht nur Suppe", "repariert Ampeln"], "führt den Film", "Regie = Leitung des Films."),
            V("Kultur umfasst z. B. ...", ["Kunst, Musik und Theater", "Nur Benzin", "Nur Wetter"], "Kunst, Musik und Theater", "Kultur ist breit."),
            V("Ein Schauspieler spielt eine ...", ["Rolle", "Rechnung", "Ampel"], "Rolle", "Rolle = Figur im Film."),
            V("Ein Dokumentarfilm zeigt meist ...", ["echte Ereignisse", "nur erfundene Magie", "nur Rezepte"], "echte Ereignisse", "Dokumentation = Realität."),
            V("Was bedeutet: der Film läuft?", ["Er wird gezeigt", "Er rennt", "Er kocht"], "Er wird gezeigt", "Laufen = im Programm sein."),
            V("Untertitel helfen beim ...", ["Verstehen der Sprache", "Kochen", "Parken"], "Verstehen der Sprache", "Text unter dem Bild."),
            V("Ein Museum zeigt oft ...", ["Kunst oder Geschichte", "Nur Fahrpläne", "Nur Schuhe"], "Kunst oder Geschichte", "Museum = Ausstellung."),
            V("Kritik am Film heißt oft ...", ["Rezension", "Frühstück", "Fahrstuhl"], "Rezension", "Rezension = Bewertung."),
            G("Der Film, ___ ich gesehen habe, war spannend.", ["den", "der", "dem"], "den", "Akkusativ Relativpronomen."),
            G("Die Schauspielerin, ___ den Preis bekommen hat, ist berühmt.", ["die", "der", "das"], "die", "Nominativ feminin."),
            G("Das Museum, ___ wir besuchen, ist modern.", ["das", "die", "den"], "das", "Neutrum Relativpronomen."),
            G("Ich finde den Film ___.", ["beeindruckend", "beeindruckt", "beeindrucken"], "beeindruckend", "Adjektiv nach finden."),
            G("Der Regisseur, ___ dem ich gesprochen habe, war nett.", ["mit", "für", "ohne"], "mit", "Sprechen mit + Dativ."),
            G("___ interessierst du dich für Kultur?", ["Wofür", "Wohin", "Woher"], "Wofür", "Sich interessieren für."),
            G("Der Saal, ___ wir sitzen, ist dunkel.", ["in dem", "in den", "in der"], "in dem", "Relativ + Präposition."),
            G("Die Kritik, ___ sie geschrieben hat, ist fair.", ["die", "der", "dem"], "die", "Akkusativ feminin."),
            G("Kultur ___ man nicht nur im Kino.", ["erlebt", "erleben", "erlebst"], "erlebt", "Man erlebt ..."),
            G("Der Film, über ___ wir sprechen, ist neu.", ["den", "dem", "der"], "den", "Über + Akkusativ.")),

        CreateLesson(15, "Sport und Wettkampf",
            V("Was ist ein Wettkampf?", ["Ein Wettbewerb", "Ein Frühstück", "Ein Möbelstück"], "Ein Wettbewerb", "Wettkampf = Konkurrenz."),
            V("Wer gewinnt, ist der ...", ["Sieger", "Zuschauer nur", "Schiedsrichter immer"], "Sieger", "Sieger = Gewinner."),
            V("Ein Trainer hilft dem ...", ["Team oder Sportler", "Kühlschrank", "Fahrplan"], "Team oder Sportler", "Training braucht Anleitung."),
            V("Fairplay bedeutet ...", ["ehrlich spielen", "mogeln", "schlafen"], "ehrlich spielen", "Fair = regelgerecht."),
            V("Was braucht man oft zum Laufen?", ["Sportschuhe", "Einen Pass als Essen", "Einen Dom"], "Sportschuhe", "Schuhe für Sport."),
            V("Ein Rekord ist die ...", ["beste Leistung bisher", "langsamste Pause", "längste Pause nur"], "beste Leistung bisher", "Rekord = Bestmarke."),
            V("Die Mannschaft spielt gegen den ...", ["Gegner", "Kühlschrank", "Briefkasten"], "Gegner", "Gegner = andere Seite."),
            V("Wer schaut zu, ist ...", ["Zuschauer", "Ball", "Tor"], "Zuschauer", "Zuschauer beobachten."),
            V("Ausdauer braucht man bei ...", ["langen Strecken", "nur einem Witz", "nur Tee"], "langen Strecken", "Ausdauer = lange Leistung."),
            V("Ein Unentschieden heißt: ...", ["kein Sieger", "nur ein Sieger", "Spiel abgesagt"], "kein Sieger", "Gleichstand."),
            G("Unser Team ist ___ als gestern.", ["stärker", "stark", "am starken"], "stärker", "Komparativ: stärker."),
            G("Sie läuft am ___.", ["schnellsten", "schneller", "schnell"], "schnellsten", "Superlativ: am schnellsten."),
            G("Der Ball ___ ins Tor geschossen.", ["wurde", "wurde sein", "ist werden"], "wurde", "Passiv: wurde + Partizip."),
            G("Die Regeln ___ genau erklärt.", ["werden", "wird", "bist"], "werden", "Passiv Plural."),
            G("Je mehr du trainierst, ___ besser wirst du.", ["desto", "als", "ob"], "desto", "Je ... desto ..."),
            G("Er trainiert, ___ fit zu bleiben.", ["um", "für", "bei"], "um", "Um ... zu."),
            G("Das Spiel ___ um 18 Uhr begonnen.", ["wird", "werden", "wirst"], "wird", "Passiv Futur/Präsens."),
            G("Wir haben ___ als die anderen Punkte.", ["mehr", "viel", "am vielen"], "mehr", "Komparativ von viel."),
            G("Der Trainer, ___ dem wir sprechen, ist streng.", ["mit", "für", "ohne"], "mit", "Sprechen mit."),
            G("Ohne Training ___ man selten besser.", ["wird", "werden", "wirst"], "wird", "Man wird ...")),

        CreateLesson(16, "Technik und Internet",
            V("Was ist das Internet?", ["Ein weltweites Netz", "Ein Möbelstück", "Ein Getränk"], "Ein weltweites Netz", "Internet verbindet Computer."),
            V("Ein Passwort schützt dein ...", ["Konto", "Frühstück", "Fahrrad immer"], "Konto", "Passwort = Zugangsschutz."),
            V("Eine App ist ein ...", ["kleines Programm", "großes Haus", "langes Buch nur"], "kleines Programm", "App = Anwendung."),
            V("Was bedeutet online?", ["Im Netz verbunden", "Nur offline schlafen", "Nur zu Fuß"], "Im Netz verbunden", "Online = verbunden."),
            V("Ein Virus kann den Computer ...", ["beschädigen", "kochen", "heilen immer"], "beschädigen", "Schadsoftware."),
            V("WLAN braucht man für ...", ["drahtloses Internet", "nur Kochen", "nur Schwimmen"], "drahtloses Internet", "WLAN = Funknetz."),
            V("Eine Datei speichert man oft auf der ...", ["Festplatte oder Cloud", "Ampel", "Suppe"], "Festplatte oder Cloud", "Speicherorte."),
            V("Updates machen Software ...", ["aktueller", "älter absichtlich", "leiser nur"], "aktueller", "Update = Aktualisierung."),
            V("Social Media nutzt man zum ...", ["Teilen und Chatten", "Nur Parken", "Nur Backen"], "Teilen und Chatten", "Soziale Netzwerke."),
            V("Ein Link führt zu einer ...", ["Website", "Küche", "Brücke immer"], "Website", "Link = Verknüpfung."),
            G("Ich interessiere mich ___ Technik.", ["für", "an", "über"], "für", "Sich interessieren für."),
            G("Er wartet ___ eine Antwort.", ["auf", "für", "mit"], "auf", "Warten auf + Akkusativ."),
            G("Die Seite ___ gerade geladen.", ["wird", "werden", "bist"], "wird", "Passiv: wird geladen."),
            G("Vergiss nicht, das Passwort ___.", ["zu ändern", "ändern", "ändert"], "zu ändern", "Infinitiv mit zu."),
            G("Es ist wichtig, vorsichtig ___.", ["zu sein", "sein", "bist"], "zu sein", "Wichtig + zu + Infinitiv."),
            G("Worüber ___ du dich aufgeregt?", ["hast", "bist", "seid"], "hast", "Sich aufregen + haben."),
            G("Die Daten ___ verschlüsselt.", ["werden", "wird", "bist"], "werden", "Passiv Plural."),
            G("Ich freue mich ___, dass es funktioniert.", ["darüber", "darauf", "davon"], "darüber", "Sich freuen über."),
            G("Ohne Internet ___ man hier nicht arbeiten.", ["kann", "können", "kannst"], "kann", "Man kann ..."),
            G("Denk ___, den Laptop auszuschalten.", ["daran", "darüber", "davon"], "daran", "Denken an.")),

        CreateLesson(17, "Geld und Konsum",
            V("Was ist Konsum?", ["Kaufen und Verbrauchen", "Nur Schlafen", "Nur Laufen"], "Kaufen und Verbrauchen", "Konsum = Verbrauch."),
            V("Ein Konto führt man bei der ...", ["Bank", "Bäckerei nur", "Ampel"], "Bank", "Bankkonto."),
            V("Sparen heißt Geld ...", ["zurücklegen", "sofort ausgeben", "wegwerfen"], "zurücklegen", "Sparen = nicht alles ausgeben."),
            V("Ein Preis sagt, wie teuer etwas ...", ["ist", "kocht", "schläft"], "ist", "Preis = Kosten."),
            V("Rabatt bedeutet ...", ["Preisnachlass", "Preiserhöhung", "Geschenkpflicht"], "Preisnachlass", "Rabatt = günstiger."),
            V("Schulden muss man oft ...", ["zurückzahlen", "anmalen", "kochen"], "zurückzahlen", "Schulden = geliehenes Geld."),
            V("Bar zahlen heißt: mit ...", ["Bargeld", "nur Wünschen", "nur Worten"], "Bargeld", "Bar = Scheine/Münzen."),
            V("Ein Budget ist ein ...", ["geplanter Geldbetrag", "Film", "Sportplatz"], "geplanter Geldbetrag", "Budget = Finanzplan."),
            V("Teuer ist das Gegenteil von ...", ["billig / günstig", "laut", "schnell"], "billig / günstig", "Preisgegensatz."),
            V("Eine Quittung beweist den ...", ["Kauf", "Traum", "Wetterbericht"], "Kauf", "Quittung = Beleg."),
            G("Das ist der Preis ___ neuen Handys.", ["des", "dem", "den"], "des", "Genitiv Neutrum: des."),
            G("Wegen ___ hohen Miete spare ich.", ["der", "die", "das"], "der", "Wegen + Genitiv."),
            G("Ich brauche Geld, ___ zu reisen.", ["um", "für", "bei"], "um", "Um ... zu."),
            G("Je weniger du ausgibst, ___ mehr sparst du.", ["desto", "als", "ob"], "desto", "Je ... desto ..."),
            G("Die Rechnung ___ schon bezahlt.", ["wurde", "worden", "werden sein"], "wurde", "Passiv Vergangenheit."),
            G("Er kauft ein, ___ er es braucht.", ["obwohl", "weil", "als"], "obwohl", "Kontrast: obwohl."),
            G("Statt ___ Autos nimmt sie den Bus.", ["eines", "einem", "einen"], "eines", "Statt + Genitiv."),
            G("Wir müssen ___ den Preis achten.", ["auf", "für", "mit"], "auf", "Achten auf."),
            G("Ohne ___ Geld kann man nicht einkaufen.", ["viel", "vielen", "vieles"], "viel", "Viel + unzählbar."),
            G("Der Wert ___ Produkts ist klar.", ["des", "dem", "den"], "des", "Genitiv Neutrum.")),

        CreateLesson(18, "Stadt und Land",
            V("In der Stadt gibt es oft ...", ["viele Geschäfte", "nur Kühe", "nur Wälder"], "viele Geschäfte", "Stadt = urbanes Leben."),
            V("Auf dem Land ist es oft ...", ["ruhiger", "lauter als die Disco", "voller U-Bahnen"], "ruhiger", "Land = weniger Lärm."),
            V("Ein Dorf hat meist ... Einwohner als eine Großstadt.", ["weniger", "mehr", "genau gleich immer"], "weniger", "Dörfer sind kleiner."),
            V("Öffentliche Verkehrsmittel findet man eher in der ...", ["Stadt", "Wüste ohne Wege", "Antarktis nur"], "Stadt", "Bus, Bahn, U-Bahn."),
            V("Frische Luft verbindet man oft mit dem ...", ["Land", "Bürohochhaus", "Parkhaus"], "Land", "Natur auf dem Land."),
            V("Miete in der Stadtmitte ist oft ...", ["hoch", "gratis", "nur symbolisch"], "hoch", "Zentrale Lagen teuer."),
            V("Ein Bauer arbeitet oft ...", ["auf dem Land", "im Callcenter nur", "im Flugzeugcockpit"], "auf dem Land", "Landwirtschaft."),
            V("Stau gibt es eher ...", ["in der Stadt", "auf dem Feld", "im Wald"], "in der Stadt", "Viel Verkehr = Stau."),
            V("Nachbarn kennt man auf dem Land oft ...", ["besser", "gar nicht immer", "nur online"], "besser", "Kleinere Gemeinschaft."),
            V("Ein Vorort liegt ...", ["am Rand der Stadt", "im Zentrum immer", "auf dem Meer"], "am Rand der Stadt", "Vorort = Randlage."),
            G("___ es in der Stadt laut ist, wohne ich gern hier.", ["Obwohl", "Weil", "Damit"], "Obwohl", "Konzessivsatz."),
            G("___ ich auf dem Land wohne, brauche ich ein Auto.", ["Weil", "Obwohl", "Ob"], "Weil", "Grundsatz."),
            G("Während ich in Berlin lebte, ___ ich oft Bahn.", ["fuhr", "gefahren", "fährst"], "fuhr", "Während + Präteritum."),
            G("Je größer die Stadt, ___ teurer die Miete.", ["desto", "als", "ob"], "desto", "Je ... desto ..."),
            G("Das Dorf, ___ ich komme, ist klein.", ["aus dem", "aus den", "aus der"], "aus dem", "Kommen aus + Relativ."),
            G("Statt ___ Stadt wählt er das Land.", ["der", "die", "das"], "der", "Statt + Genitiv."),
            G("Man lebt hier, ___ man Ruhe sucht.", ["weil", "obwohl", "als"], "weil", "Grund."),
            G("Die Stadt, ___ der ich arbeite, wächst.", ["in", "an", "auf"], "in", "Arbeiten in + Dativ."),
            G("Auf dem Land ___ es weniger Lärm.", ["gibt", "ist gibt", "sind"], "gibt", "Es gibt ..."),
            G("___ du in der Stadt oder auf dem Land?", ["Wohnst", "Wohnen", "Wohnt"], "Wohnst", "Bei du: wohnst.")),

        CreateLesson(19, "Geschichte und Erinnerung",
            V("Geschichte erzählt von der ...", ["Vergangenheit", "nur Zukunft", "nur Wetterkarte"], "Vergangenheit", "Geschichte = earlier times."),
            V("Eine Erinnerung ist etwas, das man ...", ["nicht vergisst", "sofort löscht", "nie erlebt hat"], "nicht vergisst", "Erinnerung = Gedächtnis."),
            V("Ein Denkmal erinnert an ...", ["Personen oder Ereignisse", "nur Rezepte", "nur Apps"], "Personen oder Ereignisse", "Denkmal = Mahnung."),
            V("Ein Museum zeigt oft ... Exponate.", ["historische", "nur frische", "nur laute"], "historische", "Historisch = geschichtlich."),
            V("Zeitzeugen haben etwas ...", ["selbst erlebt", "nur geträumt", "nur gelesen nie"], "selbst erlebt", "Zeitzeuge = Augenzeuge der Zeit."),
            V("Ein Krieg ist ein ... Konflikt.", ["gewaltvoller", "kulinarischer", "sportlicher nur"], "gewaltvoller", "Krieg = bewaffneter Konflikt."),
            V("Frieden bedeutet ...", ["kein Krieg", "nur Lärm", "nur Schulden"], "kein Krieg", "Frieden = Ruhe/Sicherheit."),
            V("Ein Tagebuch hilft bei ...", ["Erinnerungen", "Nur Kochen", "Nur Parken"], "Erinnerungen", "Schreiben bewahrt Erlebnisse."),
            V("Die Generation der Großeltern kennt oft andere ...", ["Zeiten", "Handys von heute nur", "Apps neu"], "Zeiten", "Andere Lebensbedingungen."),
            V("Vergessen ist das Gegenteil von ...", ["erinnern", "rennen", "kochen"], "erinnern", "Erinnern ↔ vergessen."),
            G("Nachdem er die Stadt ___ hatte, schrieb er einen Brief.", ["verlassen", "verlässt", "verlass"], "verlassen", "Plusquamperfekt: hatte + Partizip."),
            G("Als Kind ___ ich oft Geschichten gehört.", ["hatte", "habe war", "bin"], "hatte", "Plusquamperfekt mit haben."),
            G("Die Stadt, ___ er geboren wurde, ist alt.", ["in der", "in dem", "in den"], "in der", "Geboren in + feminin."),
            G("Bevor sie ankam, ___ wir schon gewartet.", ["hatten", "haben", "seid"], "hatten", "Vorzeitigkeit."),
            G("Das Denkmal ___ 1950 errichtet.", ["wurde", "worden", "wird sein"], "wurde", "Passiv Vergangenheit."),
            G("Ich erinnere mich ___ den Tag.", ["an", "auf", "über"], "an", "Sich erinnern an."),
            G("___ wir jung waren, gab es kein Smartphone.", ["Als", "Wenn", "Ob"], "Als", "Als + einmalige Vergangenheit."),
            G("Die Geschichte, ___ er erzählt, ist wahr.", ["die", "der", "dem"], "die", "Relativ Akkusativ."),
            G("Nachdem der Krieg ___ war, begann der Aufbau.", ["zu Ende", "endet", "ende"], "zu Ende", "Zu Ende sein."),
            G("Wir hatten alles ___, bevor der Film startete.", ["vergessen", "vergiss", "vergisst"], "vergessen", "Plusquamperfekt.")),

        CreateLesson(20, "Sprachen und Kommunikation",
            V("Kommunikation heißt ...", ["sich verständigen", "nur schweigen", "nur rennen"], "sich verständigen", "Kommunikation = Austausch."),
            V("Eine Muttersprache lernt man oft ...", ["als Kind", "nur im Alter von 80", "nie"], "als Kind", "Muttersprache = erste Sprache."),
            V("Übersetzen bedeutet: von einer Sprache in eine andere ...", ["übertragen", "kochen", "parken"], "übertragen", "Übersetzung."),
            V("Ein Dialekt ist eine ... Form einer Sprache.", ["regionale", "universelle immer", "nur schriftliche"], "regionale", "Dialekt = örtliche Variante."),
            V("Missverständnisse entstehen oft durch ...", ["unklare Worte", "nur Sonne", "nur Sport"], "unklare Worte", "Unklarheit → Missverständnis."),
            V("Körpersprache nutzt ...", ["Gesten und Mimik", "nur Passwörter", "nur Preise"], "Gesten und Mimik", "Nonverbal."),
            V("Fließend sprechen heißt: ...", ["ohne große Pausen", "nur einzelne Wörter", "nie antworten"], "ohne große Pausen", "Flüssig."),
            V("Ein Dolmetscher hilft bei ...", ["gesprochener Übersetzung", "nur Kochen", "nur Sport"], "gesprochener Übersetzung", "Dolmetschen = mündlich."),
            V("Wortschatz ist die Menge der ...", ["bekannten Wörter", "bekannten Städte nur", "bekannten Gerichte nur"], "bekannten Wörter", "Vokabular."),
            V("Höflich kommunizieren heißt oft: ...", ["bitte und danke sagen", "schreien", "unterbrechen immer"], "bitte und danke sagen", "Höflichkeit."),
            G("Ich lerne Deutsch, ___ ich in Deutschland arbeiten möchte.", ["damit", "obwohl", "als"], "damit", "Finalsatz: damit."),
            G("Es ist wichtig, klar ___.", ["zu sprechen", "sprechen", "sprichst"], "zu sprechen", "Infinitiv mit zu."),
            G("Er versucht, langsam ___.", ["zu erklären", "erklären", "erklärt"], "zu erklären", "Versuchen + zu."),
            G("Die Sprache, ___ sie spricht, klingt schön.", ["die", "der", "dem"], "die", "Relativ Akkusativ."),
            G("Ohne Übung ist es schwer, fließend ___.", ["zu werden", "werden", "wirst"], "zu werden", "Schwer + zu."),
            G("Wir üben, ___ besser zu verstehen.", ["um", "für", "bei"], "um", "Um ... zu."),
            G("Worüber ___ ihr gesprochen?", ["habt", "seid", "bist"], "habt", "Sprechen über + haben."),
            G("Je mehr du liest, ___ besser wird dein Wortschatz.", ["desto", "als", "ob"], "desto", "Je ... desto ..."),
            G("Sie fragt, ___ er Zeit hat.", ["ob", "als", "damit"], "ob", "Indirekte Ja/Nein-Frage."),
            G("Kommunikation gelingt, ___ man zuhört.", ["wenn", "als", "wohin"], "wenn", "Bedingung.")),

        CreateLesson(21, "Arbeit suchen",
            V("Eine Bewerbung schickt man für einen ...", ["Job", "Urlaub nur", "Film nur"], "Job", "Bewerbung = Jobantrag."),
            V("Ein Lebenslauf listet ...", ["Ausbildung und Erfahrung", "nur Hobbys ohne Arbeit", "nur Rezepte"], "Ausbildung und Erfahrung", "CV / Resume."),
            V("Ein Vorstellungsgespräch ist ein ...", ["Interview beim Arbeitgeber", "Familienfest", "Sportspiel"], "Interview beim Arbeitgeber", "Gespräch vor Einstellung."),
            V("Arbeitslos heißt: ohne ...", ["Job", "Namen", "Adresse immer"], "Job", "Ohne Beschäftigung."),
            V("Eine Stelle ist eine ...", ["offene Position", "nur Adresse", "nur Ampel"], "offene Position", "Stelle = Jobangebot."),
            V("Qualifikationen zeigen, was du ...", ["kannst", "isst", "träumst nur"], "kannst", "Fähigkeiten/Abschlüsse."),
            V("Ein Praktikum ist oft ...", ["kurze Berufserfahrung", "Dauerurlaub", "Rente"], "kurze Berufserfahrung", "Praktikum = Lernen im Job."),
            V("Gehalt ist das ...", ["Einkommen aus Arbeit", "Wetter", "Hobby"], "Einkommen aus Arbeit", "Lohn/Gehalt."),
            V("Frist bedeutet: bis wann etwas ...", ["fertig sein muss", "beginnen darf ewig", "egal ist"], "fertig sein muss", "Deadline."),
            V("Referenzen sind Personen, die dich ...", ["empfehlen können", "nur kennen vom Sehen nie", "kochend"], "empfehlen können", "Empfehlungen."),
            G("Ich ___ gern bei Ihnen arbeiten.", ["würde", "würdest", "würden"], "würde", "Höflicher Konjunktiv II."),
            G("___ Sie mir bitte eine Chance geben?", ["Könnten", "Können war", "Kannst"], "Könnten", "Höflich: könnten."),
            G("Es wäre gut, früh ___.", ["anzukommen", "ankommen", "kommst an"], "anzukommen", "Wäre + zu-Infinitiv."),
            G("Die Stelle, ___ ich mich bewerbe, ist interessant.", ["auf die", "auf der", "auf dem"], "auf die", "Sich bewerben auf."),
            G("Nachdem ich mich ___ hatte, wartete ich.", ["beworben", "bewirbst", "bewerb"], "beworben", "Plusquamperfekt."),
            G("Ohne Erfahrung ist es schwer, sofort ___.", ["genommen zu werden", "nehmen", "nimmt"], "genommen zu werden", "Passiv Infinitiv."),
            G("Ich frage mich, ___ ich genug kann.", ["ob", "als", "damit"], "ob", "Ob-Satz."),
            G("Je besser der Lebenslauf, ___ größer die Chance.", ["desto", "als", "ob"], "desto", "Je ... desto ..."),
            G("Er hofft ___, bald eine Antwort zu bekommen.", ["darauf", "darüber", "davon"], "darauf", "Hoffen auf."),
            G("Wir würden uns freuen, Sie ___.", ["kennenzulernen", "kennenlernen", "kennst"], "kennenzulernen", "Zu-Infinitiv getrennt.")),

        CreateLesson(22, "Probleme lösen",
            V("Ein Problem ist etwas ...", ["Schwieriges", "Immer Einfaches", "Nur Leckeres"], "Schwieriges", "Problem = Schwierigkeit."),
            V("Eine Lösung hilft, das Problem zu ...", ["beenden", "vergrößern", "ignorieren ewig"], "beenden", "Lösung = Ausweg."),
            V("Konflikt bedeutet oft ...", ["Streit oder Gegensatz", "nur Harmonie", "nur Pause"], "Streit oder Gegensatz", "Konflikt = Spannung."),
            V("Kompromiss heißt: beide Seiten ...", ["geben nach", "gewinnen alles", "verlieren alles"], "geben nach", "Mittelweg."),
            V("Hilfe suchen ist oft ...", ["sinnvoll", "sinnlos immer", "verboten"], "sinnvoll", "Unterstützung holen."),
            V("Ursache ist der ... eines Problems.", ["Grund", "Zufall immer", "Schmuck"], "Grund", "Ursache = warum."),
            V("Strategie ist ein ... Plan.", ["durchdachter", "zufälliger nur", "leerer"], "durchdachter", "Vorgehen."),
            V("Stress entsteht bei zu vielen ...", ["Anforderungen", "Pausen", "Ferien"], "Anforderungen", "Überlastung."),
            V("Prioritäten setzen heißt: ...", ["Wichtiges zuerst", "Alles gleichzeitig", "Nichts tun"], "Wichtiges zuerst", "Reihenfolge."),
            V("Feedback gibt ... zur Verbesserung.", ["Rückmeldung", "Geld immer", "Urlaub"], "Rückmeldung", "Feedback = Rückmeldung."),
            G("Wir sprechen, ___ eine Lösung zu finden.", ["um", "für", "bei"], "um", "Um ... zu."),
            G("Ich rufe an, ___ du Bescheid weißt.", ["damit", "obwohl", "als"], "damit", "Finalsatz."),
            G("Statt zu streiten, ___ wir reden.", ["sollten", "sollt war", "soll"], "sollten", "Rat mit sollten."),
            G("Das Problem ___ schnell gelöst.", ["wurde", "worden", "wird sein"], "wurde", "Passiv."),
            G("Es ist nötig, ruhig ___.", ["zu bleiben", "bleiben", "bleibst"], "zu bleiben", "Nötig + zu."),
            G("Je früher wir handeln, ___ besser.", ["desto", "als", "ob"], "desto", "Je ... desto ..."),
            G("Er fragt, ___ jemand helfen kann.", ["ob", "als", "damit"], "ob", "Ob-Satz."),
            G("Ohne Plan ist es schwer, erfolgreich ___.", ["zu sein", "sein", "bist"], "zu sein", "Schwer + zu."),
            G("Nachdem wir gesprochen ___, war alles klar.", ["hatten", "haben", "seid"], "hatten", "Plusquamperfekt."),
            G("Man muss ___, dem anderen zuzuhören.", ["lernen", "lernt", "lern"], "lernen", "Lernen + zu.")),

        CreateLesson(23, "Natur und Tiere",
            V("Natur umfasst z. B. ...", ["Wälder und Flüsse", "Nur Büros", "Nur Apps"], "Wälder und Flüsse", "Natur = Umwelt."),
            V("Ein Wald besteht aus vielen ...", ["Bäumen", "Autos", "Tischen"], "Bäumen", "Wald = Bäume."),
            V("Tiere leben oft in ihrem ...", ["Lebensraum", "Büro", "Kino"], "Lebensraum", "Habitat."),
            V("Umweltschutz bedeutet: die Natur ...", ["schützen", "zerstören", "ignorieren"], "schützen", "Schutz der Umwelt."),
            V("Ein Fluss fließt zum ...", ["Meer oder See", "Himmel", "Keller immer"], "Meer oder See", "Wasserlauf."),
            V("Bedrohte Arten brauchen ...", ["Schutz", "nur Lärm", "nur Beton"], "Schutz", "Artenschutz."),
            V("Recycling hilft, Müll zu ...", ["vermeiden / wiederverwenden", "vermehren", "verstecken nur"], "vermeiden / wiederverwenden", "Kreislauf."),
            V("Ein Zoo zeigt Tiere oft ...", ["außerhalb der Wildnis", "nur im Buch", "nur online"], "außerhalb der Wildnis", "Zoo = Haltung zur Schau."),
            V("Klima beschreibt langfristiges ...", ["Wettergeschehen", "Essen", "Sportregeln"], "Wettergeschehen", "Klima ≠ Wetter kurz."),
            V("Nachhaltig handeln heißt: Ressourcen ...", ["schonend nutzen", "verschwenden", "ignorieren"], "schonend nutzen", "Nachhaltigkeit."),
            G("Der Wald, ___ wir spazieren, ist groß.", ["in dem", "in den", "in der"], "in dem", "Spazieren in + Dativ."),
            G("Tiere, ___ bedroht sind, brauchen Hilfe.", ["die", "der", "dem"], "die", "Relativ Nominativ Plural."),
            G("Je sauberer die Luft, ___ gesünder leben wir.", ["desto", "als", "ob"], "desto", "Je ... desto ..."),
            G("Man sollte weniger Plastik ___.", ["verbrauchen", "verbraucht", "verbrauch"], "verbrauchen", "Modal + Infinitiv."),
            G("Der Fluss, an ___ wir sitzen, ist klar.", ["dem", "den", "der"], "dem", "An + Dativ Relativ."),
            G("Es ist wichtig, die Natur ___.", ["zu schützen", "schützen", "schützt"], "zu schützen", "Wichtig + zu."),
            G("Nachdem es geregnet ___, wuchs Gras.", ["hatte", "hat war", "ist"], "hatte", "Plusquamperfekt."),
            G("Ohne Wasser können Tiere nicht ___.", ["leben", "lebt", "lebst"], "leben", "Können + Infinitiv."),
            G("Die Art, ___ ausstirbt, ist selten.", ["die", "der", "dem"], "die", "Relativ feminin."),
            G("Wir freuen uns ___, dass die Luft besser wird.", ["darüber", "darauf", "davon"], "darüber", "Sich freuen über.")),

        CreateLesson(24, "Wünsche und Träume",
            V("Ein Wunsch ist etwas, das man ...", ["gern hätte", "schon besitzt immer", "hasst"], "gern hätte", "Wunsch = Begehren."),
            V("Ein Traum kann nachts oder als ... kommen.", ["Lebensziel", "Rechnung", "Ampel"], "Lebensziel", "Traum = Vision."),
            V("Hoffnung bedeutet: an etwas Gutes ...", ["glauben", "zweifeln immer", "vergessen"], "glauben", "Hoffnung = Zuversicht."),
            V("Ein Ziel gibt der Zukunft eine ...", ["Richtung", "Pause nur", "Farbe nur"], "Richtung", "Ziel steuert Handeln."),
            V("Motivation hilft, weiterzu ...", ["machen", "schlafen ewig", "aufgeben sofort"], "machen", "Antrieb."),
            V("Realistisch heißt: im Rahmen des ...", ["Möglichen", "Unmöglichen immer", "Verbotenen"], "Möglichen", "Machbar."),
            V("Fantasie braucht man für ...", ["kreative Ideen", "nur Rechnungen", "nur Ampeln"], "kreative Ideen", "Vorstellungsvermögen."),
            V("Erfolg kommt oft nach ...", ["Anstrengung", "nur Glück immer", "nur Schlaf"], "Anstrengung", "Arbeit + Glück."),
            V("Zufrieden sein heißt: mit dem Leben ...", ["einverstanden", "wütend", "gleichgültig immer"], "einverstanden", "Zufriedenheit."),
            V("Pläne machen hilft, Träume zu ...", ["erreichen", "vergessen", "zerstören"], "erreichen", "Planung."),
            G("Ich ___ gern um die Welt reisen.", ["würde", "würdest", "würden"], "würde", "Konjunktiv II Wunsch."),
            G("___ du Zeit hättest, kämen wir mit.", ["Wenn", "Als", "Ob"], "Wenn", "Irreale Bedingung."),
            G("Es wäre schön, mehr Freizeit ___.", ["zu haben", "haben", "hast"], "zu haben", "Wäre + zu."),
            G("Er wünscht sich, dass alles gut ___.", ["wird", "werden", "wirst"], "wird", "Dass-Satz."),
            G("Wir ___ lieber zu Hause bleiben.", ["würden", "würde", "würdest"], "würden", "Bei wir: würden."),
            G("Je klarer das Ziel, ___ leichter der Weg.", ["desto", "als", "ob"], "desto", "Je ... desto ..."),
            G("Ohne Mut ist es schwer, Träume ___.", ["zu verwirklichen", "verwirklichen", "verwirklichst"], "zu verwirklichen", "Schwer + zu."),
            G("Was ___ ihr euch zum Geburtstag?", ["wünscht", "wünschen", "wünschst"], "wünscht", "Bei ihr: wünscht."),
            G("Ich hoffe, bald meinen Traum ___.", ["zu erreichen", "erreichen", "erreicht"], "zu erreichen", "Hoffen + zu."),
            G("An deiner Stelle ___ ich es versuchen.", ["würde", "würdest", "würden"], "würde", "Ratschlag Konjunktiv II.")),
    ];

    private static QuizContentLesson CreateLesson(
        int number,
        string title,
        params (QuizCategory Category, string Prompt, string[] Options, string CorrectAnswer, string Explanation)[] questions)
    {
        var lessonId = Guid.Parse($"23232323-2323-2323-2323-{number:000000000000}");
        var baseQuestionId = number * 100 + 1;

        return new QuizContentLesson(
            new Lesson(lessonId, "Menschen", "A2.2", number, title),
            questions.Select((question, index) => new QuizQuestion(
                Guid.Parse($"24200000-0000-0000-0000-{baseQuestionId + index:000000000000}"),
                lessonId,
                question.Category,
                QuestionType.MultipleChoice,
                question.Prompt,
                question.Options,
                question.CorrectAnswer,
                question.Explanation)).ToList());
    }

    private static (QuizCategory Category, string Prompt, string[] Options, string CorrectAnswer, string Explanation) V(
        string prompt, string[] options, string correctAnswer, string explanation) =>
        (QuizCategory.Vocabulary, prompt, options, correctAnswer, explanation);

    private static (QuizCategory Category, string Prompt, string[] Options, string CorrectAnswer, string Explanation) G(
        string prompt, string[] options, string correctAnswer, string explanation) =>
        (QuizCategory.Grammar, prompt, options, correctAnswer, explanation);
}
