using DeutschQuiz.Domain;

namespace DeutschQuiz.Application;

/// <summary>
/// Independent quiz catalogue for Menschen B1.2 (Lektionen 13–24).
/// Prompts are original for DeutschQuiz and are not copied from the textbook.
/// </summary>
public static class MenschenB12QuizContentCatalog
{
    public static IReadOnlyList<QuizContentLesson> Lessons { get; } =
    [
        CreateLesson(13, "Literatur und Lesen",
            V("Was ist ein Roman?", ["Ein längeres Erzählwerk in Prosa", "Ein kurzes Gedicht", "Ein Zeitungsartikel"], "Ein längeres Erzählwerk in Prosa", "Romane erzählen ausführliche Geschichten."),
            V("Was bedeutet: den Inhalt zusammenfassen?", ["Das Wichtigste kurz wiedergeben", "Jedes Wort abschreiben", "Nur die Titelseite lesen"], "Das Wichtigste kurz wiedergeben", "Zusammenfassen heißt, Kernaussagen knapper zu formulieren."),
            V("Ein Krimi handelt oft von ...", ["einem Verbrechen und seiner Aufklärung", "Kochrezepten", "Wetterprognosen"], "einem Verbrechen und seiner Aufklärung", "Krimis drehen sich um Rätsel und Verbrechen."),
            V("Was ist eine Biografie?", ["Die Lebensgeschichte einer Person", "Eine Liste von Verben", "Ein Fahrplan"], "Die Lebensgeschichte einer Person", "Biografien beschreiben echte Lebensläufe."),
            V("Wer schreibt Gedichte?", ["Ein Dichter / eine Dichterin", "Ein Busfahrer nur wegen der Route", "Ein Thermometer"], "Ein Dichter / eine Dichterin", "Gedichte verfassen Autoren literarisch."),
            V("Was bedeutet: zwischen den Zeilen lesen?", ["Verborgene Bedeutungen verstehen", "Nur die Seitenzahl zählen", "Laut buchstabieren"], "Verborgene Bedeutungen verstehen", "Es geht um indirekte Aussagen."),
            V("Ein Bestseller ist ein Buch, das ...", ["besonders erfolgreich verkauft wird", "nie gedruckt wird", "nur handgeschrieben existiert"], "besonders erfolgreich verkauft wird", "Bestseller verkaufen sich sehr gut."),
            V("Was macht ein Lektor?", ["Prüft und verbessert Manuskripte", "Druckt Münzen", "Baut Bibliotheken aus Holz"], "Prüft und verbessert Manuskripte", "Lektoren redigieren Texte vor der Veröffentlichung."),
            V("Eine Novelle ist im Vergleich zum Roman oft ...", ["kürzer und konzentrierter", "länger und ohne Handlung", "nur ein Wörterbuch"], "kürzer und konzentrierter", "Novellen sind kürzere Prosawerke."),
            V("Was bedeutet: kritisieren?", ["Stärken und Schwächen bewerten", "Nur loben ohne Grund", "Den Text vernichten"], "Stärken und Schwächen bewerten", "Kritik analysiert und bewertet."),
            G("Das Buch, ___ ich gestern gelesen habe, war spannend.", ["das", "die", "der"], "das", "Relativpronomen Neutrum: das Buch → das."),
            G("Die Autorin, ___ Romane berühmt sind, lebt in Berlin.", ["deren", "deren Buch", "deren dem"], "deren", "Genitiv Relativ: deren."),
            G("Wenn ich mehr Zeit ___, würde ich jeden Tag lesen.", ["hätte", "habe", "hatte"], "hätte", "Irrealer Konditionalsatz: hätte."),
            G("Der Roman ___ von Millionen Menschen gelesen.", ["wurde", "wurde sein", "ist worden lesen"], "wurde", "Passiv Präteritum: wurde gelesen."),
            G("Je mehr man liest, ___ besser wird das Sprachgefühl.", ["desto", "umso als", "je"], "desto", "Je … desto …"),
            G("Er behauptet, das Buch schon ___ zu haben.", ["gelesen", "lesen", "liest"], "gelesen", "Infinitiv Perfekt nach behaupten."),
            G("Ohne regelmäßig zu ___, verbessert man sich kaum.", ["lesen", "liest", "gelesen"], "lesen", "Infinitiv nach ohne … zu."),
            G("Mir gefällt der Stil, ___ der Autor schreibt.", ["in dem", "in den", "in der"], "in dem", "Präposition + Relativ: in dem Stil."),
            G("Es wird empfohlen, kritische Texte ___ zu lesen.", ["sorgfältig", "sorgfältiger als", "am sorgfältig"], "sorgfältig", "Adverb zum Infinitiv."),
            G("Hätte sie das Vorwort ___, hätte sie die These verstanden.", ["gelesen", "lesen", "liest"], "gelesen", "Konjunktiv II Perfekt: hätte gelesen.")),

        CreateLesson(14, "Musik und Kunst",
            V("Was ist eine Ausstellung?", ["Eine öffentliche Präsentation von Kunstwerken", "Ein Konzert nur für Köche", "Ein Wetterbericht"], "Eine öffentliche Präsentation von Kunstwerken", "Ausstellungen zeigen Kunst."),
            V("Ein Orchester besteht aus ...", ["vielen Instrumentalisten", "nur einem Sänger ohne Instrumente", "nur Lautsprechern"], "vielen Instrumentalisten", "Orchester sind große Ensembles."),
            V("Was bedeutet: improvisieren?", ["Ohne festes Skript spontan spielen", "Nur Noten abschreiben", "Das Publikum zählen"], "Ohne festes Skript spontan spielen", "Improvisation entsteht im Moment."),
            V("Eine Skulptur ist ...", ["ein dreidimensionales Kunstwerk", "nur ein Foto", "eine Melodie"], "ein dreidimensionales Kunstwerk", "Skulpturen sind plastisch."),
            V("Was macht ein Dirigent?", ["Leitet das Orchester", "Verkauft Tickets an der Garderobe", "Stimmt nur eine Saite"], "Leitet das Orchester", "Dirigenten koordinieren das Ensemble."),
            V("Abstrakte Kunst zeigt oft ...", ["Formen und Farben ohne realistische Abbildung", "nur Landkarten", "Fahrpläne"], "Formen und Farben ohne realistische Abbildung", "Abstrakt = nicht gegenständlich."),
            V("Was ist eine Vernissage?", ["Die Eröffnung einer Ausstellung", "Das Ende eines Romans", "Eine Steuererklärung"], "Die Eröffnung einer Ausstellung", "Vernissage = Ausstellungseröffnung."),
            V("Ein Hit ist ein Song, der ...", ["sehr populär wird", "nie gespielt wird", "nur instrumental ohne Melodie sein muss"], "sehr populär wird", "Hits sind besonders erfolgreich."),
            V("Was bedeutet: kritisches Publikum?", ["Zuschauer, die genau und anspruchsvoll urteilen", "Leute, die nur klatschen", "Nur Kinder im Museum"], "Zuschauer, die genau und anspruchsvoll urteilen", "Kritisch = wählerisch und prüfend."),
            V("Streetart findet man oft ...", ["im öffentlichen Raum / an Wänden", "nur in Tresoren", "nur in Bibliotheken unter Glas"], "im öffentlichen Raum / an Wänden", "Streetart ist Kunst im Stadtraum."),
            G("Das Gemälde, ___ wir bewundern, hängt im Museum.", ["das", "die", "dem"], "das", "Relativ Neutrum Akkusativ: das."),
            G("Die Musik ___ live aufgenommen.", ["wurde", "wurde sein", "ist werden"], "wurde", "Passiv: wurde aufgenommen."),
            G("Je lauter die Band spielt, ___ begeisterter reagiert das Publikum.", ["desto", "je", "als"], "desto", "Je … desto …"),
            G("Er spielt Gitarre, ___ er noch nie Unterricht hatte.", ["obwohl", "weil", "damit"], "obwohl", "Konzessiv: obwohl."),
            G("Die Künstlerin, ___ Werke weltweit bekannt sind, kommt aus Wien.", ["deren", "deren den", "deren dem"], "deren", "Genitiv Plural/Feminin: deren."),
            G("Man sollte Kunstwerke nicht ___ berühren.", ["einfach", "einfacher", "am einfachen"], "einfach", "Adverb: nicht einfach berühren."),
            G("Würde ich besser zeichnen ___, würde ich an der Ausstellung teilnehmen.", ["können", "kann", "gekonnt"], "können", "Konjunktiv II: würde … können."),
            G("Das Konzert findet statt, ___ das Wetter schlecht ist.", ["auch wenn", "damit", "statt"], "auch wenn", "Konzessive Konjunktion."),
            G("Die Ausstellung ___ von tausenden Besuchern besucht.", ["wurde", "wurde haben", "ist worden besuchen"], "wurde", "Passiv Präteritum."),
            G("Ohne zu ___, versteht man abstrakte Kunst oft schwer.", ["üben", "übt", "geübt"], "üben", "ohne … zu + Infinitiv.")),

        CreateLesson(15, "Wirtschaft im Alltag",
            V("Was ist Inflation?", ["Steigende Preise / sinkende Kaufkraft", "Ein Feiertag", "Ein Musikstil"], "Steigende Preise / sinkende Kaufkraft", "Inflation bedeutet Preissteigerung."),
            V("Ein Haushaltsbudget hilft dabei, ...", ["Einnahmen und Ausgaben zu planen", "nur Urlaub zu buchen", "Steuern zu erfinden"], "Einnahmen und Ausgaben zu planen", "Budget = finanzielle Planung."),
            V("Was bedeutet: sparen?", ["Geld zurücklegen statt alles auszugeben", "Sofort alles ausgeben", "Nur bar bezahlen müssen"], "Geld zurücklegen statt alles auszugeben", "Sparen = Rücklagen bilden."),
            V("Ein Kredit ist ...", ["geliehenes Geld, das man zurückzahlt", "ein Geschenk ohne Pflicht", "eine Steuererstattung"], "geliehenes Geld, das man zurückzahlt", "Kredite müssen getilgt werden."),
            V("Was ist Mehrwertsteuer?", ["Eine Steuer auf Waren und Dienstleistungen", "Ein Bonus vom Chef", "Ein Sparbuch"], "Eine Steuer auf Waren und Dienstleistungen", "MwSt. wird auf Preise erhoben."),
            V("Angebot und Nachfrage bestimmen oft ...", ["den Preis", "die Grammatik", "die Uhrzeit"], "den Preis", "Marktmechanismus: Preisbildung."),
            V("Was bedeutet: nachhaltig wirtschaften?", ["Ressourcen langfristig verantwortungsvoll nutzen", "Nur kurzfristig Gewinn maximieren", "Gar nichts produzieren"], "Ressourcen langfristig verantwortungsvoll nutzen", "Nachhaltigkeit denkt an die Zukunft."),
            V("Ein Verbraucher ist ...", ["jemand, der Waren oder Dienste nutzt", "nur ein Produzent", "eine Bankfiliale"], "jemand, der Waren oder Dienste nutzt", "Verbraucher = Konsument."),
            V("Was ist ein Gehalt?", ["Regelmäßige Bezahlung für Arbeit", "Ein spontanes Trinkgeld nur", "Eine Strafe"], "Regelmäßige Bezahlung für Arbeit", "Gehalt = Entgelt."),
            V("Online-Banking ermöglicht ...", ["Geldgeschäfte digital zu erledigen", "nur Bargeld zu drucken", "Steuern abzuschaffen"], "Geldgeschäfte digital zu erledigen", "Banking über das Internet."),
            G("Wenn die Preise ___, sinkt die Kaufkraft.", ["steigen", "steigt", "gestiegen sind ohne wenn"], "steigen", "Konditionalsatz Präsens."),
            G("Das Geld ___ auf dem Sparkonto angelegt.", ["wurde", "wurde sein", "ist werden"], "wurde", "Passiv: wurde angelegt."),
            G("Je höher die Zinsen, ___ teurer wird der Kredit.", ["desto", "umso als", "je"], "desto", "Je … desto …"),
            G("Er gibt mehr aus, ___ er verdient.", ["als", "wie", "denn"], "als", "Vergleich bei Ungleichheit: als."),
            G("Ohne zu ___, gerät man leicht in Schulden.", ["planen", "plant", "geplant"], "planen", "ohne … zu + Infinitiv."),
            G("Die Rechnung, ___ ich bezahlt habe, war korrekt.", ["die", "der", "das"], "die", "Relativ feminin Akkusativ: die."),
            G("Man sollte vergleichen, bevor man etwas ___.", ["kauft", "kaufen", "gekauft"], "kauft", "Temporal: bevor + Präsens."),
            G("Würden die Kosten sinken, ___ mehr Menschen investieren.", ["würden", "werden", "wurden"], "würden", "Irrealer Konditionalsatz."),
            G("Der Vertrag ___ von beiden Seiten unterschrieben.", ["wurde", "wurde haben", "ist unterschreiben"], "wurde", "Passiv Präteritum."),
            G("Obwohl sie sparsam ___, bleibt wenig übrig.", ["lebt", "leben", "gelebt"], "lebt", "obwohl + Konjugation.")),

        CreateLesson(16, "Klima und Verantwortung",
            V("Was ist der Treibhauseffekt?", ["Erwärmung der Erde durch bestimmte Gase", "Ein Kühlschrankprinzip im Sommer", "Ein Musikfestival"], "Erwärmung der Erde durch bestimmte Gase", "Treibhausgase halten Wärme zurück."),
            V("Nachhaltigkeit bedeutet ...", ["heutige Bedürfnisse ohne Schaden für die Zukunft zu erfüllen", "alles sofort zu verbrauchen", "Natur komplett zu ignorieren"], "heutige Bedürfnisse ohne Schaden für die Zukunft zu erfüllen", "Nachhaltig = zukunftsfähig."),
            V("Was reduziert den CO₂-Ausstoß im Alltag?", ["Öfter öffentliche Verkehrsmittel nutzen", "Nur das Auto für kurze Wege", "Heizung maximal aufdrehen"], "Öfter öffentliche Verkehrsmittel nutzen", "Weniger Individualverkehr spart Emissionen."),
            V("Recycling heißt ...", ["Wertstoffe wiederverwerten", "Alles in den Restmüll werfen", "Nur neu kaufen"], "Wertstoffe wiederverwerten", "Recycling = Kreislaufnutzung."),
            V("Was ist erneuerbare Energie?", ["Energie aus Sonne, Wind, Wasser u. a.", "Nur Kohle und Öl", "Energie aus Plastikmüll allein"], "Energie aus Sonne, Wind, Wasser u. a.", "Erneuerbar = nachhaltig erzeugbar."),
            V("Dürre bedeutet ...", ["anhaltende Trockenheit", "Dauerregen", "Schnee im Sommer nur"], "anhaltende Trockenheit", "Dürre = Wassermangel."),
            V("Was bedeutet: ökologischer Fußabdruck?", ["Maß für Umweltbelastung durch Lebensstil", "Schuhgröße in der Natur", "Ein Wanderweg"], "Maß für Umweltbelastung durch Lebensstil", "Fußabdruck misst Ressourcenverbrauch."),
            V("Klimaschutz zielt darauf ab, ...", ["die Erderwärmung zu begrenzen", "mehr Abfall zu erzeugen", "Wälder abzuholzen"], "die Erderwärmung zu begrenzen", "Klimaschutz = Emissionen senken."),
            V("Was ist Biodiversität?", ["Vielfalt der Arten und Lebensräume", "Nur eine Tierart", "Ein Börsenindex"], "Vielfalt der Arten und Lebensräume", "Biodiversität = Artenvielfalt."),
            V("Verantwortung übernehmen heißt ...", ["für Folgen des eigenen Handelns einstehen", "alles anderen zuschieben", "Probleme leugnen"], "für Folgen des eigenen Handelns einstehen", "Verantwortung = Rechenschaft."),
            G("Wenn wir weniger fliegen würden, ___ die Emissionen.", ["sänken", "sinken", "sanken"], "sänken", "Irrealer Konditionalsatz: sänken."),
            G("Je mehr Wälder man schützt, ___ besser ist das Klima.", ["desto", "je", "als"], "desto", "Je … desto …"),
            G("Müll ___ getrennt gesammelt.", ["wird", "wurde sein", "ist werden"], "wird", "Passiv Präsens: wird gesammelt."),
            G("Obwohl viele Bescheid ___, ändert sich zu wenig.", ["wissen", "weiß", "gewusst"], "wissen", "obwohl + Plural."),
            G("Es lohnt sich, den Verbrauch ___ zu senken.", ["möglichst", "möglichster", "am möglichen"], "möglichst", "möglichst = so weit wie möglich."),
            G("Viele fordern, dass Unternehmen strenger ___ werden.", ["kontrolliert", "kontrollieren", "kontrolliert hat"], "kontrolliert", "Passiv: kontrolliert werden."),
            G("Die Maßnahmen, ___ beschlossen wurden, greifen langsam.", ["die", "der", "das"], "die", "Relativ Plural Nominativ: die."),
            G("Ohne konsequent zu ___, erreicht man die Klimaziele nicht.", ["handeln", "handelt", "gehandelt"], "handeln", "ohne … zu + Infinitiv."),
            G("Hätte man früher reagiert, ___ die Lage besser.", ["wäre", "ist", "war"], "wäre", "Irrealer Konditionalsatz Vergangenheit."),
            G("Der Bericht ___ von Experten veröffentlicht.", ["wurde", "wurde haben", "ist veröffentlichen"], "wurde", "Passiv Präteritum.")),

        CreateLesson(17, "Migration und Heimat",
            V("Was bedeutet Migration?", ["Dauerhafter oder längerer Wohnortwechsel", "Nur ein Wochenendausflug", "Ein Musikstil"], "Dauerhafter oder längerer Wohnortwechsel", "Migration = Wandern / Umziehen über Grenzen oder Regionen."),
            V("Heimat ist oft ...", ["der Ort oder das Gefühl von Zugehörigkeit", "nur ein Passstempel", "eine Steuerklasse"], "der Ort oder das Gefühl von Zugehörigkeit", "Heimat kann geografisch oder emotional sein."),
            V("Was ist Integration?", ["Teilhabe am gesellschaftlichen Leben", "Vollständige Isolation", "Nur Sprachtests ohne Alltag"], "Teilhabe am gesellschaftlichen Leben", "Integration = Mitwirken und Aufnehmen."),
            V("Ein Flüchtling sucht Schutz vor ...", ["Verfolgung, Krieg oder Gefahr", "guten Jobangeboten nur", "Urlaubsstress"], "Verfolgung, Krieg oder Gefahr", "Flüchtlinge fliehen vor Not."),
            V("Was bedeutet: kulturelle Vielfalt?", ["Unterschiedliche Kulturen leben zusammen", "Nur eine Kultur ist erlaubt", "Gleichheit der Passnummern"], "Unterschiedliche Kulturen leben zusammen", "Vielfalt = Pluralität."),
            V("Ein Visum ist ...", ["eine Einreiseerlaubnis", "ein Bahnticket", "ein Mietvertrag"], "eine Einreiseerlaubnis", "Visa regeln Aufenthalt/Einreise."),
            V("Was heißt: Heimweh haben?", ["Sehnsucht nach dem vertrauten Ort", "Freude am Reisen ohne Ende", "Hunger nach Spezialitäten nur"], "Sehnsucht nach dem vertrauten Ort", "Heimweh = Sehnsucht nach zu Hause."),
            V("Ein Pass dokumentiert ...", ["die Identität und Staatsangehörigkeit", "nur den Beruf", "nur das Lieblingsessen"], "die Identität und Staatsangehörigkeit", "Reisepass = Ausweisdokument."),
            V("Was bedeutet: Vorurteile abbauen?", ["Unfaire Annahmen hinterfragen und reduzieren", "Mehr Stereotypen verbreiten", "Nur Statistiken ignorieren"], "Unfaire Annahmen hinterfragen und reduzieren", "Vorurteile sind ungeprüfte Meinungen."),
            V("Asyl beantragen heißt ...", ["um Schutz im Aufnahmeland bitten", "sofort die Staatsbürgerschaft kaufen", "nur touristisch einreisen"], "um Schutz im Aufnahmeland bitten", "Asyl = Schutzstatus."),
            G("Die Menschen, ___ ausgewandert sind, vermissen oft ihre Familie.", ["die", "der", "das"], "die", "Relativ Plural: die."),
            G("Je besser die Sprachkenntnisse, ___ leichter fällt die Integration.", ["desto", "je", "als"], "desto", "Je … desto …"),
            G("Obwohl er neu ___, engagiert er sich schon im Verein.", ["ist", "sein", "gewesen"], "ist", "obwohl + Präsens."),
            G("Der Antrag ___ sorgfältig geprüft.", ["wurde", "wurde sein", "ist prüfen"], "wurde", "Passiv Präteritum."),
            G("Wenn ich in einem anderen Land ___, würde ich die Sprache lernen.", ["lebte", "lebe", "gelebt"], "lebte", "Irrealer Konditionalsatz."),
            G("Ohne Hilfe zu ___, wäre der Start schwerer gewesen.", ["bekommen", "bekommt", "bekam"], "bekommen", "ohne … zu + Infinitiv."),
            G("Die Stadt, in ___ sie wohnen, ist multikulturell.", ["der", "die", "das"], "der", "Präposition in + Dativ feminin: in der."),
            G("Man sollte respektieren, ___ andere Traditionen haben.", ["dass", "ob nur", "als"], "dass", "dass-Satz nach respektieren."),
            G("Hätte er früher Unterstützung ___, wäre die Eingewöhnung leichter gewesen.", ["erhalten", "erhält", "erhielt"], "erhalten", "Konjunktiv II Perfekt: hätte erhalten."),
            G("Vielfalt ___ als Stärke gesehen.", ["wird", "wurde sein", "ist werden"], "wird", "Passiv Präsens.")),

        CreateLesson(18, "Digitale Welt",
            V("Was ist Datenschutz?", ["Schutz persönlicher Informationen", "Nur schnelleres WLAN", "Ein Computerspiel"], "Schutz persönlicher Informationen", "Datenschutz regelt den Umgang mit Daten."),
            V("Phishing versucht, ...", ["Zugangsdaten durch Betrug zu erlangen", "nur Werbung zu blockieren", "Hardware zu reparieren"], "Zugangsdaten durch Betrug zu erlangen", "Phishing = digitale Betrugsmasche."),
            V("Was bedeutet: cloudbasiert?", ["Daten liegen auf entfernten Servern", "Nur auf Papier", "Nur offline auf CDs"], "Daten liegen auf entfernten Servern", "Cloud = Speicherung im Netz."),
            V("Künstliche Intelligenz kann ...", ["Muster erkennen und Aufgaben automatisieren", "Gefühle wie Menschen fühlen müssen", "nur Bücher drucken"], "Muster erkennen und Aufgaben automatisieren", "KI analysiert und lernt aus Daten."),
            V("Was ist ein Algorithmus?", ["Eine schrittweise Rechenvorschrift", "Ein Passwort allein", "Ein Bildschirm"], "Eine schrittweise Rechenvorschrift", "Algorithmen steuern Abläufe."),
            V("Digitale Kompetenz heißt ...", ["Medien und Technik sinnvoll nutzen zu können", "Nur Smartphones zu sammeln", "Das Internet abzuschalten"], "Medien und Technik sinnvoll nutzen zu können", "Kompetenz = Können und Urteilen."),
            V("Was bedeutet: viral gehen?", ["Sich sehr schnell im Netz verbreiten", "Nur offline bleiben", "Einen Virus im Körper haben müssen"], "Sich sehr schnell im Netz verbreiten", "Viral = massive Verbreitung."),
            V("Zwei-Faktor-Authentifizierung erhöht ...", ["die Sicherheit von Konten", "nur die Lautstärke", "die Bildschirmauflösung"], "die Sicherheit von Konten", "2FA = zusätzliche Prüfung."),
            V("Was ist Open Source?", ["Software mit offenem, einsehbarem Quellcode", "Nur kostenpflichtige Apps", "Geheime Firmengeheimnisse"], "Software mit offenem, einsehbarem Quellcode", "Open Source = öffentlich zugänglich."),
            V("Cybermobbing ist ...", ["Belästigung und Angriffe über digitale Medien", "Freundliches Chatten", "Technischer Support"], "Belästigung und Angriffe über digitale Medien", "Mobbing im Netz."),
            G("Die App, ___ ich nutze, aktualisiert sich automatisch.", ["die", "der", "das"], "die", "Relativ feminin: die."),
            G("Passwörter ___ regelmäßig geändert werden.", ["sollten", "sollte", "soll"], "sollten", "Modal Plural: sollten."),
            G("Wer persönliche Daten teilt, ___ die Risiken kennen.", ["sollte", "sollten", "sollst"], "sollte", "Modal bei wer: sollte."),
            G("Je mehr Daten man teilt, ___ größer wird das Risiko.", ["desto", "je", "als"], "desto", "Je … desto …"),
            G("Obwohl die Verbindung ___, lädt die Seite langsam.", ["stabil ist", "stabil", "stabil sein"], "stabil ist", "obwohl + vollständiger Satz."),
            G("Die Nachricht ___ sofort gelöscht.", ["wurde", "wurde sein", "ist löschen"], "wurde", "Passiv Präteritum."),
            G("Ohne kritisch zu ___, glaubt man Fake News leichter.", ["prüfen", "prüft", "geprüft"], "prüfen", "ohne … zu + Infinitiv."),
            G("Würde man Quellen ___, gäbe es weniger Desinformation.", ["verifizieren", "verifiziert", "verifiziert hat"], "verifizieren", "würde + Infinitiv."),
            G("Der Server, auf ___ die Daten liegen, steht in Europa.", ["dem", "den", "der"], "dem", "Präposition auf + Dativ: auf dem."),
            G("Es wird empfohlen, Software aktuell ___ halten.", ["zu", "zum", "zur"], "zu", "empfohlen + zu + Infinitiv.")),

        CreateLesson(19, "Recht und Bürgerpflichten",
            V("Was ist die Verfassung?", ["Das grundlegende Regelwerk eines Staates", "Ein Mietvertrag", "Ein Fahrplan"], "Das grundlegende Regelwerk eines Staates", "Verfassung = Grundgesetz."),
            V("Bürgerpflichten sind zum Beispiel ...", ["Steuern zahlen und Gesetze beachten", "Nur fernsehen", "Wahlzettel wegwerfen müssen"], "Steuern zahlen und Gesetze beachten", "Pflichten gelten für Bürger."),
            V("Was bedeutet: Unschuldsvermutung?", ["Man gilt als unschuldig, bis Schuld bewiesen ist", "Jeder ist sofort schuldig", "Nur Zeugen sind unschuldig"], "Man gilt als unschuldig, bis Schuld bewiesen ist", "Grundsatz im Strafverfahren."),
            V("Ein Anwalt vertritt ...", ["die Interessen einer Partei vor Gericht", "nur die Polizei", "nur Journalisten"], "die Interessen einer Partei vor Gericht", "Anwälte beraten und vertreten."),
            V("Was ist ein Urteil?", ["Die Entscheidung eines Gerichts", "Eine Meinung in der Kantine", "Ein Wetterbericht"], "Die Entscheidung eines Gerichts", "Urteile schließen Verfahren ab."),
            V("Demokratie bedeutet unter anderem ...", ["Mitbestimmung durch Wahlen", "Herrschaft einer Person ohne Kontrolle", "Keine Rechte für Bürger"], "Mitbestimmung durch Wahlen", "Volksherrschaft mit Beteiligung."),
            V("Was heißt: Berufung einlegen?", ["Gegen ein Urteil Rechtsmittel nutzen", "Sofort aufgeben", "Nur applaudieren"], "Gegen ein Urteil Rechtsmittel nutzen", "Berufung = nächste Instanz."),
            V("Gleichheit vor dem Gesetz heißt ...", ["alle werden rechtlich gleich behandelt", "Reiche sind ausgenommen", "Nur Beamte haben Rechte"], "alle werden rechtlich gleich behandelt", "Rechtsgleichheit."),
            V("Was ist eine Geldbuße?", ["Eine finanzielle Strafe für Ordnungswidrigkeiten", "Ein Gehalt", "Ein Stipendium"], "Eine finanzielle Strafe für Ordnungswidrigkeiten", "Bußgeld bei Verstößen."),
            V("Zeugenaussage bedeutet ...", ["über Beobachtetes vor Gericht berichten", "Urteile selbst fällen", "Gesetze schreiben"], "über Beobachtetes vor Gericht berichten", "Zeugen schildern Wahrgenommenes."),
            G("Gesetze ___ von Parlamenten beschlossen.", ["werden", "wurde", "ist werden"], "werden", "Passiv Präsens Plural."),
            G("Jeder, ___ gegen Regeln verstößt, riskiert Strafen.", ["der", "die", "das"], "der", "Relativ maskulin: der."),
            G("Je klarer die Regeln, ___ besser funktioniert der Rechtsstaat.", ["desto", "je", "als"], "desto", "Je … desto …"),
            G("Obwohl er unschuldig ___, musste er aussagen.", ["war", "ist gewesen ohne obwohl", "sein"], "war", "obwohl + Präteritum."),
            G("Der Angeklagte ___ freigesprochen.", ["wurde", "wurde sein", "ist freisprechen"], "wurde", "Passiv Präteritum."),
            G("Man darf nicht handeln, ___ es das Gesetz verbietet.", ["wenn", "damit", "ohne"], "wenn", "Konditional: wenn."),
            G("Ohne Beweise zu ___, darf niemand verurteilt werden.", ["haben", "hat", "hatte"], "haben", "ohne … zu + Infinitiv."),
            G("Würden mehr Menschen wählen ___, wäre die Legitimation stärker.", ["gehen", "geht", "gegangen"], "gehen", "würde … gehen."),
            G("Die Rechte, ___ die Verfassung garantiert, sind grundlegend.", ["die", "der", "das"], "die", "Relativ Plural Akkusativ: die."),
            G("Es ist wichtig, dass Bürger ihre Pflichten ___.", ["erfüllen", "erfüllt", "erfüllst"], "erfüllen", "dass-Satz Plural.")),

        CreateLesson(20, "Forschung und Innovation",
            V("Was ist eine Hypothese?", ["Eine überprüfbare Annahme", "Ein bewiesenes Gesetz ohne Test", "Ein Zufallsergebnis"], "Eine überprüfbare Annahme", "Hypothesen werden getestet."),
            V("Innovation bedeutet ...", ["neue Ideen und Lösungen umsetzen", "nur Altes kopieren", "Forschung stoppen"], "neue Ideen und Lösungen umsetzen", "Innovation = Neuerung."),
            V("Was macht ein Experiment?", ["Prüft eine Annahme unter kontrollierten Bedingungen", "Erzählt nur Anekdoten", "Ersetzt Statistik immer"], "Prüft eine Annahme unter kontrollierten Bedingungen", "Experimente liefern Evidenz."),
            V("Peer-Review heißt ...", ["Fachleute prüfen wissenschaftliche Arbeiten", "Nur Laien kommentieren", "Sofortige Veröffentlichung ohne Kontrolle"], "Fachleute prüfen wissenschaftliche Arbeiten", "Qualitätssicherung in der Wissenschaft."),
            V("Was ist ein Prototyp?", ["Ein erstes funktionsfähiges Modell", "Das fertige Massenprodukt immer", "Nur eine Skizze ohne Form"], "Ein erstes funktionsfähiges Modell", "Prototypen testen Machbarkeit."),
            V("Grundlagenforschung sucht ...", ["grundlegendes Wissen ohne direkten Anwendungszwang", "nur schnelle Produkte", "nur Werbeslogans"], "grundlegendes Wissen ohne direkten Anwendungszwang", "Grundlage vor Anwendung."),
            V("Was bedeutet: patentieren?", ["Erfindung rechtlich schützen lassen", "Sofort veröffentlichen ohne Schutz", "Ideen geheim halten für immer ohne Antrag"], "Erfindung rechtlich schützen lassen", "Patent = Schutzrecht."),
            V("Ein Labor ist ...", ["ein Ort für wissenschaftliche Versuche", "nur ein Büro ohne Geräte", "ein Konzertsaal"], "ein Ort für wissenschaftliche Versuche", "Labore ermöglichen Experimente."),
            V("Was ist interdisziplinär?", ["Mehrere Fachrichtungen arbeiten zusammen", "Nur ein Fach ohne Austausch", "Zufällige Hobbyprojekte"], "Mehrere Fachrichtungen arbeiten zusammen", "Interdisziplinär = fächerübergreifend."),
            V("Nachhaltige Innovation achtet auf ...", ["Umwelt und langfristigen Nutzen", "nur kurzfristigen Gewinn", "Ressourcenverschwendung"], "Umwelt und langfristigen Nutzen", "Nachhaltig + innovativ."),
            G("Die Studie, ___ veröffentlicht wurde, ist umstritten.", ["die", "der", "das"], "die", "Relativ feminin: die."),
            G("Je genauer die Messung, ___ zuverlässiger das Ergebnis.", ["desto", "je", "als"], "desto", "Je … desto …"),
            G("Neue Methoden ___ entwickelt.", ["werden", "wurde", "ist werden"], "werden", "Passiv Präsens."),
            G("Obwohl die Hypothese ___ klang, musste sie getestet werden.", ["plausibel", "plausibler", "am plausiblen"], "plausibel", "Adjektiv nach klingen."),
            G("Ohne Daten zu ___, bleibt die Theorie spekulativ.", ["erheben", "erhebt", "erhoben"], "erheben", "ohne … zu + Infinitiv."),
            G("Das Experiment ___ unter strengen Bedingungen durchgeführt.", ["wurde", "wurde sein", "ist durchführen"], "wurde", "Passiv Präteritum."),
            G("Würde man mehr investieren, ___ schneller Fortschritte.", ["gäbe es", "gibt es", "gab es immer"], "gäbe es", "Irrealer Konditionalsatz."),
            G("Forscher, ___ Ergebnisse reproduzierbar sind, gewinnen Vertrauen.", ["deren", "deren den", "deren dem"], "deren", "Genitiv Relativ: deren."),
            G("Es gilt als notwendig, Quellen korrekt ___ zitieren.", ["zu", "zum", "zur"], "zu", "zu + Infinitiv."),
            G("Nachdem die Analyse ___ war, wurden die Resultate diskutiert.", ["abgeschlossen", "abschließen", "schließt ab"], "abgeschlossen", "Temporal: nachdem + Plusquamperfekt-ähnlich Partizip.")),

        CreateLesson(21, "Sport und Fairness",
            V("Was bedeutet Fairness im Sport?", ["Regeln achten und Gegner respektieren", "Um jeden Preis gewinnen", "Schiedsrichter bestechen"], "Regeln achten und Gegner respektieren", "Fair Play = ehrliches Verhalten."),
            V("Doping ist ...", ["unerlaubte Leistungssteigerung", "normales Training", "gesunde Ernährung nur"], "unerlaubte Leistungssteigerung", "Doping verstößt gegen Regeln."),
            V("Was macht ein Schiedsrichter?", ["Überwacht die Einhaltung der Regeln", "Trainiert nur die Mannschaft", "Verkauft Merchandising"], "Überwacht die Einhaltung der Regeln", "Schiedsrichter leiten Spiele."),
            V("Teamgeist heißt ...", ["gemeinsam und solidarisch handeln", "nur Einzelkämpfer sein", "Gegner beleidigen"], "gemeinsam und solidarisch handeln", "Team = Zusammenhalt."),
            V("Was ist Ausdauer?", ["Fähigkeit, lange Leistung zu erbringen", "Nur kurze Sprints", "Maximalkraft allein"], "Fähigkeit, lange Leistung zu erbringen", "Ausdauer = Stamina."),
            V("Ein Foul ist ...", ["ein Regelverstoß gegen den Gegner", "ein fairer Pass", "ein Torjubeln"], "ein Regelverstoß gegen den Gegner", "Fouls werden geahndet."),
            V("Was bedeutet: disqualifiziert werden?", ["Wegen Verstoßes vom Wettbewerb ausgeschlossen", "Den Pokal gewinnen", "Als Trainer arbeiten"], "Wegen Verstoßes vom Wettbewerb ausgeschlossen", "Disqualifikation = Ausschluss."),
            V("Amateurport treibt man oft ...", ["ohne professionelles Gehalt", "nur für Millionenverträge", "nur im Labor"], "ohne professionelles Gehalt", "Amateur = nicht hauptberuflich."),
            V("Was ist ein Marathon?", ["Ein Langstreckenlauf über ca. 42 km", "Ein kurzer Sprint", "Ein Schwimmstil nur"], "Ein Langstreckenlauf über ca. 42 km", "Marathon = Ausdauerlauf."),
            V("Respekt gegenüber Gegnern zeigt sich darin, dass man ...", ["auch nach Niederlagen anerkennend bleibt", "beleidigt und schummelt", "Regeln ignoriert"], "auch nach Niederlagen anerkennend bleibt", "Respekt gehört zum Fair Play."),
            G("Das Spiel, ___ wir gesehen haben, war spannend.", ["das", "die", "der"], "das", "Relativ Neutrum: das."),
            G("Je fairer man spielt, ___ mehr Anerkennung bekommt man.", ["desto", "je", "als"], "desto", "Je … desto …"),
            G("Der Rekord ___ gebrochen.", ["wurde", "wurde sein", "ist brechen"], "wurde", "Passiv Präteritum."),
            G("Obwohl sie verletzt ___, trainierte sie vorsichtig weiter.", ["war", "ist", "sein"], "war", "obwohl + Präteritum."),
            G("Ohne zu ___, riskiert man Verletzungen.", ["aufwärmen", "wärmt auf", "aufgewärmt"], "aufwärmen", "ohne … zu + Infinitiv."),
            G("Würden alle Regeln ___, gäbe es weniger Konflikte.", ["eingehalten", "einhalten", "hält ein"], "eingehalten", "Passiv Konjunktiv II: würden eingehalten."),
            G("Sportler, ___ fair spielen, sind Vorbilder.", ["die", "der", "das"], "die", "Relativ Plural: die."),
            G("Man sollte akzeptieren, ___ die Entscheidung des Schiris gilt.", ["dass", "ob", "als"], "dass", "dass-Satz."),
            G("Nachdem das Tor ___ worden war, jubelte das Stadion.", ["gegeben", "geben", "gibt"], "gegeben", "Passiv Plusquamperfekt: gegeben worden war."),
            G("Fairness ___ im Sport großgeschrieben.", ["wird", "wurde sein", "ist werden"], "wird", "Passiv Präsens.")),

        CreateLesson(22, "Ernährung und Trends",
            V("Was bedeutet ausgewogene Ernährung?", ["Vielfalt und passende Mengen wichtiger Nährstoffe", "Nur Fast Food", "Nur Süßigkeiten"], "Vielfalt und passende Mengen wichtiger Nährstoffe", "Ausgewogen = ausgewogen."),
            V("Vegetarisch heißt ...", ["ohne Fleisch und Fisch essen", "nur Fleisch essen", "gar nichts essen"], "ohne Fleisch und Fisch essen", "Vegetarier meiden Fleisch/Fisch."),
            V("Was sind Lebensmittelunverträglichkeiten?", ["Körper reagiert negativ auf bestimmte Speisen", "Nur Geschmacksvorlieben", "Allgemeiner Hunger"], "Körper reagiert negativ auf bestimmte Speisen", "Unverträglichkeit ≠ Geschmack."),
            V("Superfoods werden oft als ... beworben.", ["besonders nährstoffreich", "komplett wirkungslos immer", "nur dekorativ"], "besonders nährstoffreich", "Marketingbegriff für „gesunde“ Lebensmittel."),
            V("Was bedeutet: regional einkaufen?", ["Produkte aus der näheren Umgebung wählen", "Nur Importware kaufen", "Nur online bestellen müssen"], "Produkte aus der näheren Umgebung wählen", "Regional = kurze Wege."),
            V("Kalorien messen ...", ["den Energiegehalt von Lebensmitteln", "nur das Gewicht der Packung", "die Farbe des Essens"], "den Energiegehalt von Lebensmitteln", "kcal = Energie."),
            V("Was ist eine Diät im Alltagssinn oft?", ["Eine bewusste Umstellung der Ernährung", "Nur mehr Zucker", "Gar keine Flüssigkeit"], "Eine bewusste Umstellung der Ernährung", "Diät = Ernährungsplan."),
            V("Food-Trends ändern sich ...", ["je nach Mode, Medien und Wissenschaft", "nie", "nur alle hundert Jahre"], "je nach Mode, Medien und Wissenschaft", "Trends sind zeitgebunden."),
            V("Was bedeutet: haltbar machen?", ["Lebensmittel länger genießbar halten", "Sofort wegwerfen", "Nur einfrieren müssen immer"], "Lebensmittel länger genießbar halten", "Konservieren, Einmachen usw."),
            V("Nachhaltige Ernährung achtet auf ...", ["Umwelt, Saison und wenig Verschwendung", "nur den niedrigsten Preis immer", "maximale Verpackung"], "Umwelt, Saison und wenig Verschwendung", "Nachhaltig essen."),
            G("Lebensmittel, ___ regional sind, haben oft kürzere Transportwege.", ["die", "der", "das"], "die", "Relativ Plural: die."),
            G("Je weniger Zucker man ___, desto besser für die Zähne.", ["isst", "essen", "gegessen"], "isst", "Je … desto … + Präsens."),
            G("Viele Produkte ___ als gesund vermarktet.", ["werden", "wurde", "ist werden"], "werden", "Passiv Präsens."),
            G("Obwohl der Trend ___ ist, sollte man kritisch bleiben.", ["neu", "neuer", "am neuen"], "neu", "Adjektiv nach sein."),
            G("Ohne Etiketten zu ___, kennt man Inhaltsstoffe schlecht.", ["lesen", "liest", "gelesen"], "lesen", "ohne … zu + Infinitiv."),
            G("Die Empfehlung ___ von Ernährungsberatern gegeben.", ["wurde", "wurde sein", "ist geben"], "wurde", "Passiv Präteritum."),
            G("Würde man weniger Fleisch ___, sänke oft der CO₂-Fußabdruck.", ["essen", "isst", "gegessen"], "essen", "würde + Infinitiv."),
            G("Gerichte, ___ mit Saisongemüse zubereitet werden, schmecken frisch.", ["die", "der", "das"], "die", "Relativ Plural: die."),
            G("Es ist ratsam, dass man abwechslungsreich ___.", ["isst", "essen", "gegessen"], "isst", "dass-Satz Singular man: isst."),
            G("Nachdem der Trend ___ war, kamen neue Modewellen.", ["vorüber", "vorübergehen", "geht vorüber"], "vorüber", "vorüber sein = vorbei.")),

        CreateLesson(23, "Geschichte Europas",
            V("Was war die Europäische Union ursprünglich vor allem?", ["Ein Friedens- und Wirtschaftsprojekt nach Kriegen", "Ein Sportverband", "Ein Sprachkurs"], "Ein Friedens- und Wirtschaftsprojekt nach Kriegen", "EU-Idee: Frieden und Zusammenarbeit."),
            V("Die Aufklärung betonte ...", ["Vernunft, Kritik und Menschenrechte", "nur Aberglauben", "absolute Willkür"], "Vernunft, Kritik und Menschenrechte", "Aufklärung = Vernunftzeitalter."),
            V("Was bedeutet: Industrialisierung?", ["Übergang zu maschineller Massenproduktion", "Nur Landwirtschaft ausweiten", "Rückkehr zur Steinzeit"], "Übergang zu maschineller Massenproduktion", "Industrie verändert Wirtschaft und Gesellschaft."),
            V("Der Eiserne Vorhang trennte ...", ["Ost- und Westblock im Kalten Krieg", "nur Nord- und Südamerika", "nur Sprachfamilien"], "Ost- und Westblock im Kalten Krieg", "Metapher für die Teilung Europas."),
            V("Was ist ein Bündnis?", ["Ein Zusammenschluss zu gemeinsamen Zielen", "Ein Einzelstaat ohne Partner", "Nur ein Handelsgeschäft einmalig"], "Ein Zusammenschluss zu gemeinsamen Zielen", "Allianzen kooperieren."),
            V("Die Reformation veränderte ...", ["Religion und Gesellschaft in Europa", "nur die Kochkunst", "nur den Fußball"], "Religion und Gesellschaft in Europa", "Reformation = religiöser Umbruch."),
            V("Was bedeutet: Souveränität?", ["Eigenständige staatliche Entscheidungsgewalt", "Abhängigkeit von Nachbarn immer", "Nur kulturelle Feste"], "Eigenständige staatliche Entscheidungsgewalt", "Souverän = selbstbestimmt."),
            V("Der Euro ist ...", ["die gemeinsame Währung vieler EU-Staaten", "nur eine Historikerzeitschrift", "ein mittelalterliches Gesetz"], "die gemeinsame Währung vieler EU-Staaten", "Euro = Einheitswährung."),
            V("Was war die Berliner Mauer?", ["Symbol der deutschen und europäischen Teilung", "Eine Touristenattraktion von Anfang an nur", "Ein Handelsweg nach Asien"], "Symbol der deutschen und europäischen Teilung", "Mauer = Teilung 1961–1989."),
            V("Erinnerungskultur heißt ...", ["bewusst mit Geschichte und Opfern umgehen", "Vergangenheit komplett vergessen", "Nur Feiern ohne Kontext"], "bewusst mit Geschichte und Opfern umgehen", "Erinnern als gesellschaftliche Aufgabe."),
            G("Ereignisse, ___ Europa prägten, werden bis heute diskutiert.", ["die", "der", "das"], "die", "Relativ Plural: die."),
            G("Je genauer man Quellen ___, desto klarer wird das Bild.", ["prüft", "prüfen", "geprüft"], "prüft", "Je … desto …"),
            G("Viele Verträge ___ nach langen Verhandlungen unterzeichnet.", ["wurden", "wurde", "ist werden"], "wurden", "Passiv Präteritum Plural."),
            G("Obwohl der Krieg ___, blieb die Lage angespannt.", ["vorüber war", "vorüber", "vorübergehen"], "vorüber war", "obwohl + vollständiger Satz."),
            G("Ohne kritisch zu ___, wiederholt man Mythen.", ["hinterfragen", "hinterfragt", "hinterfragt hat"], "hinterfragen", "ohne … zu + Infinitiv."),
            G("Die Grenzen ___ mehrmals neu gezogen.", ["wurden", "wurde sein", "ist ziehen"], "wurden", "Passiv Präteritum."),
            G("Hätte man früher kooperiert, ___ Konflikte milder verlaufen.", ["wären", "sind", "waren"], "wären", "Irrealer Konditionalsatz Vergangenheit."),
            G("Staaten, ___ der EU beigetreten sind, übernehmen gemeinsame Regeln.", ["die", "der", "das"], "die", "Relativ Plural: die."),
            G("Es ist wichtig, dass Geschichte nicht ___ wird.", ["verfälscht", "verfälschen", "verfälscht hat"], "verfälscht", "Passiv: nicht verfälscht wird."),
            G("Nachdem die Mauer ___ war, begann eine neue Epoche.", ["gefallen", "fallen", "fällt"], "gefallen", "nachdem + Partizip/Zustand.")),

        CreateLesson(24, "Ziele und Lebenswege",
            V("Was ist ein Lebensziel?", ["Ein langfristiger persönlicher Wunsch", "Nur ein Tagesplan", "Ein Zufall ohne Richtung"], "Ein langfristiger persönlicher Wunsch", "Ziele geben Orientierung."),
            V("Motivation hilft dabei, ...", ["trotz Schwierigkeiten weiterzumachen", "sofort aufzugeben", "Ziele zu vergessen"], "trotz Schwierigkeiten weiterzumachen", "Motivation = Antrieb."),
            V("Was bedeutet: Prioritäten setzen?", ["Wichtiges vor Unwichtigem ordnen", "Alles gleichzeitig machen", "Nichts entscheiden"], "Wichtiges vor Unwichtigem ordnen", "Priorisieren = Reihenfolge."),
            V("Ein Lebenslauf dokumentiert ...", ["Ausbildung, Beruf und Stationen", "nur Hobbys ohne Daten", "nur Urlaubsfotos"], "Ausbildung, Beruf und Stationen", "CV = beruflicher Werdegang."),
            V("Was ist Work-Life-Balance?", ["Ausgleich zwischen Arbeit und Privatleben", "Nur Überstunden", "Nur Freizeit ohne Job"], "Ausgleich zwischen Arbeit und Privatleben", "Balance = Gleichgewicht."),
            V("Weiterbildung dient dazu, ...", ["Kenntnisse und Chancen zu erweitern", "alles Gelernte zu vergessen", "nur Zertifikate zu sammeln ohne Sinn"], "Kenntnisse und Chancen zu erweitern", "Lernen über die Erstausbildung hinaus."),
            V("Was bedeutet: flexibel bleiben?", ["sich an Veränderungen anpassen können", "nie Pläne ändern", "nur eine Option haben"], "sich an Veränderungen anpassen können", "Flexibilität = Anpassungsfähigkeit."),
            V("Ein Mentoring unterstützt ...", ["durch Erfahrung und Beratung", "nur durch Kritik ohne Hilfe", "durch Ignorieren"], "durch Erfahrung und Beratung", "Mentoren begleiten."),
            V("Was heißt: Verantwortung für den eigenen Weg übernehmen?", ["Entscheidungen bewusst treffen und tragen", "alles dem Zufall überlassen", "nur andere entscheiden lassen"], "Entscheidungen bewusst treffen und tragen", "Selbstverantwortung."),
            V("Perspektiven wechseln bedeutet ...", ["Situationen aus anderer Sicht sehen", "nur die eigene Meinung behalten", "Ziele löschen"], "Situationen aus anderer Sicht sehen", "Perspektivwechsel schafft Verständnis."),
            G("Ziele, ___ man ernst nimmt, brauchen konkrete Schritte.", ["die", "der", "das"], "die", "Relativ Plural: die."),
            G("Je klarer der Plan, ___ leichter fällt die Umsetzung.", ["desto", "je", "als"], "desto", "Je … desto …"),
            G("Der Lebenslauf ___ sorgfältig formuliert.", ["wurde", "wurde sein", "ist formulieren"], "wurde", "Passiv Präteritum."),
            G("Obwohl der Weg ___ war, gab sie nicht auf.", ["schwierig", "schwieriger", "am schwierigen"], "schwierig", "Adjektiv nach sein."),
            G("Ohne regelmäßig zu ___, erreicht man ambitionierte Ziele selten.", ["üben", "übt", "geübt"], "üben", "ohne … zu + Infinitiv."),
            G("Würde ich mehr Zeit ___, würde ich eine Weiterbildung machen.", ["haben", "hat", "hatte"], "haben", "Irreal: würde … haben."),
            G("Menschen, ___ ihre Prioritäten kennen, entscheiden klarer.", ["die", "der", "das"], "die", "Relativ Plural: die."),
            G("Es ist sinnvoll, dass man realistische Zwischenziele ___.", ["setzt", "setzen", "gesetzt"], "setzt", "dass + man: setzt."),
            G("Nachdem sie ihr Ziel ___ hatte, plante sie das Nächste.", ["erreicht", "erreichen", "erreicht wird"], "erreicht", "nachdem + Plusquamperfekt."),
            G("Erfolge ___ oft erst nach Rückschlägen sichtbar.", ["werden", "wurde", "ist werden"], "werden", "Passiv/werden + Adjektiv: werden sichtbar.")),
    ];

    private static QuizContentLesson CreateLesson(
        int number,
        string title,
        params (QuizCategory Category, string Prompt, string[] Options, string CorrectAnswer, string Explanation)[] questions)
    {
        var lessonId = Guid.Parse($"32121212-3212-3212-3212-{number:000000000000}");
        var baseQuestionId = number * 100 + 1;

        return new QuizContentLesson(
            new Lesson(lessonId, "Menschen", "B1.2", number, title),
            questions.Select((question, index) => new QuizQuestion(
                Guid.Parse($"25200000-0000-0000-0000-{baseQuestionId + index:000000000000}"),
                lessonId,
                question.Category,
                QuestionType.MultipleChoice,
                question.Prompt,
                question.Options,
                question.CorrectAnswer,
                question.Explanation)).ToList());
    }

    private static (QuizCategory Category, string Prompt, string[] Options, string CorrectAnswer, string Explanation) V(
        string prompt, string[] options, string correctAnswer, string explanation) =>
        (QuizCategory.Vocabulary, prompt, options, correctAnswer, explanation);

    private static (QuizCategory Category, string Prompt, string[] Options, string CorrectAnswer, string Explanation) G(
        string prompt, string[] options, string correctAnswer, string explanation) =>
        (QuizCategory.Grammar, prompt, options, correctAnswer, explanation);
}
