using DeutschQuiz.Domain;

namespace DeutschQuiz.Application;

/// <summary>
/// Independent quiz catalogue for Menschen B1.1 (Lektionen 1–12).
/// Prompts are original for DeutschQuiz and are not copied from the textbook.
/// </summary>
public static class MenschenB11QuizContentCatalog
{
    public static IReadOnlyList<QuizContentLesson> Lessons { get; } =
    [
        CreateLesson(1, "Identität und Biografie",
            V("Was gehört zur Biografie einer Person?", ["Wichtige Lebensstationen", "Nur der Tagesplan", "Nur die Lieblingsfarbe"], "Wichtige Lebensstationen", "Eine Biografie fasst Lebenswege zusammen."),
            V("Was bedeutet Herkunft?", ["Woher man kommt", "Was man isst", "Wann man schläft"], "Woher man kommt", "Herkunft beschreibt den Ursprung."),
            V("Ein Lebenslauf fasst zusammen ...", ["Ausbildung und Berufserfahrung", "Nur Hobbys ohne Datum", "Nur Wetterdaten"], "Ausbildung und Berufserfahrung", "Im Lebenslauf stehen Stationen und Qualifikationen."),
            V("Was ist eine prägende Erfahrung?", ["Etwas, das einen stark beeinflusst", "Etwas Belangloses", "Nur ein Zufallsprodukt"], "Etwas, das einen stark beeinflusst", "Prägend = einflussreich für die Person."),
            V("Staatsangehörigkeit bedeutet ...", ["Zu welchem Staat man gehört", "Welchen Beruf man hat", "Wo man einkauft"], "Zu welchem Staat man gehört", "Staatsangehörigkeit ist rechtliche Zugehörigkeit."),
            V("Was beschreibt man mit Persönlichkeit?", ["Charakterzüge einer Person", "Nur die Schuhgröße", "Nur den Wohnort"], "Charakterzüge einer Person", "Persönlichkeit = typische Eigenschaften."),
            V("Ein Wendepunkt im Leben ist ...", ["Ein Ereignis, das viel verändert", "Ein alltäglicher Einkauf", "Ein kurzer Spaziergang"], "Ein Ereignis, das viel verändert", "Wendepunkt = entscheidende Veränderung."),
            V("Was bedeutet Integration?", ["Teil einer Gesellschaft werden", "Nur alleine bleiben", "Nur umziehen ohne Kontakt"], "Teil einer Gesellschaft werden", "Integration heißt: Anschluss finden."),
            V("Erinnerungen sind ...", ["Gespeicherte Erlebnisse", "Nur zukünftige Pläne", "Nur Fahrpläne"], "Gespeicherte Erlebnisse", "Erinnerungen beziehen sich auf die Vergangenheit."),
            V("Was ist ein Vorbild?", ["Jemand, an dem man sich orientiert", "Ein Zufallsgerät", "Ein leerer Termin"], "Jemand, an dem man sich orientiert", "Vorbilder beeinflussen Werte und Ziele."),
            G("Das ist die Frau, ___ in Berlin wohnt.", ["die", "der", "das"], "die", "Relativpronomen feminin Nominativ: die."),
            G("Der Mann, ___ ich gestern getroffen habe, ist Lehrer.", ["den", "der", "dem"], "den", "Relativpronomen Akkusativ maskulin: den."),
            G("Als Kind ___ ich oft Fußball.", ["spielte", "spielen", "gespielt"], "spielte", "Präteritum von spielen: spielte."),
            G("Ich ___ in München geboren.", ["wurde", "wurde ich", "worden"], "wurde", "Passiv Geburt: wurde geboren."),
            G("Er erzählte, ___ er lange im Ausland gelebt habe.", ["dass", "ob", "weil"], "dass", "dass leitet einen Inhaltssatz ein."),
            G("Die Stadt, in ___ ich aufgewachsen bin, ist klein.", ["der", "die", "dem"], "der", "in + Relativpronomen feminin Dativ: der."),
            G("Wenn ich mehr Zeit ___, würde ich mehr lesen.", ["hätte", "habe", "haben"], "hätte", "Konjunktiv II in der Bedingung."),
            G("Meine Eltern ___ früher in Hamburg.", ["wohnten", "wohnen", "gewohnt"], "wohnten", "Präteritum von wohnen."),
            G("Das Buch, ___ auf dem Tisch liegt, gehört mir.", ["das", "der", "dem"], "das", "Relativpronomen Neutrum Nominativ: das."),
            G("Sie ___ vor zehn Jahren nach Deutschland.", ["zog", "ziehen", "gezogen"], "zog", "Präteritum von ziehen.")),

        CreateLesson(2, "Arbeit und Karriere",
            V("Was ist eine Karriere?", ["Beruflicher Aufstieg über die Zeit", "Nur ein Hobby", "Nur ein Urlaub"], "Beruflicher Aufstieg über die Zeit", "Karriere beschreibt den Berufsweg."),
            V("Was bedeutet Bewerbung?", ["Anfrage um eine Stelle", "Eine Kündigung", "Ein Freizeitplan"], "Anfrage um eine Stelle", "Mit einer Bewerbung sucht man Arbeit."),
            V("Ein Vorstellungsgespräch ist ...", ["ein Gespräch mit dem Arbeitgeber", "eine Party", "ein Kaufvertrag"], "ein Gespräch mit dem Arbeitgeber", "Dort stellt man sich vor."),
            V("Was ist Verantwortung im Beruf?", ["Aufgaben ernst nehmen und entscheiden", "Nur Pause machen", "Nur zuschauen"], "Aufgaben ernst nehmen und entscheiden", "Verantwortung heißt: zuständig sein."),
            V("Überstunden bedeuten ...", ["länger arbeiten als geplant", "früher Feierabend", "nur Teilzeit"], "länger arbeiten als geplant", "Überstunden = zusätzliche Arbeitszeit."),
            V("Was ist ein Praktikant?", ["Jemand, der zur Orientierung arbeitet", "Der Firmenchef", "Ein Kunde"], "Jemand, der zur Orientierung arbeitet", "Praktika dienen dem Lernen."),
            V("Beförderung heißt ...", ["eine höhere Position bekommen", "gekündigt werden", "umziehen"], "eine höhere Position bekommen", "Beförderung = Aufstieg."),
            V("Was beschreibt man mit Soft Skills?", ["Soziale und persönliche Fähigkeiten", "Nur Maschinenkenntnisse", "Nur Gehalt"], "Soziale und persönliche Fähigkeiten", "Soft Skills sind z. B. Teamfähigkeit."),
            V("Ein Arbeitsvertrag regelt ...", ["Rechte und Pflichten im Job", "Nur Hobbys", "Nur den Wohnort"], "Rechte und Pflichten im Job", "Der Vertrag hält Bedingungen fest."),
            V("Was bedeutet Work-Life-Balance?", ["Gleichgewicht von Arbeit und Privatleben", "Nur Mehrarbeit", "Nur Urlaub ohne Job"], "Gleichgewicht von Arbeit und Privatleben", "Balance zwischen Beruf und Freizeit."),
            G("Die Stelle ___ gestern ausgeschrieben.", ["wurde", "worden", "wird"], "wurde", "Passiv Präteritum: wurde ausgeschrieben."),
            G("Wenn ich die Stelle ___, würde ich umziehen.", ["bekäme", "bekomme", "bekommen"], "bekäme", "Konjunktiv II: bekäme."),
            G("Der Chef, ___ das Team leitet, ist neu.", ["der", "den", "dem"], "der", "Relativpronomen Nominativ maskulin."),
            G("Ich ___ gestern lange im Büro.", ["blieb", "bleiben", "geblieben"], "blieb", "Präteritum von bleiben."),
            G("Die Bewerbung muss abgeschickt ___.", ["werden", "worden", "wurde"], "werden", "Passiv Infinitiv: werden."),
            G("Er arbeitet hart, ___ er befördert werden will.", ["weil", "obwohl", "dass"], "weil", "weil gibt den Grund an."),
            G("Die Aufgaben, ___ mir gestellt wurden, sind klar.", ["die", "der", "denen"], "die", "Relativpronomen Plural Nominativ/Akkusativ: die."),
            G("Ich ___ früher in einer Bank.", ["arbeitete", "arbeiten", "gearbeitet"], "arbeitete", "Präteritum von arbeiten."),
            G("Würdest du den Job annehmen, wenn du ihn ___?", ["hättest", "hast", "haben"], "hättest", "Konjunktiv II in der Bedingung."),
            G("Die Entscheidung ___ vom Management getroffen.", ["wurde", "worden", "werden"], "wurde", "Passiv: wurde getroffen.")),

        CreateLesson(3, "Medienkompetenz",
            V("Was ist Medienkompetenz?", ["Medien kritisch nutzen und verstehen", "Nur fernsehen", "Nur Fotos speichern"], "Medien kritisch nutzen und verstehen", "Kompetenz im Umgang mit Medien."),
            V("Eine Quelle prüfen heißt ...", ["Informationen auf Glaubwürdigkeit prüfen", "Alles sofort teilen", "Nur liken"], "Informationen auf Glaubwürdigkeit prüfen", "Quellenkritik ist zentral."),
            V("Was sind Fake News?", ["Absichtlich falsche Nachrichten", "Offizielle Gesetze", "Private Termine"], "Absichtlich falsche Nachrichten", "Fake News sind irreführend."),
            V("Datenschutz schützt ...", ["persönliche Informationen", "nur Werbung", "nur Filme"], "persönliche Informationen", "Daten sollen nicht missbraucht werden."),
            V("Was bedeutet viral gehen?", ["Sich sehr schnell online verbreiten", "Nur offline bleiben", "Nur löschen"], "Sich sehr schnell online verbreiten", "Viral = hohe Reichweite."),
            V("Ein Algorithmus entscheidet oft ...", ["welche Inhalte man sieht", "das Wetter", "die Bahnverbindung allein"], "welche Inhalte man sieht", "Algorithmen filtern Feeds."),
            V("Was ist ein Influencer?", ["Jemand mit großer Online-Reichweite", "Ein Beamter ohne Netz", "Ein Buchhändler nur offline"], "Jemand mit großer Online-Reichweite", "Influencer beeinflussen Meinungen."),
            V("Clickbait bedeutet ...", ["reißerische Überschriften für Klicks", "seriöse Analyse", "kein Titel"], "reißerische Überschriften für Klicks", "Clickbait lockt Aufmerksamkeit."),
            V("Was ist ein Filterbubble?", ["Man sieht vor allem ähnliche Meinungen", "Man liest alle Seiten gleich", "Man ist offline"], "Man sieht vor allem ähnliche Meinungen", "Filterblasen engensicht."),
            V("Medienethik fragt ...", ["was man online verantworten kann", "nur nach Preisen", "nur nach Farben"], "was man online verantworten kann", "Ethik betrifft Verantwortung."),
            G("Nachrichten ___ täglich veröffentlicht.", ["werden", "worden", "wurde"], "werden", "Passiv Präsens Plural: werden."),
            G("Der Artikel, ___ ich gelesen habe, war kritisch.", ["den", "der", "dem"], "den", "Relativpronomen Akkusativ maskulin."),
            G("Wenn alle Quellen geprüft ___, wäre das Ideal.", ["würden", "werden", "worden"], "würden", "Konjunktiv II Passiv-Idee: würden."),
            G("Sie ___ gestern einen Podcast.", ["hörte", "hören", "gehört"], "hörte", "Präteritum von hören."),
            G("Ich bleibe skeptisch, ___ etwas unklar ist.", ["wenn", "dass", "ob"], "wenn", "wenn leitet eine Bedingung ein."),
            G("Die Informationen, ___ online stehen, sind nicht immer wahr.", ["die", "der", "denen"], "die", "Relativpronomen Plural."),
            G("Das Video ___ millionenfach geteilt.", ["wurde", "worden", "werden"], "wurde", "Passiv Präteritum."),
            G("Er fragte, ___ die Nachricht stimmt.", ["ob", "weil", "damit"], "ob", "ob bei offenen Fragen."),
            G("Würde ich alles glauben, ___ ich viele Fehler machen.", ["würde", "werde", "worden"], "würde", "Konjunktiv II Folge."),
            G("Die Plattform, auf ___ wir posten, speichert Daten.", ["der", "die", "dem"], "der", "auf + Dativ Relativpronomen feminin: der.")),

        CreateLesson(4, "Gesundheitssystem",
            V("Was ist eine Krankenkasse?", ["Eine Versicherung für Gesundheitskosten", "Ein Fitnessstudio", "Eine Apotheke"], "Eine Versicherung für Gesundheitskosten", "Krankenkassen finanzieren Behandlungen."),
            V("Ein Rezept braucht man oft für ...", ["bestimmte Medikamente", "Brot", "Kinokarten"], "bestimmte Medikamente", "Ärzte verschreiben Medikamente."),
            V("Was bedeutet Vorsorge?", ["Maßnahmen, um Krankheiten vorzubeugen", "Nur Notfallhilfe", "Nur Urlaub"], "Maßnahmen, um Krankheiten vorzubeugen", "Vorsorge = Prävention."),
            V("Eine Überweisung schickt dich ...", ["zu einem Facharzt", "zum Supermarkt", "zur Bank"], "zu einem Facharzt", "Hausärzte überweisen weiter."),
            V("Was ist ein Notfall?", ["Eine akute, dringende Situation", "Ein geplanter Termin", "Ein Hobby"], "Eine akute, dringende Situation", "Im Notfall braucht man sofort Hilfe."),
            V("Rehabilitation hilft nach ...", ["Krankheit oder Verletzung", "einem Einkauf", "einem Konzert"], "Krankheit oder Verletzung", "Reha unterstützt die Genesung."),
            V("Was bedeutet Wartezeit beim Arzt?", ["Zeit bis zum Termin oder Aufruf", "Nur Behandlungsdauer", "Nur Schlaf"], "Zeit bis zum Termin oder Aufruf", "Wartezeiten sind im System häufig."),
            V("Prävention umfasst z. B. ...", ["Impfungen und Check-ups", "Nur Notoperationen", "Nur Rechnungen"], "Impfungen und Check-ups", "Vorbeugen statt nur heilen."),
            V("Was ist eine Diagnose?", ["Feststellung einer Krankheit", "Ein Fahrplan", "Ein Vertrag"], "Feststellung einer Krankheit", "Die Diagnose benennt das Problem."),
            V("Gesundheitskompetenz heißt ...", ["Informationen verstehen und nutzen", "Nur Medikamente sammeln", "Nur warten"], "Informationen verstehen und nutzen", "Patienten sollen mitreden können."),
            G("Der Patient ___ gestern untersucht.", ["wurde", "worden", "werden"], "wurde", "Passiv Präteritum."),
            G("Das Medikament, ___ der Arzt verschrieben hat, hilft.", ["das", "der", "dem"], "das", "Relativpronomen Neutrum Akkusativ."),
            G("Wenn ich krank ___, würde ich zum Arzt gehen.", ["wäre", "bin", "sein"], "wäre", "Konjunktiv II: wäre."),
            G("Sie ___ lange im Wartezimmer.", ["saß", "sitzen", "gesessen"], "saß", "Präteritum von sitzen."),
            G("Ich gehe zum Arzt, ___ ich Fieber habe.", ["weil", "obwohl", "damit"], "weil", "weil nennt den Grund."),
            G("Die Impfung ___ empfohlen.", ["wird", "worden", "wurde"], "wird", "Passiv Präsens."),
            G("Der Arzt, ___ mir geholfen hat, war freundlich.", ["der", "den", "dem"], "der", "Relativpronomen Nominativ."),
            G("Er ___ die Tabletten dreimal täglich.", ["nahm", "nehmen", "genommen"], "nahm", "Präteritum von nehmen."),
            G("Würdest du anrufen, wenn die Schmerzen stärker ___?", ["würden", "werden", "worden"], "würden", "Konjunktiv II."),
            G("Die Kosten ___ von der Kasse übernommen.", ["werden", "worden", "wurde"], "werden", "Passiv Präsens Plural.")),

        CreateLesson(5, "Gesellschaft und Regeln",
            V("Was sind gesellschaftliche Normen?", ["Unausgesprochene Verhaltensregeln", "Nur Gesetze im Buch", "Nur Preise"], "Unausgesprochene Verhaltensregeln", "Normen steuern den Alltag."),
            V("Ein Gesetz ist ...", ["eine verbindliche staatliche Regel", "ein Vorschlag ohne Folge", "ein Witz"], "eine verbindliche staatliche Regel", "Gesetze sind rechtlich bindend."),
            V("Was bedeutet Verantwortung in der Gesellschaft?", ["Für andere und sich einstehen", "Nur eigene Vorteile suchen", "Nur schweigen"], "Für andere und sich einstehen", "Soziale Verantwortung."),
            V("Toleranz heißt ...", ["andere Meinungen und Lebensweisen aushalten", "alles erzwingen", "nur streiten"], "andere Meinungen und Lebensweisen aushalten", "Toleranz ermöglicht Vielfalt."),
            V("Was ist ein Bürgerrecht?", ["Ein Recht, das Bürgern zusteht", "Eine private Meinung", "Ein Kauf"], "Ein Recht, das Bürgern zusteht", "Rechte schützen Freiheit."),
            V("Pflichten sind ...", ["Dinge, die man tun muss", "Nur Wünsche", "Nur Hobbys"], "Dinge, die man tun muss", "Pflichten ergänzen Rechte."),
            V("Was bedeutet Gleichberechtigung?", ["Gleiche Rechte unabhängig vom Geschlecht", "Nur Vorteile für eine Gruppe", "Nur Zufall"], "Gleiche Rechte unabhängig vom Geschlecht", "Gleichberechtigung ist ein Grundsatz."),
            V("Sanktionen folgen oft auf ...", ["Regelverstöße", "korrektes Verhalten", "Lob"], "Regelverstöße", "Sanktionen sind Konsequenzen."),
            V("Was ist Zivilcourage?", ["Eingreifen, wenn Unrecht geschieht", "Wegschauen", "Nur diskutieren ohne Handlung"], "Eingreifen, wenn Unrecht geschieht", "Mut im Alltag für andere."),
            V("Integration in Regeln heißt auch ...", ["Gesetze und Normen kennen und achten", "Alles ignorieren", "Nur privat leben"], "Gesetze und Normen kennen und achten", "Zusammenleben braucht gemeinsame Regeln."),
            G("Die Regeln ___ klar formuliert.", ["werden", "worden", "wurde"], "werden", "Passiv Präsens."),
            G("Wer gegen das Gesetz ___, muss mit Folgen rechnen.", ["verstößt", "verstoßen", "verstieß"], "verstößt", "Präsens bei allgemeiner Regel."),
            G("Das Gesetz, ___ gestern beschlossen wurde, gilt ab sofort.", ["das", "der", "dem"], "das", "Relativpronomen Neutrum."),
            G("Wenn alle fair ___, gäbe es weniger Konflikte.", ["wären", "sind", "sein"], "wären", "Konjunktiv II."),
            G("Früher ___ strengere Regeln.", ["galten", "gelten", "gegolten"], "galten", "Präteritum von gelten."),
            G("Man darf nicht parken, ___ es verboten ist.", ["wenn", "dass", "ob"], "wenn", "wenn bei Bedingung/Zeit."),
            G("Die Menschen, ___ hier leben, respektieren Vielfalt.", ["die", "der", "denen"], "die", "Relativpronomen Plural."),
            G("Die Entscheidung ___ demokratisch getroffen.", ["wurde", "worden", "werden"], "wurde", "Passiv Präteritum."),
            G("Er handelte so, ___ er helfen wollte.", ["weil", "obwohl", "ob"], "weil", "weil gibt den Grund."),
            G("Würde man mehr zuhören, ___ weniger Missverständnisse.", ["gäbe es", "gibt es", "gegeben"], "gäbe es", "Konjunktiv II: gäbe es.")),

        CreateLesson(6, "Konsum und Nachhaltigkeit",
            V("Was bedeutet Nachhaltigkeit?", ["Ressourcen so nutzen, dass Zukunft bleibt", "Nur schnell kaufen", "Nur wegwerfen"], "Ressourcen so nutzen, dass Zukunft bleibt", "Nachhaltigkeit denkt langfristig."),
            V("Konsum beschreibt ...", ["das Kaufen und Nutzen von Gütern", "nur Produzieren", "nur Sparen ohne Kauf"], "das Kaufen und Nutzen von Gütern", "Konsum = Verbrauch."),
            V("Was ist ein ökologischer Fußabdruck?", ["Messung der Umweltbelastung", "Schuhgröße", "Preisvergleich"], "Messung der Umweltbelastung", "Er zeigt Ressourcenverbrauch."),
            V("Recycling heißt ...", ["Abfall wiederverwerten", "Alles verbrennen", "Neu kaufen ohne Grund"], "Abfall wiederverwerten", "Recycling spart Rohstoffe."),
            V("Was bedeutet fairer Handel?", ["gerechte Bedingungen für Produzenten", "Nur billigste Preise", "Nur Werbung"], "gerechte Bedingungen für Produzenten", "Fair Trade achtet auf Gerechtigkeit."),
            V("Geplante Obsoleszenz bedeutet ...", ["Produkte werden absichtlich kurzlebiger", "Produkte halten ewig", "Keine Produktion"], "Produkte werden absichtlich kurzlebiger", "Kurze Lebensdauer fördert Nachkauf."),
            V("Was ist Secondhand?", ["Gebrauchte Ware erneut verkaufen/kaufen", "Nur Neuware", "Nur Miete"], "Gebrauchte Ware erneut verkaufen/kaufen", "Secondhand verlängert Nutzung."),
            V("Ressourcen sind z. B. ...", ["Wasser, Energie, Rohstoffe", "Nur Meinungen", "Nur Apps"], "Wasser, Energie, Rohstoffe", "Ressourcen sind begrenzt."),
            V("Was bedeutet regional kaufen?", ["Produkte aus der Nähe wählen", "Nur Import", "Nur Online ohne Herkunft"], "Produkte aus der Nähe wählen", "Regional spart oft Transport."),
            V("Mülltrennung hilft ...", ["Recycling und Umwelt", "nur Chaos", "nur schnellerem Kauf"], "Recycling und Umwelt", "Getrennte Abfälle sind besser verwertbar."),
            G("Plastik ___ in vielen Produkten verwendet.", ["wird", "worden", "wurde"], "wird", "Passiv Präsens."),
            G("Wenn wir weniger ___, würden wir Ressourcen sparen.", ["kauften", "kaufen", "gekauft"], "kauften", "Konjunktiv II / irreale Bedingung."),
            G("Die Verpackung, ___ recycelt werden kann, ist besser.", ["die", "der", "dem"], "die", "Relativpronomen feminin."),
            G("Früher ___ man weniger Einwegprodukte.", ["benutzte", "benutzen", "benutzt"], "benutzte", "Präteritum."),
            G("Ich kaufe bio, ___ die Umwelt zu schützen.", ["um", "weil", "obwohl"], "um", "um ... zu + Infinitiv."),
            G("Die Flasche muss getrennt ___.", ["werden", "worden", "wurde"], "werden", "Passiv Infinitiv."),
            G("Das Produkt, für ___ ich mich entscheide, ist langlebig.", ["das", "dem", "denen"], "das", "für + Akkusativ Relativpronomen Neutrum."),
            G("Wir ___ gestern den Müll.", ["trennten", "trennen", "getrennt"], "trennten", "Präteritum von trennen."),
            G("Würdest du Secondhand kaufen, wenn es günstiger ___?", ["wäre", "ist", "sein"], "wäre", "Konjunktiv II."),
            G("Viele Rohstoffe ___ importiert.", ["werden", "worden", "wurde"], "werden", "Passiv Präsens Plural.")),

        CreateLesson(7, "Reisen und Kulturen",
            V("Was ist interkulturelle Kompetenz?", ["Mit anderen Kulturen angemessen umgehen", "Nur die eigene Sprache sprechen", "Nur Touristenfotos"], "Mit anderen Kulturen angemessen umgehen", "Kompetenz im Kulturkontakt."),
            V("Ein Klischee ist ...", ["ein vereinfachtes Bild von Gruppen", "eine genaue Studie", "ein Fahrplan"], "ein vereinfachtes Bild von Gruppen", "Klischees verkürzen Realität."),
            V("Was bedeutet Gastfreundschaft?", ["Gäste willkommen heißen und unterstützen", "Gäste ignorieren", "Nur Eintritt verkaufen"], "Gäste willkommen heißen und unterstützen", "Gastfreundschaft zeigt Offenheit."),
            V("Ein Visum erlaubt oft ...", ["den legalen Aufenthalt in einem Land", "nur den Flug", "nur Souvenirs"], "den legalen Aufenthalt in einem Land", "Visa sind Einreiseerlaubnisse."),
            V("Was ist ein Brauchtum?", ["Traditionelle Sitte oder Gewohnheit", "Ein modernes Gesetz allein", "Ein Zufall"], "Traditionelle Sitte oder Gewohnheit", "Brauchtum pflegt Tradition."),
            V("Kulturschock beschreibt ...", ["Irritation in einer fremden Kultur", "Sofortige Gewöhnung", "Nur Freude ohne Anpassung"], "Irritation in einer fremden Kultur", "Neue Normen können überfordern."),
            V("Was bedeutet Mehrsprachigkeit?", ["Mehrere Sprachen beherrschen", "Nur Dialekt", "Nur Gesten"], "Mehrere Sprachen beherrschen", "Mehrsprachigkeit erleichtert Verständigung."),
            V("Respekt vor Ritualen heißt ...", ["fremde Bräuche achten", "alles kritisieren", "nur fotografieren"], "fremde Bräuche achten", "Respekt schützt Würde."),
            V("Was ist ein Reisebericht?", ["Schilderung von Erlebnissen unterwegs", "Nur eine Rechnung", "Nur ein Ticket"], "Schilderung von Erlebnissen unterwegs", "Berichte teilen Eindrücke."),
            V("Globalisierung beeinflusst Reisen durch ...", ["mehr Vernetzung und Austausch", "weniger Flüge weltweit", "keine Kulturkontakte"], "mehr Vernetzung und Austausch", "Weltweite Verbindungen wachsen."),
            G("In vielen Ländern ___ Deutsch gesprochen.", ["wird", "worden", "wurde"], "wird", "Passiv Präsens."),
            G("Das Land, ___ ich besucht habe, war beeindruckend.", ["das", "der", "dem"], "das", "Relativpronomen Neutrum Akkusativ."),
            G("Wenn ich mehr Geld ___, würde ich länger bleiben.", ["hätte", "habe", "haben"], "hätte", "Konjunktiv II."),
            G("Wir ___ gestern durch die Altstadt.", ["gingen", "gehen", "gegangen"], "gingen", "Präteritum von gehen."),
            G("Ich lerne die Sprache, ___ ich mich verständigen kann.", ["damit", "obwohl", "ob"], "damit", "damit nennt den Zweck."),
            G("Die Stadt, in ___ wir übernachtet haben, liegt am Meer.", ["der", "die", "dem"], "der", "in + Dativ Relativpronomen feminin."),
            G("Früher ___ man länger mit dem Zug.", ["reiste", "reisen", "gereist"], "reiste", "Präteritum von reisen."),
            G("Die Tradition ___ von Generation zu Generation weitergegeben.", ["wird", "worden", "wurde"], "wird", "Passiv Präsens."),
            G("Würdest du dich anpassen, wenn die Regeln anders ___?", ["wären", "sind", "sein"], "wären", "Konjunktiv II."),
            G("Er erzählte, ___ die Reise anstrengend gewesen sei.", ["dass", "ob", "weil"], "dass", "dass leitet indirekte Rede ein.")),

        CreateLesson(8, "Bildung und Ausbildung",
            V("Was ist eine Ausbildung?", ["Berufliches Lernen in Praxis und Theorie", "Nur Freizeit", "Nur Urlaub"], "Berufliches Lernen in Praxis und Theorie", "Ausbildung qualifiziert für Berufe."),
            V("Ein duales System verbindet ...", ["Betrieb und Berufsschule", "Nur Uni und Hobby", "Nur Online-Spiele"], "Betrieb und Berufsschule", "Dual = zwei Lernorte."),
            V("Was bedeutet Abitur?", ["Hochschulreife nach der Schule", "Ein Praktikum", "Ein Ferienjob"], "Hochschulreife nach der Schule", "Mit Abitur studiert man oft."),
            V("Weiterbildung hilft ...", ["Wissen und Skills zu erweitern", "nur zu vergessen", "nur zu kündigen"], "Wissen und Skills zu erweitern", "Lebenslanges Lernen."),
            V("Was ist ein Stipendium?", ["Finanzielle Förderung für Lernen", "Eine Strafe", "Ein Stundenplan"], "Finanzielle Förderung für Lernen", "Stipendien unterstützen Studierende."),
            V("Motivation in der Bildung heißt ...", ["inneren Antrieb zum Lernen haben", "nur Anwesenheit", "nur Noten sammeln ohne Sinn"], "inneren Antrieb zum Lernen haben", "Motivation trägt Erfolg."),
            V("Was beschreibt man mit Kompetenz?", ["Fähigkeit, etwas erfolgreich zu tun", "Nur Glück", "Nur Zufall"], "Fähigkeit, etwas erfolgreich zu tun", "Kompetenzen sind anwendbar."),
            V("Ein Praktikum dient oft der ...", ["beruflichen Orientierung", "nur Unterhaltung", "nur Wohnungssuche"], "beruflichen Orientierung", "Praktika testen Berufsfelder."),
            V("Was ist Inklusion in der Schule?", ["Alle Lernenden mitnehmen", "Nur Elite fördern", "Nur trennen"], "Alle Lernenden mitnehmen", "Inklusion öffnet Teilhabe."),
            V("Prüfungsangst ist ...", ["starke Nervosität vor Tests", "Ruhe und Gelassenheit", "Desinteresse"], "starke Nervosität vor Tests", "Angst kann Leistung behindern."),
            G("Die Prüfung ___ morgen geschrieben.", ["wird", "worden", "wurde"], "wird", "Passiv Präsens Futur-nah."),
            G("Der Lehrer, ___ uns unterrichtet, ist streng, aber fair.", ["der", "den", "dem"], "der", "Relativpronomen Nominativ."),
            G("Wenn ich mehr üben ___, würde ich besser bestehen.", ["würde", "werde", "worden"], "würde", "Konjunktiv II."),
            G("Sie ___ gestern den Test.", ["bestand", "bestehen", "bestanden"], "bestand", "Präteritum von bestehen."),
            G("Ich lerne fleißig, ___ ich die Prüfung schaffe.", ["damit", "obwohl", "ob"], "damit", "damit = Zweck."),
            G("Die Aufgabe, ___ uns gestellt wurde, war schwer.", ["die", "der", "denen"], "die", "Relativpronomen feminin/Plural."),
            G("Früher ___ Schüler länger auswendig.", ["lernten", "lernen", "gelernt"], "lernten", "Präteritum."),
            G("Das Zeugnis ___ digital ausgestellt.", ["wird", "worden", "wurde"], "wird", "Passiv Präsens."),
            G("Würdest du studieren, wenn du ein Stipendium ___?", ["hättest", "hast", "haben"], "hättest", "Konjunktiv II."),
            G("Er sagte, ___ die Ausbildung anspruchsvoll sei.", ["dass", "ob", "weil"], "dass", "dass in indirekter Rede.")),

        CreateLesson(9, "Politik und Meinungen",
            V("Was ist eine Demokratie?", ["Volk entscheidet mit über Politik", "Nur eine Person regiert absolut", "Keine Wahlen"], "Volk entscheidet mit über Politik", "Demokratie basiert auf Mitbestimmung."),
            V("Eine Meinung äußern heißt ...", ["sagen, was man denkt", "schweigen müssen", "nur nicken"], "sagen, was man denkt", "Meinungsfreiheit ist zentral."),
            V("Was bedeutet Wahlbeteiligung?", ["Anteil der Menschen, die wählen", "Nur Kandidatenzahl", "Nur Plakate"], "Anteil der Menschen, die wählen", "Hohe Beteiligung stärkt Legitimität."),
            V("Ein Kompromiss ist ...", ["eine Einigung mit Zugeständnissen", "ein Sieg ohne Nachgeben", "ein Streit ohne Ende"], "eine Einigung mit Zugeständnissen", "Kompromisse ermöglichen Lösungen."),
            V("Was ist Opposition?", ["Politische Gegenkraft zur Regierung", "Die Regierung selbst", "Nur Medien"], "Politische Gegenkraft zur Regierung", "Opposition kontrolliert und kritisiert."),
            V("Lobbyismus beschreibt ...", ["Einflussnahme von Interessengruppen", "Nur private Hobbys", "Nur Sport"], "Einflussnahme von Interessengruppen", "Lobbys versuchen Politik zu prägen."),
            V("Was bedeutet Meinungsfreiheit?", ["Erlaubt, Ansichten zu äußern", "Nur eine Meinung erlaubt", "Schweigepflicht"], "Erlaubt, Ansichten zu äußern", "Grundrecht in Demokratien."),
            V("Ein Protest ist oft ...", ["öffentlicher Widerspruch gegen etwas", "stille Zustimmung", "nur Feiern"], "öffentlicher Widerspruch gegen etwas", "Protest macht Unzufriedenheit sichtbar."),
            V("Was ist ein Argument?", ["Begründung für eine Position", "Nur ein Gefühl ohne Grund", "Ein Zufall"], "Begründung für eine Position", "Argumente stützen Meinungen."),
            V("Debattieren heißt ...", ["kontrovers und begründet diskutieren", "nur schreien", "nur schweigen"], "kontrovers und begründet diskutieren", "Debatten brauchen Regeln und Gründe."),
            G("Das Gesetz ___ im Parlament verabschiedet.", ["wurde", "worden", "werden"], "wurde", "Passiv Präteritum."),
            G("Die Politikerin, ___ ich gewählt habe, hält Wort.", ["die", "der", "denen"], "die", "Relativpronomen Akkusativ feminin."),
            G("Wenn mehr Menschen wählen ___, wäre die Demokratie stärker.", ["würden", "werden", "worden"], "würden", "Konjunktiv II."),
            G("Er ___ gestern seine Meinung klar.", ["äußerte", "äußern", "geäußert"], "äußerte", "Präteritum."),
            G("Ich diskutiere mit, ___ ich betroffen bin.", ["weil", "obwohl", "ob"], "weil", "weil = Grund."),
            G("Das Thema, über ___ wir sprechen, ist komplex.", ["das", "dem", "denen"], "das", "über + Akkusativ Relativpronomen Neutrum."),
            G("Früher ___ weniger Transparenz.", ["gab es", "gibt es", "gegeben"], "gab es", "Präteritum: gab es."),
            G("Die Entscheidung ___ öffentlich erklärt.", ["wird", "worden", "wurde"], "wird", "Passiv Präsens."),
            G("Würdest du protestieren, wenn deine Rechte verletzt ___?", ["würden", "werden", "worden"], "würden", "Konjunktiv II."),
            G("Sie fragte, ___ er zustimme.", ["ob", "dass", "weil"], "ob", "ob bei Ja/Nein-Frage.")),

        CreateLesson(10, "Wissenschaft leicht",
            V("Was ist eine Hypothese?", ["Eine überprüfbare Vermutung", "Ein bewiesenes Gesetz", "Ein Zufall ohne Idee"], "Eine überprüfbare Vermutung", "Hypothesen werden getestet."),
            V("Ein Experiment dient dazu ...", ["Annahmen zu prüfen", "nur zu raten", "nur zu erzählen"], "Annahmen zu prüfen", "Experimente liefern Daten."),
            V("Was bedeutet empirisch?", ["Auf Beobachtung und Daten gestützt", "Nur spekulativ", "Nur gefühlsmäßig"], "Auf Beobachtung und Daten gestützt", "Empirie braucht Evidenz."),
            V("Eine Theorie erklärt ...", ["Zusammenhänge systematisch", "nur einzelne Fakten ohne Muster", "nur Meinungen"], "Zusammenhänge systematisch", "Theorien ordnen Wissen."),
            V("Was ist ein Labor?", ["Ort für wissenschaftliche Versuche", "Nur ein Büro", "Nur eine Bibliothek"], "Ort für wissenschaftliche Versuche", "Im Labor wird experimentiert."),
            V("Peer-Review bedeutet ...", ["Fachleute prüfen Veröffentlichungen", "Jeder postet ungeprüft", "Nur Werbung"], "Fachleute prüfen Veröffentlichungen", "Qualitätssicherung in der Wissenschaft."),
            V("Was beschreibt man mit Methode?", ["Geplantes Vorgehen beim Forschen", "Nur das Ergebnis", "Nur den Titel"], "Geplantes Vorgehen beim Forschen", "Methoden machen Forschung nachvollziehbar."),
            V("Ein Ergebnis ist ...", ["was die Untersuchung zeigt", "nur die Hypothese", "nur die Frage"], "was die Untersuchung zeigt", "Ergebnisse folgen aus Daten."),
            V("Was bedeutet objektiv?", ["Möglichst unabhängig von Vorurteilen", "Nur subjektiv", "Nur emotional"], "Möglichst unabhängig von Vorurteilen", "Objektivität ist ein Ideal."),
            V("Innovation heißt ...", ["neue Lösungen entwickeln", "nur Altes wiederholen", "nur kopieren"], "neue Lösungen entwickeln", "Innovation treibt Fortschritt."),
            G("Das Experiment ___ sorgfältig durchgeführt.", ["wurde", "worden", "werden"], "wurde", "Passiv Präteritum."),
            G("Die Studie, ___ veröffentlicht wurde, ist bekannt.", ["die", "der", "dem"], "die", "Relativpronomen feminin."),
            G("Wenn die Daten klarer ___, wäre die Deutung leichter.", ["wären", "sind", "sein"], "wären", "Konjunktiv II."),
            G("Die Forscher ___ gestern die Ergebnisse vor.", ["stellten", "stellen", "gestellt"], "stellten", "Präteritum: vorstellen."),
            G("Wir wiederholen den Test, ___ Fehler auszuschließen.", ["um", "weil", "obwohl"], "um", "um ... zu."),
            G("Die Hypothese, von ___ wir ausgehen, ist neu.", ["der", "die", "dem"], "der", "von + Dativ Relativpronomen feminin."),
            G("Früher ___ man ohne Computer.", ["forschte", "forschen", "geforscht"], "forschte", "Präteritum."),
            G("Die Proben ___ im Labor analysiert.", ["werden", "worden", "wurde"], "werden", "Passiv Präsens Plural."),
            G("Würde die Theorie stimmen, ___ wir neue Fragen stellen.", ["müssten", "müssen", "gemusst"], "müssten", "Konjunktiv II von müssen."),
            G("Er erklärte, ___ die Messung genau sei.", ["dass", "ob", "weil"], "dass", "dass in Inhaltssatz.")),

        CreateLesson(11, "Beziehungen und Konflikte",
            V("Was ist ein Konflikt?", ["Ein Gegensatz von Interessen oder Meinungen", "Immer Frieden", "Nur Freundschaft"], "Ein Gegensatz von Interessen oder Meinungen", "Konflikte entstehen bei Spannungen."),
            V("Empathie bedeutet ...", ["Gefühle anderer nachvollziehen", "Nur die eigene Sicht", "Gleichgültigkeit"], "Gefühle anderer nachvollziehen", "Empathie hilft Beziehungen."),
            V("Was ist eine Grenze in Beziehungen?", ["Was man akzeptiert und was nicht", "Nur geografische Linie", "Nur ein Termin"], "Was man akzeptiert und was nicht", "Grenzen schützen Bedürfnisse."),
            V("Kompromissbereitschaft heißt ...", ["bereit sein, nachzugeben und zu lösen", "nur gewinnen wollen", "nur schweigen"], "bereit sein, nachzugeben und zu lösen", "Kompromisse brauchen Flexibilität."),
            V("Was bedeutet Missverständnis?", ["Falsches Verstehen einer Aussage", "Perfekte Klarheit", "Nur Zustimmung"], "Falsches Verstehen einer Aussage", "Missverständnisse erzeugen Konflikte."),
            V("Vertrauen entsteht durch ...", ["Zuverlässigkeit und Offenheit", "nur Geheimnisse", "nur Druck"], "Zuverlässigkeit und Offenheit", "Vertrauen braucht Zeit."),
            V("Was ist Eskalation?", ["Verschärfung eines Konflikts", "Sofortige Lösung", "Ruhe"], "Verschärfung eines Konflikts", "Eskalation macht Konflikte größer."),
            V("Mediation hilft ...", ["bei der Vermittlung zwischen Parteien", "nur bei Siegen", "nur bei Ignorieren"], "bei der Vermittlung zwischen Parteien", "Mediatoren sind neutral."),
            V("Was bedeutet Kritikfähigkeit?", ["Kritik annehmen und prüfen können", "Jede Kritik abwehren", "Nur kritisieren"], "Kritik annehmen und prüfen können", "Kritikfähigkeit stärkt Lernen."),
            V("Beziehungspflege meint ...", ["bewusst Zeit und Aufmerksamkeit geben", "nur Kontakt meiden", "nur Konflikte suchen"], "bewusst Zeit und Aufmerksamkeit geben", "Beziehungen brauchen Pflege."),
            G("Der Streit ___ gestern beigelegt.", ["wurde", "worden", "werden"], "wurde", "Passiv Präteritum."),
            G("Die Freundin, ___ mir zugehört hat, half mir.", ["die", "der", "denen"], "die", "Relativpronomen Nominativ feminin."),
            G("Wenn wir ehrlich ___, würden wir uns besser verstehen.", ["wären", "sind", "sein"], "wären", "Konjunktiv II."),
            G("Sie ___ lange über das Problem.", ["sprachen", "sprechen", "gesprochen"], "sprachen", "Präteritum von sprechen."),
            G("Ich entschuldige mich, ___ ich verletzt habe.", ["weil ich dich", "obwohl ich dich", "ob ich dich"], "weil ich dich", "weil + Grund."),
            G("Das Thema, über ___ wir streiten, ist heikel.", ["das", "dem", "denen"], "das", "über + Akkusativ."),
            G("Früher ___ wir öfter.", ["stritten", "streiten", "gestritten"], "stritten", "Präteritum von streiten."),
            G("Eine Lösung ___ gemeinsam gesucht.", ["wird", "worden", "wurde"], "wird", "Passiv Präsens."),
            G("Würdest du dich entschuldigen, wenn du Unrecht ___?", ["hättest", "hast", "haben"], "hättest", "Konjunktiv II."),
            G("Er fragte, ___ sie noch wütend sei.", ["ob", "dass", "weil"], "ob", "ob bei offener Frage.")),

        CreateLesson(12, "Zukunft der Arbeit",
            V("Was bedeutet Digitalisierung der Arbeit?", ["Prozesse und Jobs werden digitaler", "Nur Papierarbeit steigt", "Keine Technik"], "Prozesse und Jobs werden digitaler", "Digitalisierung verändert Berufe."),
            V("Homeoffice heißt ...", ["von zu Hause aus arbeiten", "nur im Büro bleiben", "nur reisen"], "von zu Hause aus arbeiten", "Remote-Arbeit ist verbreitet."),
            V("Was ist Automatisierung?", ["Maschinen übernehmen Aufgaben", "Nur Menschen arbeiten manuell", "Nur Pause"], "Maschinen übernehmen Aufgaben", "Automatisierung ersetzt Routinen."),
            V("Lebenslanges Lernen bedeutet ...", ["ständig neue Skills erwerben", "nur einmal lernen", "nie weiterbilden"], "ständig neue Skills erwerben", "Wandel verlangt Lernen."),
            V("Was beschreibt Gig-Economy?", ["Kurzfristige, flexible Aufträge", "Nur Festanstellung ewig", "Nur Beamtenstatus"], "Kurzfristige, flexible Aufträge", "Plattformarbeit ist typisch."),
            V("Künstliche Intelligenz kann ...", ["Aufgaben unterstützen oder ersetzen", "nur Sport machen", "nur kochen ohne Daten"], "Aufgaben unterstützen oder ersetzen", "KI verändert Tätigkeiten."),
            V("Was ist ein Zukunftsberuf?", ["Ein Beruf mit wachsender Nachfrage", "Ein aussterbender Job", "Nur ein Hobby"], "Ein Beruf mit wachsender Nachfrage", "Nachfrage prägt Chancen."),
            V("Workation verbindet ...", ["Arbeit und Reisen", "nur Urlaub ohne Job", "nur Bürozwang"], "Arbeit und Reisen", "Arbeiten von unterwegs."),
            V("Was bedeutet Upskilling?", ["Bestehende Fähigkeiten erweitern", "Nur kündigen", "Nur abbauen"], "Bestehende Fähigkeiten erweitern", "Upskilling hält fit."),
            V("Die Zukunft der Arbeit braucht oft ...", ["Flexibilität und digitale Kompetenz", "nur starre Routinen", "keine Weiterbildung"], "Flexibilität und digitale Kompetenz", "Anpassung ist zentral."),
            G("Viele Aufgaben ___ in Zukunft automatisiert.", ["werden", "worden", "wurde"], "werden", "Passiv Futur-nah / Präsens."),
            G("Der Job, ___ ich mir wünsche, ist hybrid.", ["den", "der", "dem"], "den", "Relativpronomen Akkusativ maskulin."),
            G("Wenn KI alles ___, bräuchten wir neue Berufe.", ["übernähme", "übernimmt", "übernommen"], "übernähme", "Konjunktiv II."),
            G("Früher ___ man fast nur vor Ort.", ["arbeitete", "arbeiten", "gearbeitet"], "arbeitete", "Präteritum."),
            G("Ich bilde mich weiter, ___ ich konkurrenzfähig bleibe.", ["damit", "obwohl", "ob"], "damit", "damit = Zweck."),
            G("Die Softwares, mit ___ wir arbeiten, ändern sich schnell.", ["denen", "die", "der"], "denen", "mit + Dativ Relativpronomen Plural."),
            G("Homeoffice ___ von vielen Firmen erlaubt.", ["wird", "worden", "wurde"], "wird", "Passiv Präsens."),
            G("Sie ___ gestern remote.", ["arbeiteten", "arbeiten", "gearbeitet"], "arbeiteten", "Präteritum Plural."),
            G("Würdest du umschulen, wenn dein Beruf verschwinden ___?", ["würde", "wird", "worden"], "würde", "Konjunktiv II."),
            G("Experten sagen, ___ Flexibilität wichtiger wird.", ["dass", "ob", "weil"], "dass", "dass leitet Inhalt ein.")),
    ];

    private static QuizContentLesson CreateLesson(
        int number,
        string title,
        params (QuizCategory Category, string Prompt, string[] Options, string CorrectAnswer, string Explanation)[] questions)
    {
        var lessonId = Guid.Parse($"31111111-3111-3111-3111-{number:000000000000}");
        var baseQuestionId = number * 100 + 1;

        return new QuizContentLesson(
            new Lesson(lessonId, "Menschen", "B1.1", number, title),
            questions.Select((question, index) => new QuizQuestion(
                Guid.Parse($"25100000-0000-0000-0000-{baseQuestionId + index:000000000000}"),
                lessonId,
                question.Category,
                QuestionType.MultipleChoice,
                question.Prompt,
                question.Options,
                question.CorrectAnswer,
                question.Explanation)).ToList());
    }

    private static (QuizCategory Category, string Prompt, string[] Options, string CorrectAnswer, string Explanation) V(
        string prompt, string[] options, string correctAnswer, string explanation) =>
        (QuizCategory.Vocabulary, prompt, options, correctAnswer, explanation);

    private static (QuizCategory Category, string Prompt, string[] Options, string CorrectAnswer, string Explanation) G(
        string prompt, string[] options, string correctAnswer, string explanation) =>
        (QuizCategory.Grammar, prompt, options, correctAnswer, explanation);
}
