using DeutschQuiz.Domain;

namespace DeutschQuiz.Application;

/// <summary>
/// Independent quiz catalogue for Menschen A1.2 (Lektionen 13–24).
/// Prompts are original for DeutschQuiz and are not copied from the textbook.
/// </summary>
public static class MenschenA12QuizContentCatalog
{
    public static IReadOnlyList<QuizContentLesson> Lessons { get; } =
    [
        CreateLesson(13, "Wir suchen das Hotel Maritim",
            V("Wo findest du oft viele Geschäfte?", ["In der Stadtmitte", "Im Kühlschrank", "Im Pass"], "In der Stadtmitte", "Die Stadtmitte ist oft ein Einkaufszentrum."),
            V("Was suchst du, wenn du übernachten willst?", ["Ein Hotel", "Einen Stift", "Eine Jacke"], "Ein Hotel", "Im Hotel kann man übernachten."),
            V("Was steht oft neben dem Bahnhof?", ["Ein Busbahnhof", "Ein Kissen", "Ein Hemd"], "Ein Busbahnhof", "Bus und Bahn sind oft nah beieinander."),
            V("Wohin gehst du bei Rot?", ["Du bleibst stehen.", "Du rennst.", "Du schwimmst."], "Du bleibst stehen.", "Bei Rot bleibt man an der Ampel stehen."),
            V("Was bedeutet: geradeaus?", ["Weiter in dieselbe Richtung", "Nach links", "Nach oben"], "Weiter in dieselbe Richtung", "Geradeaus heißt: nicht links oder rechts."),
            V("Was ist eine Ampel?", ["Ein Signal für den Verkehr", "Ein Getränk", "Ein Möbelstück"], "Ein Signal für den Verkehr", "Die Ampel zeigt Rot, Gelb und Grün."),
            V("Wo ist das Café? – ___ dem Park.", ["Neben", "Durch", "Ohne"], "Neben", "Neben beschreibt eine Position."),
            V("Wie bittest du höflich um den Weg?", ["Entschuldigung, wo ist ...?", "Gib mir den Weg!", "Komm her!"], "Entschuldigung, wo ist ...?", "Entschuldigung ist höflich."),
            V("Was siehst du oft in der Stadt?", ["Straßen und Häuser", "Berge und Zelte", "Wellen und Schiffe"], "Straßen und Häuser", "Eine Stadt hat Straßen und Häuser."),
            V("Der Dom ist oft ein ...", ["bekanntes Gebäude", "Frühstück", "Fahrrad"], "bekanntes Gebäude", "Ein Dom ist ein großes Kirchengebäude."),
            G("Das Hotel ist ___ dem Bahnhof.", ["neben", "durch", "ohne"], "neben", "Neben + Dativ beschreibt den Ort."),
            G("Das Hotel liegt ___ der Brücke.", ["unter", "ohne", "gegen"], "unter", "Unter der Brücke = Position mit Dativ."),
            G("___ dem Restaurant biegen Sie rechts ab.", ["Vor", "Mit", "Für"], "Vor", "Vor dem Restaurant = Position."),
            G("Die Ampel ist ___ der Kreuzung.", ["an", "ohne", "gegen"], "an", "An der Kreuzung steht oft eine Ampel."),
            G("Das Café liegt ___ dem Park und dem Museum.", ["zwischen", "durch", "ohne"], "zwischen", "Zwischen A und B."),
            G("Gehen Sie ___ dem Bahnhof vorbei.", ["an", "gegen", "für"], "an", "An ... vorbei ist eine Wegbeschreibung."),
            G("Das Hotel ist ___ Zentrum.", ["im", "am", "zum"], "im", "Im Zentrum = in dem Zentrum."),
            G("Fahren Sie ___ der Ampel nach links.", ["an", "aus", "ohne"], "an", "An der Ampel nach links."),
            G("Wo ist der Dom? – Er ist ___ der Stadtmitte.", ["in", "mit", "für"], "in", "In der Stadtmitte."),
            G("Können Sie mir bitte ___?", ["helfen", "Hilfe", "hilft"], "helfen", "Können Sie mir helfen?")),

        CreateLesson(14, "Wie findest du Ottos Haus?",
            V("Was gehört zur Wohnung?", ["Wohnzimmer", "Bahnhof", "Pass"], "Wohnzimmer", "Das Wohnzimmer ist ein Zimmer der Wohnung."),
            V("Wie findest du die Küche? – ___!", ["Schön", "Bahnhof", "Montag"], "Schön", "Schön ist eine Meinung."),
            V("Was steht oft im Wohnzimmer?", ["Ein Sofa", "Ein Zug", "Ein Pass"], "Ein Sofa", "Im Wohnzimmer steht oft ein Sofa."),
            V("Die Wohnung ist im ...", ["ersten Stock", "ersten Tee", "ersten Schuh"], "ersten Stock", "Stock = Etage."),
            V("Was brauchst du zum Kochen?", ["Eine Küche", "Einen Bahnhof", "Einen Mantel"], "Eine Küche", "In der Küche kocht man."),
            V("Wie ist das Haus? – Es ist ...", ["groß und hell", "hungrig", "schnell"], "groß und hell", "So beschreibt man ein Haus."),
            V("Wo schläft man?", ["Im Schlafzimmer", "Im Kühlschrank", "Im Pass"], "Im Schlafzimmer", "Man schläft im Schlafzimmer."),
            V("Was findest du hässlich?", ["Etwas Unschönes", "Etwas Leckeres", "Etwas Schnelles"], "Etwas Unschönes", "Hässlich = nicht schön."),
            V("Der Balkon ist ...", ["draußen an der Wohnung", "im Kühlschrank", "im Pass"], "draußen an der Wohnung", "Der Balkon liegt außen."),
            V("Wie findest du die Farbe? – ___!", ["Nett", "Bahnhof", "Zug"], "Nett", "Nett ist eine Bewertung."),
            G("Wie ___ du die Wohnung?", ["findest", "finden", "findet"], "findest", "Bei du: findest."),
            G("Das Haus ___ sehr modern.", ["ist", "sind", "bist"], "ist", "Das Haus ist Singular."),
            G("Die Küche ___ groß.", ["ist", "sind", "bist"], "ist", "Die Küche ist Singular."),
            G("Ich finde das Sofa ___.", ["bequem", "bequemt", "bequemen"], "bequem", "Adjektiv nach finden."),
            G("Die Zimmer ___ hell.", ["sind", "ist", "bist"], "sind", "Die Zimmer = Plural."),
            G("Otto ___ im zweiten Stock.", ["wohnt", "wohnen", "wohnst"], "wohnt", "Bei er: wohnt."),
            G("___ findest du den Balkon?", ["Wie", "Woher", "Wann"], "Wie", "Wie fragt nach der Meinung."),
            G("Das Bad ___ neben dem Schlafzimmer.", ["liegt", "liegen", "liegst"], "liegt", "Bei das Bad: liegt."),
            G("Wir ___ die Wohnung schön.", ["finden", "findet", "findest"], "finden", "Bei wir: finden."),
            G("Es gibt ___ Balkon.", ["einen", "eine", "ein"], "einen", "Balkon ist maskulin: einen.")),

        CreateLesson(15, "In Giesing wohnt das Leben",
            V("Was ist ein Stadtteil?", ["Ein Teil der Stadt", "Ein Teil vom Essen", "Ein Teil vom Auto"], "Ein Teil der Stadt", "Stadtteil = Viertel."),
            V("Was findest du im Viertel oft?", ["Läden und Cafés", "Flugzeuge", "Berge"], "Läden und Cafés", "Im Viertel gibt es Läden."),
            V("Wer wohnt in der Nachbarschaft?", ["Die Nachbarn", "Die Züge", "Die Ampeln"], "Die Nachbarn", "Nachbarn wohnen in der Nähe."),
            V("Was macht man auf dem Markt?", ["Einkaufen", "Fliegen", "Schlafen im Zug"], "Einkaufen", "Auf dem Markt kauft man ein."),
            V("Ein Park ist gut zum ...", ["Spazierengehen", "Kochen im Pass", "Parken im Bett"], "Spazierengehen", "Im Park geht man spazieren."),
            V("Was ist laut?", ["Viel Lärm", "Viel Ruhe", "Viel Schlaf"], "Viel Lärm", "Laut = viel Geräusch."),
            V("Die Straßenbahn fährt ...", ["durch die Stadt", "durch den Kühlschrank", "durch den Pass"], "durch die Stadt", "Die Straßenbahn ist öffentlicher Verkehr."),
            V("Was brauchst du für den Alltag im Viertel?", ["Geschäfte in der Nähe", "Einen Flughafen im Zimmer", "Ein Schiff im Bad"], "Geschäfte in der Nähe", "Alltag braucht Läden nah."),
            V("Kinder spielen oft auf dem ...", ["Spielplatz", "Kühlschrank", "Pass"], "Spielplatz", "Auf dem Spielplatz spielen Kinder."),
            V("Das Leben im Viertel kann ... sein.", ["lebendig", "geschlossen wie ein Pass", "nur Zug"], "lebendig", "Lebendig = viel Aktivität."),
            G("In unserem Viertel ___ viele Cafés.", ["gibt es", "ist es", "bist du"], "gibt es", "Es gibt = vorhanden sein."),
            G("Die Nachbarn ___ sehr nett.", ["sind", "ist", "bist"], "sind", "Die Nachbarn = Plural."),
            G("Ich ___ gern auf dem Markt.", ["kaufe", "kaufst", "kauft"], "kaufe", "Bei ich: kaufe."),
            G("Der Park ___ neben der Schule.", ["liegt", "liegen", "liegst"], "liegt", "Bei der Park: liegt."),
            G("Wir ___ hier seit zwei Jahren.", ["wohnen", "wohnt", "wohnst"], "wohnen", "Bei wir: wohnen."),
            G("___ du den Stadtteil?", ["Kennst", "Kennen", "Kennt"], "Kennst", "Bei du: kennst."),
            G("Die Straßenbahn ___ alle zehn Minuten.", ["kommt", "kommen", "kommst"], "kommt", "Bei die Straßenbahn: kommt."),
            G("Hier ___ es nicht so laut.", ["ist", "sind", "bist"], "ist", "Es ist ..."),
            G("Die Kinder ___ auf dem Spielplatz.", ["spielen", "spielt", "spielst"], "spielen", "Bei die Kinder: spielen."),
            G("Mein Freund ___ in diesem Viertel.", ["lebt", "leben", "lebst"], "lebt", "Bei er: lebt.")),

        CreateLesson(16, "Wir haben hier ein Problem",
            V("Was ist ein Problem?", ["Etwas Schwieriges", "Etwas Leckeres", "Etwas Buntes"], "Etwas Schwieriges", "Ein Problem ist schwierig."),
            V("Was machst du bei einem Problem?", ["Um Hilfe bitten", "Sofort schlafen", "Nur lachen ohne Grund"], "Um Hilfe bitten", "Hilfe suchen ist sinnvoll."),
            V("Das Internet funktioniert nicht. Das ist ein ...", ["technisches Problem", "Frühstück", "Fahrrad"], "technisches Problem", "Technik kann Probleme machen."),
            V("Wer kann dir helfen?", ["Ein Kollege oder Nachbar", "Ein Kühlschrank", "Ein Pass allein"], "Ein Kollege oder Nachbar", "Personen können helfen."),
            V("Was sagst du höflich?", ["Können Sie mir bitte helfen?", "Hilf jetzt!", "Weg da!"], "Können Sie mir bitte helfen?", "Bitte und Sie sind höflich."),
            V("Der Aufzug ist kaputt. Was passt?", ["Wir nehmen die Treppe.", "Wir essen den Aufzug.", "Wir schlafen im Pass."], "Wir nehmen die Treppe.", "Alternative bei kaputtem Aufzug."),
            V("Was bedeutet kaputt?", ["Nicht in Ordnung", "Sehr lecker", "Sehr neu"], "Nicht in Ordnung", "Kaputt = defekt."),
            V("Du hast den Schlüssel verloren. Was brauchst du?", ["Einen Ersatzschlüssel", "Einen Zug", "Einen Dom"], "Einen Ersatzschlüssel", "Ohne Schlüssel brauchst du Ersatz."),
            V("Was ist eine Lösung?", ["Ein Weg aus dem Problem", "Ein Getränk", "Ein Schuh"], "Ein Weg aus dem Problem", "Lösung = Antwort auf das Problem."),
            V("Das Licht geht nicht. Vielleicht ist die ... kaputt.", ["Lampe", "Suppe", "Jacke"], "Lampe", "Licht kommt oft von der Lampe."),
            G("Wir ___ ein Problem.", ["haben", "hat", "hast"], "haben", "Bei wir: haben."),
            G("Können Sie mir bitte ___?", ["helfen", "Hilfe", "hilft"], "helfen", "Helfen ist der Infinitiv nach können."),
            G("Der Aufzug ___ nicht.", ["funktioniert", "funktionieren", "funktionierst"], "funktioniert", "Bei der Aufzug: funktioniert."),
            G("Ich ___ den Schlüssel verloren.", ["habe", "hast", "hat"], "habe", "Bei ich: habe ... verloren."),
            G("Was ___ wir jetzt machen?", ["können", "kann", "kannst"], "können", "Bei wir: können."),
            G("Das ist ___ Problem.", ["kein", "keine", "keinen"], "kein", "Problem ist Neutrum: kein."),
            G("___ du mir helfen?", ["Kannst", "Können", "Kann"], "Kannst", "Bei du: kannst."),
            G("Die Tür ___ nicht auf.", ["geht", "gehen", "gehst"], "geht", "Die Tür geht (nicht) auf."),
            G("Wir ___ die Treppe.", ["nehmen", "nimmt", "nimmst"], "nehmen", "Bei wir: nehmen."),
            G("Das Licht ___ nicht.", ["geht", "gehen", "gehst"], "geht", "Das Licht geht (nicht).")),

        CreateLesson(17, "Wer will Popstar werden?",
            V("Was ist ein Beruf?", ["Eine Arbeit", "Ein Getränk", "Ein Möbelstück"], "Eine Arbeit", "Beruf = Job."),
            V("Wer will Sänger werden?", ["Jemand mit Musik-Wunsch", "Ein Kühlschrank", "Ein Pass"], "Jemand mit Musik-Wunsch", "Sänger ist ein Musikberuf."),
            V("Was braucht man oft für einen Traumberuf?", ["Übung und Motivation", "Nur einen Pass", "Nur Tee"], "Übung und Motivation", "Träume brauchen Arbeit."),
            V("Ein Popstar steht oft auf der ...", ["Bühne", "Küche", "Ampel"], "Bühne", "Auf der Bühne tritt man auf."),
            V("Was bedeutet Talent?", ["Besondere Fähigkeit", "Ein Bahnhof", "Ein Schuh"], "Besondere Fähigkeit", "Talent = Begabung."),
            V("Wer spielt Gitarre?", ["Ein Musiker", "Ein Koch nur mit Löffel", "Ein Zug"], "Ein Musiker", "Gitarre ist ein Instrument."),
            V("Was willst du später werden?", ["Einen Beruf nennen", "Einen Dom essen", "Einen Pass trinken"], "Einen Beruf nennen", "Die Frage fragt nach dem Berufswunsch."),
            V("Ein Fan findet den Star ...", ["toll", "kaputt wie ein Aufzug", "nur grau"], "toll", "Fans finden Stars oft toll."),
            V("Was ist ein Traumjob?", ["Ein Wunschberuf", "Ein Frühstück", "Ein Stockwerk"], "Ein Wunschberuf", "Traumjob = idealer Beruf."),
            V("Auf der Bühne braucht man oft ...", ["Mut", "Nur Schlaf", "Nur Schnee"], "Mut", "Auftritt braucht Mut."),
            G("Ich ___ Popstar werden.", ["will", "willst", "wollen"], "will", "Bei ich: will."),
            G("___ du Musiker werden?", ["Willst", "Will", "Wollen"], "Willst", "Bei du: willst."),
            G("Er ___ Sänger werden.", ["will", "willst", "wollen"], "will", "Bei er: will."),
            G("Wir ___ später Lehrer werden.", ["wollen", "will", "willst"], "wollen", "Bei wir: wollen."),
            G("Was ___ sie werden?", ["will", "willst", "wollen"], "will", "Bei sie (Singular): will."),
            G("Ihr ___ berühmt werden.", ["wollt", "will", "willst"], "wollt", "Bei ihr: wollt."),
            G("Sie ___ alle Künstler werden.", ["wollen", "will", "willst"], "wollen", "Bei sie (Plural): wollen."),
            G("Mein Bruder ___ Schauspieler werden.", ["will", "wollen", "willst"], "will", "Bei er: will."),
            G("___ ihr auf der Bühne singen?", ["Wollt", "Will", "Willst"], "Wollt", "Bei ihr: wollt."),
            G("Ich ___ nicht berühmt sein.", ["will", "willst", "wollen"], "will", "Negation: will nicht.")),

        CreateLesson(18, "Geben Sie ihm doch diesen Tee",
            V("Wem gibst du den Tee? – ___ Freund.", ["Meinem", "Mein", "Meine"], "Meinem", "Dativ maskulin: meinem."),
            V("Was gibst du oft zu trinken?", ["Tee oder Wasser", "Einen Bahnhof", "Einen Dom"], "Tee oder Wasser", "Getränke zum Trinken."),
            V("Das Geschenk ist für ...", ["ihn / sie", "den Pass allein", "den Zug"], "ihn / sie", "Geschenke sind für Personen."),
            V("Wem hilft der Arzt?", ["Dem Patienten", "Dem Sofa", "Dem Pass"], "Dem Patienten", "Helfen + Dativ."),
            V("Gib ___ bitte das Buch.", ["mir", "ich", "mich"], "mir", "Mir ist Dativ."),
            V("Was passt? – Ich schreibe ___ eine E-Mail.", ["ihm", "er", "ihn"], "ihm", "Schreiben + Dativ der Person."),
            V("Der Kellner bringt ___ die Rechnung.", ["uns", "wir", "unsers"], "uns", "Uns ist Dativ Plural."),
            V("Kannst du ___ das Salz geben?", ["mir", "ich", "mich"], "mir", "Geben + Dativ."),
            V("Sie schenkt ___ Blumen.", ["ihr", "sie (Nom.)", "ihrens"], "ihr", "Ihr = Dativ feminin."),
            V("Erzähle ___ die Geschichte!", ["mir", "ich", "mich"], "mir", "Erzählen + Dativ."),
            G("Ich gebe ___ den Tee.", ["ihm", "er", "ihn"], "ihm", "Geben + Dativ: ihm."),
            G("Gib ___ bitte das Glas.", ["ihr", "sie", "ihren"], "ihr", "Gib ihr = Dativ feminin."),
            G("Wir helfen ___.", ["ihm", "er", "ihn"], "ihm", "Helfen + Dativ."),
            G("Kannst du ___ das Buch bringen?", ["mir", "ich", "mich"], "mir", "Mir = Dativ."),
            G("Sie schreibt ___ eine Karte.", ["uns", "wir", "unser"], "uns", "Uns = Dativ."),
            G("Er schenkt ___ einen Ball.", ["dem Kind", "das Kind", "den Kind"], "dem Kind", "Dativ Neutrum: dem."),
            G("Ich zeige ___ die Stadt.", ["dir", "du", "dich"], "dir", "Dir = Dativ."),
            G("Gebt ___ bitte Wasser!", ["mir", "ich", "mich"], "mir", "Imperativ + mir."),
            G("Der Lehrer erklärt ___ die Regel.", ["den Schülern", "die Schüler", "der Schüler"], "den Schülern", "Dativ Plural: den."),
            G("Bitte gib ___ den Stift.", ["ihm", "er", "ihn"], "ihm", "Ihm = Dativ maskulin.")),

        CreateLesson(19, "Der hatte doch keinen Bauch",
            V("Was ist ein Körperteil?", ["Der Arm", "Der Bahnhof", "Der Tee"], "Der Arm", "Arm ist ein Körperteil."),
            V("Wo ist der Bauch?", ["Am Körper in der Mitte", "Im Pass", "Am Bahnhof"], "Am Körper in der Mitte", "Bauch = Körperteil."),
            V("Was machst du mit den Augen?", ["Sehen", "Hören", "Riechen nur mit dem Fuß"], "Sehen", "Augen zum Sehen."),
            V("Die Haare sind auf dem ...", ["Kopf", "Fuß allein", "Pass"], "Kopf", "Haare wachsen auf dem Kopf."),
            V("Was bedeutet schlank?", ["Nicht dick", "Sehr laut", "Sehr kaputt"], "Nicht dick", "Schlank beschreibt den Körper."),
            V("Er hat starke ...", ["Arme", "Bahnhöfe", "Pässe"], "Arme", "Arme sind Körperteile."),
            V("Womit hörst du?", ["Mit den Ohren", "Mit den Schuhen", "Mit dem Pass"], "Mit den Ohren", "Ohren zum Hören."),
            V("Ein Lächeln ist im ...", ["Gesicht", "Kühlschrank", "Zug"], "Gesicht", "Lächeln sieht man im Gesicht."),
            V("Die Beine braucht man zum ...", ["Gehen", "Schreiben nur mit dem Ohr", "Trinken"], "Gehen", "Beine zum Gehen."),
            V("Sie hat lange ...", ["Haare", "Ampeln", "Hotels"], "Haare", "Haare können lang sein."),
            G("Er ___ keine Bauchschmerzen.", ["hat", "haben", "hast"], "hat", "Bei er: hat."),
            G("Meine Schwester ___ lange Haare.", ["hat", "haben", "hast"], "hat", "Bei sie: hat."),
            G("Ich ___ blaue Augen.", ["habe", "hast", "hat"], "habe", "Bei ich: habe."),
            G("___ du starke Arme?", ["Hast", "Hat", "Haben"], "Hast", "Bei du: hast."),
            G("Die Kinder ___ braune Haare.", ["haben", "hat", "hast"], "haben", "Bei die Kinder: haben."),
            G("Sein Bauch ___ nicht groß.", ["ist", "sind", "bist"], "ist", "Sein Bauch ist Singular."),
            G("Ihre Augen ___ grün.", ["sind", "ist", "bist"], "sind", "Augen = Plural."),
            G("Er ___ sehr sportlich.", ["sieht aus", "sehen aus", "siehst aus"], "sieht aus", "Bei er: sieht aus."),
            G("Wie ___ du aus?", ["siehst", "sieht", "sehen"], "siehst", "Bei du: siehst aus."),
            G("Wir ___ keine Kopfschmerzen.", ["haben", "hat", "hast"], "haben", "Bei wir: haben.")),

        CreateLesson(20, "Komm sofort runter!",
            V("Was ist ein Imperativ?", ["Eine Aufforderung", "Ein Getränk", "Ein Möbelstück"], "Eine Aufforderung", "Imperativ = Befehl/Bitte."),
            V("Was bedeutet: Komm her!", ["Komm zu mir", "Geh weg für immer ohne Grund", "Schlaf im Pass"], "Komm zu mir", "Her = Richtung zum Sprecher."),
            V("Sofort heißt ...", ["jetzt gleich", "nächstes Jahr", "nie"], "jetzt gleich", "Sofort = unmittelbar."),
            V("Was sagst du höflich?", ["Bitte komm!", "Komm sofort!", "Her jetzt!"], "Bitte komm!", "Bitte macht es höflicher."),
            V("Runter bedeutet oft ...", ["nach unten", "nach oben", "nach links nur im Pass"], "nach unten", "Runter = nach unten."),
            V("Mach das Fenster ___!", ["auf", "Zug", "Pass"], "auf", "Aufmachen = öffnen."),
            V("Sei bitte ___!", ["ruhig", "Bahnhof", "Dom"], "ruhig", "Ruhig = nicht laut."),
            V("Wart ___!", ["einen Moment", "einen Pass", "einen Dom"], "einen Moment", "Warten einen Moment."),
            V("Hilf ___ bitte!", ["mir", "ich", "mich"], "mir", "Hilf mir = Dativ."),
            V("Geh die Treppe ___!", ["runter", "Pass", "Tee"], "runter", "Runter = nach unten."),
            G("___ bitte her!", ["Komm", "Kommt", "Kommen"], "Komm", "Imperativ du: Komm!"),
            G("___ das Fenster auf!", ["Mach", "Macht", "Machen"], "Mach", "Imperativ du: Mach!"),
            G("___ ruhig!", ["Sei", "Seid", "Sein"], "Sei", "Imperativ du von sein: Sei!"),
            G("___ mir bitte!", ["Hilf", "Helft", "Helfen"], "Hilf", "Imperativ du: Hilf!"),
            G("___ einen Moment!", ["Wart", "Wartet", "Warten"], "Wart", "Imperativ du: Wart!"),
            G("Kinder, ___ bitte her!", ["kommt", "komm", "kommen"], "kommt", "Imperativ ihr: kommt!"),
            G("___ Sie bitte Platz!", ["Nehmen", "Nimm", "Nehmt"], "Nehmen", "Höflich: Nehmen Sie!"),
            G("___ das Buch zu!", ["Mach", "Macht", "Machen"], "Mach", "Mach ... zu!"),
            G("___ nicht so laut!", ["Sei", "Seid", "Ist"], "Sei", "Sei nicht so laut!"),
            G("Freunde, ___ mir!", ["helft", "hilf", "helfen"], "helft", "Imperativ ihr: helft!")),

        CreateLesson(21, "Bei Rot musst du stehen",
            V("Was machst du bei Rot an der Ampel?", ["Stehen bleiben", "Schnell laufen", "Schwimmen"], "Stehen bleiben", "Bei Rot bleibt man stehen."),
            V("Bei Grün darfst du ...", ["gehen", "schlafen im Pass", "essen den Zug"], "gehen", "Grün = gehen erlaubt."),
            V("Was ist eine Regel?", ["Etwas, das man beachten soll", "Ein Getränk", "Ein Sofa"], "Etwas, das man beachten soll", "Regeln steuern Verhalten."),
            V("Im Bus musst du oft einen ... zeigen.", ["Fahrschein", "Pass als Essen", "Dom"], "Fahrschein", "Fahrscheine für den Bus."),
            V("Was darfst du nicht im Museum?", ["Laut schreien", "Ruhig schauen", "Leise gehen"], "Laut schreien", "Im Museum ist Schreien unpassend."),
            V("Wer muss den Sicherheitsgurt anlegen?", ["Autofahrer und Mitfahrer", "Nur der Dom", "Nur der Tee"], "Autofahrer und Mitfahrer", "Gurt ist Pflicht im Auto."),
            V("Was bedeutet verboten?", ["Nicht erlaubt", "Sehr lecker", "Sehr neu"], "Nicht erlaubt", "Verboten = nicht erlaubt."),
            V("Auf dem Fahrradweg fährst du mit dem ...", ["Fahrrad", "Schiff", "Flugzeug"], "Fahrrad", "Fahrradweg für Fahrräder."),
            V("Bei Gelb sollst du ...", ["vorsichtig sein", "rennen ohne Blick", "schlafen"], "vorsichtig sein", "Gelb = Vorsicht."),
            V("Was musst du in der Bibliothek?", ["Leise sein", "Laut singen", "Kochen"], "Leise sein", "Bibliothek = Ruhe."),
            G("Bei Rot ___ du stehen.", ["musst", "müssen", "muss"], "musst", "Bei du: musst."),
            G("Ich ___ jetzt gehen.", ["muss", "musst", "müssen"], "muss", "Bei ich: muss."),
            G("Wir ___ den Fahrschein kaufen.", ["müssen", "muss", "musst"], "müssen", "Bei wir: müssen."),
            G("___ ich hier parken?", ["Darf", "Darfst", "Dürfen"], "Darf", "Bei ich: darf."),
            G("Ihr ___ nicht rauchen.", ["dürft", "darf", "darfst"], "dürft", "Bei ihr: dürft."),
            G("Man ___ den Gurt anlegen.", ["muss", "musst", "müssen"], "muss", "Man muss ..."),
            G("Kinder ___ hier nicht spielen.", ["dürfen", "darf", "darfst"], "dürfen", "Bei Kinder: dürfen."),
            G("Er ___ heute arbeiten.", ["muss", "musst", "müssen"], "muss", "Bei er: muss."),
            G("___ wir über die Straße gehen?", ["Können", "Kann", "Kannst"], "Können", "Bei wir: können."),
            G("Du ___ bei Grün gehen.", ["darfst", "darf", "dürfen"], "darfst", "Bei du: darfst.")),

        CreateLesson(22, "Am besten sind seine Schuhe",
            V("Was ist der Komparativ von gut?", ["besser", "guter", "am guten"], "besser", "gut → besser."),
            V("Was ist der Superlativ von gut?", ["am besten", "besser", "gutest"], "am besten", "gut → am besten."),
            V("Seine Schuhe sind ... als meine.", ["schöner", "schön", "am schönen"], "schöner", "Vergleich mit -er."),
            V("Welches Auto ist am schnellsten?", ["Das schnellste", "Das schnelle", "Das schneller"], "Das schnellste", "Superlativ mit am / -ste."),
            V("Berlin ist ___ als mein Dorf.", ["größer", "groß", "am großen"], "größer", "groß → größer."),
            V("Das ist der ___ Tee.", ["beste", "besser", "gut"], "beste", "Superlativ attributiv: beste."),
            V("Heute ist es ___ als gestern.", ["wärmer", "warm", "am warmen"], "wärmer", "warm → wärmer."),
            V("Welcher Film ist am interessantesten?", ["Der interessanteste", "Der interessante", "Der interessanter"], "Der interessanteste", "Superlativ."),
            V("Mein Bruder ist ___ als ich.", ["älter", "alt", "am alten"], "älter", "alt → älter."),
            V("Das Wetter ist heute am ...", ["schönsten", "schöner", "schön"], "schönsten", "am schönsten."),
            G("Diese Schuhe sind ___ als jene.", ["besser", "gut", "am besten"], "besser", "Komparativ: besser."),
            G("Das ist ___ beste Hotel.", ["das", "der", "die"], "das", "Hotel Neutrum: das beste."),
            G("Er läuft ___ als ich.", ["schneller", "schnell", "am schnellen"], "schneller", "Komparativ: schneller."),
            G("Welches Zimmer ist am ___?", ["größten", "größer", "groß"], "größten", "am größten."),
            G("Heute arbeite ich ___ als gestern.", ["länger", "lang", "am langen"], "länger", "Komparativ: länger."),
            G("Das ist die ___ Lösung.", ["beste", "besser", "gut"], "beste", "beste + feminin."),
            G("Mein Auto ist ___ als deins.", ["älter", "alt", "am alten"], "älter", "älter."),
            G("Im Sommer ist es am ___.", ["wärmsten", "wärmer", "warm"], "wärmsten", "am wärmsten."),
            G("Sie spricht Deutsch ___ als früher.", ["besser", "gut", "am besten"], "besser", "besser."),
            G("Das war der ___ Tag.", ["schönste", "schöner", "schön"], "schönste", "Superlativ attributiv.")),

        CreateLesson(23, "Ins Wasser gefallen",
            V("Was ist das Perfekt?", ["Eine Vergangenheit", "Ein Getränk", "Ein Möbelstück"], "Eine Vergangenheit", "Perfekt = oft gesprochene Vergangenheit."),
            V("gefallen – Partizip von ...", ["fallen", "finden", "fahren nur als Pass"], "fallen", "fallen → gefallen."),
            V("Mit sein bildet man Perfekt oft bei ...", ["Bewegung / Zustandswechsel", "nur Tee trinken", "nur Pass lesen"], "Bewegung / Zustandswechsel", "gehen, fahren, fallen oft mit sein."),
            V("Mit haben bildet man Perfekt oft bei ...", ["vielen anderen Verben", "nur sein", "nur Wetter"], "vielen anderen Verben", "machen, kaufen usw. mit haben."),
            V("Ich bin nach Hause ...", ["gegangen", "gegangen haben", "geh"], "gegangen", "gehen → gegangen + sein."),
            V("Sie hat Pizza ...", ["gegessen", "essen", "isst"], "gegessen", "essen → gegessen + haben."),
            V("Wir sind nach Berlin ...", ["gefahren", "gefahren haben", "fahrt"], "gefahren", "fahren → gefahren + sein."),
            V("Er hat das Buch ...", ["gelesen", "liest", "lesen"], "gelesen", "lesen → gelesen."),
            V("Ins Wasser bedeutet ...", ["hinein ins Wasser", "nur neben dem Pass", "nur auf dem Dom"], "hinein ins Wasser", "Richtung ins Wasser."),
            V("Was passt? – Gestern ___ ich müde gewesen.", ["bin", "habe", "hast"], "bin", "gewesen mit sein."),
            G("Ich ___ ins Wasser gefallen.", ["bin", "habe", "hast"], "bin", "fallen → sein + gefallen."),
            G("Sie ___ gestern gearbeitet.", ["hat", "ist", "bist"], "hat", "arbeiten + haben."),
            G("Wir ___ nach Hause gegangen.", ["sind", "haben", "hast"], "sind", "gehen + sein."),
            G("___ du den Film gesehen?", ["Hast", "Bist", "Seid"], "Hast", "sehen + haben."),
            G("Er ___ mit dem Bus gefahren.", ["ist", "hat", "hast"], "ist", "fahren + sein."),
            G("Ihr ___ Pizza gegessen.", ["habt", "seid", "bist"], "habt", "essen + haben."),
            G("Ich ___ gestern müde gewesen.", ["bin", "habe", "hast"], "bin", "gewesen + sein."),
            G("Wann ___ ihr angekommen?", ["seid", "habt", "bist"], "seid", "ankommen + sein."),
            G("Sie ___ das Fenster geöffnet.", ["hat", "ist", "bist"], "hat", "öffnen + haben."),
            G("Wir ___ lange gewartet.", ["haben", "sind", "bist"], "haben", "warten + haben.")),

        CreateLesson(24, "Ich würde am liebsten jeden Tag feiern",
            V("Was bedeutet: am liebsten?", ["Am liebsten / am meisten gern", "Nie", "Nur bei Rot"], "Am liebsten / am meisten gern", "Am liebsten = stärkste Vorliebe."),
            V("Feiern heißt ...", ["ein Fest machen", "nur schlafen", "nur den Pass lesen"], "ein Fest machen", "Feiern = Party/Fest."),
            V("Ich würde gern ...", ["einen Wunsch ausdrücken", "einen Dom essen", "einen Zug trinken"], "einen Wunsch ausdrücken", "würde gern = Wunsch."),
            V("Jeden Tag bedeutet ...", ["an allen Tagen", "nur montags", "nie"], "an allen Tagen", "Jeden Tag = täglich."),
            V("Was würdest du gern machen?", ["Einen Wunsch nennen", "Nur den Pass zählen", "Nur die Ampel essen"], "Einen Wunsch nennen", "Die Frage fragt nach dem Wunsch."),
            V("Am Wochenende würde ich gern ...", ["ausschlafen", "bei Rot rennen", "den Dom trinken"], "ausschlafen", "Typischer Wunsch."),
            V("würde + Infinitiv drückt oft aus ...", ["einen Wunsch / höfliche Idee", "nur Perfekt", "nur Imperativ streng"], "einen Wunsch / höfliche Idee", "Konjunktiv II light auf A1."),
            V("Ich würde lieber Tee als Kaffee ...", ["trinken", "fallen", "stehen bei Rot"], "trinken", "Lieber A als B."),
            V("Was passt zu feiern?", ["Musik und Freunde", "Nur Ampel", "Nur Gurt"], "Musik und Freunde", "Feiern mit Leuten."),
            V("Am liebsten wäre ich ...", ["im Urlaub", "im Pass", "im Aufzug kaputt"], "im Urlaub", "Wunschort."),
            G("Ich ___ gern jeden Tag feiern.", ["würde", "würdest", "würden"], "würde", "Bei ich: würde."),
            G("___ du gern ans Meer fahren?", ["Würdest", "Würde", "Würden"], "Würdest", "Bei du: würdest."),
            G("Er ___ gern Popstar werden.", ["würde", "würdest", "würden"], "würde", "Bei er: würde."),
            G("Wir ___ am liebsten zu Hause bleiben.", ["würden", "würde", "würdest"], "würden", "Bei wir: würden."),
            G("Was ___ ihr gern machen?", ["würdet", "würde", "würdest"], "würdet", "Bei ihr: würdet."),
            G("Sie ___ gern Deutsch lernen.", ["würde", "würdest", "würden"], "würde", "Bei sie Singular: würde."),
            G("Ich ___ lieber Tee trinken.", ["würde", "würdest", "würden"], "würde", "würde lieber + Infinitiv."),
            G("___ wir heute feiern?", ["Würden", "Würde", "Würdest"], "Würden", "Bei wir: würden."),
            G("Am liebsten ___ ich schlafen.", ["würde", "würdest", "würden"], "würde", "Am liebsten würde ich ..."),
            G("Meine Freunde ___ gern kommen.", ["würden", "würde", "würdest"], "würden", "Bei Plural: würden.")),
    ];

    private static QuizContentLesson CreateLesson(
        int number,
        string title,
        params (QuizCategory Category, string Prompt, string[] Options, string CorrectAnswer, string Explanation)[] questions)
    {
        var lessonId = Guid.Parse($"13131313-1313-1313-1313-{number:000000000000}");
        var baseQuestionId = number * 100 + 1;

        return new QuizContentLesson(
            new Lesson(lessonId, "Menschen", "A1.2", number, title),
            questions.Select((question, index) => new QuizQuestion(
                Guid.Parse($"23000000-0000-0000-0000-{baseQuestionId + index:000000000000}"),
                lessonId,
                question.Category,
                QuestionType.MultipleChoice,
                question.Prompt,
                question.Options,
                question.CorrectAnswer,
                question.Explanation)).ToList());
    }

    private static (QuizCategory Category, string Prompt, string[] Options, string CorrectAnswer, string Explanation) V(
        string prompt, string[] options, string correctAnswer, string explanation) =>
        (QuizCategory.Vocabulary, prompt, options, correctAnswer, explanation);

    private static (QuizCategory Category, string Prompt, string[] Options, string CorrectAnswer, string Explanation) G(
        string prompt, string[] options, string correctAnswer, string explanation) =>
        (QuizCategory.Grammar, prompt, options, correctAnswer, explanation);
}
