using DeutschQuiz.Domain;

namespace DeutschQuiz.Application;

/// <summary>
/// Independent quiz catalogue for Menschen A2.1 (Lektionen 1–12).
/// Prompts are original for DeutschQuiz and are not copied from the textbook.
/// </summary>
public static class MenschenA21QuizContentCatalog
{
    public static IReadOnlyList<QuizContentLesson> Lessons { get; } =
    [
        CreateLesson(1, "Alltag und Routinen",
            V("Was ist eine Routine?", ["Etwas, das man regelmäßig macht", "Ein einmaliges Fest", "Ein Unfall"], "Etwas, das man regelmäßig macht", "Routinen wiederholen sich."),
            V("Wann stehst du oft auf?", ["Am Morgen", "Nur im Winter", "Nur im Museum"], "Am Morgen", "Aufstehen gehört zum Morgen."),
            V("Was machst du vor der Arbeit oft?", ["Frühstücken", "Umziehen in eine neue Stadt", "Einen Pass erneuern"], "Frühstücken", "Frühstück ist typisch am Morgen."),
            V("Wie oft gehst du einkaufen?", ["Regelmäßig oder nach Bedarf", "Nur bei Rot", "Nur im Traum"], "Regelmäßig oder nach Bedarf", "Einkaufen gehört zum Alltag."),
            V("Was bedeutet: täglich?", ["Jeden Tag", "Einmal im Jahr", "Nie"], "Jeden Tag", "Täglich = jeden Tag."),
            V("Nach der Arbeit bist du oft ...", ["müde", "ein Pass", "eine Ampel"], "müde", "Arbeit macht viele Leute müde."),
            V("Was gehört zur Abendroutine?", ["Zähne putzen", "Einen Zug bauen", "Einen Dom essen"], "Zähne putzen", "Hygiene am Abend ist üblich."),
            V("Wer putzt die Wohnung?", ["Oft man selbst oder die Mitbewohner", "Nur der Busfahrer", "Nur die Ampel"], "Oft man selbst oder die Mitbewohner", "Haushalt ist Alltag."),
            V("Was machst du in der Mittagspause?", ["Essen oder kurz ausruhen", "Einen Pass verlängern", "Ein Haus kaufen"], "Essen oder kurz ausruhen", "Pause = kurze Erholung."),
            V("Am Wochenende ist der Alltag oft ...", ["anders als unter der Woche", "genau wie Montag immer", "nur Grammatik"], "anders als unter der Woche", "Wochenende weicht oft ab."),
            G("Ich ___ jeden Tag um sieben auf.", ["stehe", "stehst", "stehen"], "stehe", "Bei ich: stehe auf."),
            G("Sie ___ morgens immer Kaffee.", ["trinkt", "trinken", "trinkst"], "trinkt", "Bei sie Singular: trinkt."),
            G("Wir ___ abends fern.", ["sehen", "sieht", "siehst"], "sehen", "Bei wir: sehen."),
            G("___ du oft Sport?", ["Machst", "Macht", "Machen"], "Machst", "Bei du: machst."),
            G("Er ___ nie zu spät.", ["kommt", "kommen", "kommst"], "kommt", "Bei er: kommt."),
            G("Ich putze ___ die Zähne.", ["mir", "mich", "mein"], "mir", "Zähne putzen mit Dativ: mir."),
            G("Am Montag ___ ich früh zur Arbeit.", ["gehe", "gehst", "geht"], "gehe", "Bei ich: gehe."),
            G("Meine Eltern ___ um acht.", ["frühstücken", "frühstückt", "frühstückst"], "frühstücken", "Eltern = Plural."),
            G("___ ihr jeden Tag einkaufen?", ["Geht", "Gehts", "Gehen"], "Geht", "Bei ihr: geht."),
            G("Nach der Schule ___ sie Hausaufgaben.", ["macht", "machen", "machst"], "macht", "Bei sie Singular: macht.")),

        CreateLesson(2, "Arbeit und Beruf",
            V("Was ist ein Beruf?", ["Eine Tätigkeit, mit der man Geld verdient", "Ein Wochenende", "Ein Möbelstück"], "Eine Tätigkeit, mit der man Geld verdient", "Beruf = Arbeit."),
            V("Wo arbeitet ein Arzt oft?", ["Im Krankenhaus oder in der Praxis", "Nur im Zoo", "Nur am Bahnhof"], "Im Krankenhaus oder in der Praxis", "Ärzte behandeln Patienten."),
            V("Was ist ein Kollege?", ["Jemand, mit dem man zusammenarbeitet", "Ein Getränk", "Ein Verkehrsschild"], "Jemand, mit dem man zusammenarbeitet", "Kollegen teilen den Arbeitsplatz."),
            V("Was brauchst du oft für den Job?", ["Qualifikation und Erfahrung", "Nur ein Sofa", "Nur Schnee"], "Qualifikation und Erfahrung", "Arbeit braucht Fähigkeiten."),
            V("Was ist eine Bewerbung?", ["Unterlagen für einen neuen Job", "Ein Menü", "Ein Fahrplan"], "Unterlagen für einen neuen Job", "Man bewirbt sich mit Unterlagen."),
            V("Wer verdient Gehalt?", ["Ein Angestellter", "Ein Sofa", "Ein Park"], "Ein Angestellter", "Gehalt = Bezahlung."),
            V("Was macht man in der Pause?", ["Kurz entspannen oder essen", "Eine Stadt umziehen", "Einen Pass essen"], "Kurz entspannen oder essen", "Pause unterbricht die Arbeit."),
            V("Was ist Schichtarbeit?", ["Arbeit zu wechselnden Zeiten", "Nur Sonntagsausflug", "Nur Hausaufgaben"], "Arbeit zu wechselnden Zeiten", "Schicht = unterschiedliche Zeiten."),
            V("Ein Praktikum hilft oft ...", ["Berufserfahrung zu sammeln", "Einen Dom zu bauen", "Nur zu schlafen"], "Berufserfahrung zu sammeln", "Praktikum = Lernen im Job."),
            V("Was bedeutet arbeitslos?", ["Ohne Job", "Sehr reich", "Immer im Urlaub"], "Ohne Job", "Arbeitslos = ohne Beschäftigung."),
            G("Ich ___ als Lehrer.", ["arbeite", "arbeitest", "arbeitet"], "arbeite", "Bei ich: arbeite."),
            G("___ du Vollzeit oder Teilzeit?", ["Arbeitest", "Arbeitet", "Arbeiten"], "Arbeitest", "Bei du: arbeitest."),
            G("Sie ___ im Büro.", ["arbeitet", "arbeiten", "arbeitest"], "arbeitet", "Bei sie Singular: arbeitet."),
            G("Wir ___ eine neue Stelle.", ["suchen", "sucht", "suchst"], "suchen", "Bei wir: suchen."),
            G("Er ___ viel Geld.", ["verdient", "verdienen", "verdienst"], "verdient", "Bei er: verdient."),
            G("Meine Kollegin ___ pünktlich.", ["kommt", "kommen", "kommst"], "kommt", "Bei sie: kommt."),
            G("___ ihr morgen zur Besprechung?", ["Kommt", "Komm", "Kommen"], "Kommt", "Bei ihr: kommt."),
            G("Ich ___ mich um die Stelle bewerben.", ["möchte", "möchtest", "möchten"], "möchte", "Bei ich: möchte."),
            G("Der Chef ___ die Aufgaben.", ["erklärt", "erklären", "erklärst"], "erklärt", "Bei er: erklärt."),
            G("Was ___ Sie beruflich?", ["machen", "macht", "machst"], "machen", "Höflich: Sie machen.")),

        CreateLesson(3, "Medien und Nachrichten",
            V("Was sind Medien?", ["Zeitung, Radio, TV, Internet", "Nur Schuhe", "Nur Möbel"], "Zeitung, Radio, TV, Internet", "Medien informieren und unterhalten."),
            V("Wo liest du oft Nachrichten?", ["Online oder in der Zeitung", "Nur im Kühlschrank", "Nur im Pass"], "Online oder in der Zeitung", "Nachrichten kommen aus Medien."),
            V("Was ist eine Schlagzeile?", ["Der große Titel einer Meldung", "Ein Rezept", "Ein Fahrplan"], "Der große Titel einer Meldung", "Schlagzeilen fassen kurz zusammen."),
            V("Wer berichtet aus dem Ausland?", ["Ein Korrespondent", "Ein Koch nur lokal", "Ein Sofa"], "Ein Korrespondent", "Korrespondenten berichten von woanders."),
            V("Was bedeutet aktuell?", ["Jetzt wichtig / neu", "Sehr alt", "Nur historisch"], "Jetzt wichtig / neu", "Aktuell = gegenwärtig."),
            V("Podcasts hört man oft ...", ["mit dem Smartphone", "mit dem Fahrradlenker", "mit dem Fenster"], "mit dem Smartphone", "Podcasts sind Audiodateien."),
            V("Was ist Fake News?", ["Falsche oder erfundene Nachrichten", "Wahre Wetterberichte", "Offizielle Fahrpläne"], "Falsche oder erfundene Nachrichten", "Fake News sind nicht wahr."),
            V("Im Fernsehen siehst du oft ...", ["Nachrichten und Sendungen", "Nur den Pass", "Nur die Küche"], "Nachrichten und Sendungen", "TV zeigt Programme."),
            V("Was macht ein Journalist?", ["Er recherchiert und schreibt", "Er repariert nur Ampeln", "Er kocht nur Suppe"], "Er recherchiert und schreibt", "Journalisten produzieren Berichte."),
            V("Soziale Medien dienen oft zum ...", ["Teilen und Kommentieren", "Nur Schlafen", "Nur Parken"], "Teilen und Kommentieren", "Social Media = Austausch online."),
            G("Ich ___ jeden Morgen die Nachrichten.", ["lese", "liest", "lesen"], "lese", "Bei ich: lese."),
            G("___ du oft Podcasts?", ["Hörst", "Hört", "Hören"], "Hörst", "Bei du: hörst."),
            G("Der Bericht ___ sehr interessant.", ["ist", "sind", "bist"], "ist", "Der Bericht = Singular."),
            G("Wir ___ uns über Politik.", ["informieren", "informiert", "informierst"], "informieren", "Bei wir: informieren."),
            G("Sie ___ den Artikel geteilt.", ["hat", "ist", "bist"], "hat", "teilen + haben."),
            G("Die Nachrichten ___ heute früh.", ["kamen", "kam", "kommst"], "kamen", "Plural Vergangenheit / Präteritum A2."),
            G("___ ihr die Schlagzeile gesehen?", ["Habt", "Seid", "Bist"], "Habt", "sehen + haben."),
            G("Er ___ nicht alles, was online steht.", ["glaubt", "glauben", "glaubst"], "glaubt", "Bei er: glaubt."),
            G("Diese Meldung ___ falsch.", ["scheint", "scheinen", "scheinst"], "scheint", "Bei die Meldung: scheint."),
            G("Ich ___ gerade einen Podcast.", ["höre", "hörst", "hört"], "höre", "Bei ich: höre.")),

        CreateLesson(4, "Gesundheit und Fitness",
            V("Was bedeutet gesund?", ["Körperlich und mental in Ordnung", "Nur teuer", "Nur laut"], "Körperlich und mental in Ordnung", "Gesund = wohlauf."),
            V("Wo gehst du bei starken Schmerzen?", ["Zum Arzt", "Zum Bahnhof als Therapie", "Zum Pass"], "Zum Arzt", "Ärzte helfen bei Krankheit."),
            V("Was hilft oft bei Erkältung?", ["Ruhe und viel trinken", "Nur laufen im Regen", "Nur laut schreien"], "Ruhe und viel trinken", "Erkältung braucht Schonung."),
            V("Fitness bedeutet oft ...", ["körperliche Fitness durch Training", "Nur Fernsehen", "Nur Sitzen"], "körperliche Fitness durch Training", "Fitness = trainierter Zustand."),
            V("Was ist ein Rezept vom Arzt?", ["Anweisung für Medizin", "Ein Kochbuch", "Ein Ticket"], "Anweisung für Medizin", "Rezept für Medikamente."),
            V("Wer trainiert im Fitnessstudio?", ["Menschen, die Sport machen", "Nur Ampeln", "Nur Zeitungen"], "Menschen, die Sport machen", "Studio = Trainingsort."),
            V("Was solltest du nach dem Sport?", ["Trinken und ausruhen", "Sofort schwere Arbeit ohne Pause", "Den Pass essen"], "Trinken und ausruhen", "Körper braucht Erholung."),
            V("Kopfschmerzen sitzen oft im ...", ["Kopf", "Schuh", "Fahrplan"], "Kopf", "Kopfschmerzen = Schmerz im Kopf."),
            V("Eine gesunde Ernährung enthält oft ...", ["Obst und Gemüse", "Nur Süßigkeiten", "Nur Softdrinks"], "Obst und Gemüse", "Vitamine unterstützen Gesundheit."),
            V("Was bedeutet fit?", ["In guter Form", "Sehr krank", "Nur müde"], "In guter Form", "Fit = leistungsfähig."),
            G("Ich ___ mich nicht gut.", ["fühle", "fühlst", "fühlt"], "fühle", "sich fühlen: ich fühle mich."),
            G("___ du Sport?", ["Treibst", "Treibt", "Treiben"], "Treibst", "Bei du: treibst."),
            G("Er ___ jeden Tag joggen.", ["geht", "gehen", "gehst"], "geht", "Bei er: geht."),
            G("Du ___ mehr schlafen.", ["solltest", "sollt", "sollen"], "solltest", "Ratschlag: solltest."),
            G("Wir ___ uns gesund ernähren.", ["wollen", "will", "willst"], "wollen", "Bei wir: wollen."),
            G("Sie ___ starke Halsschmerzen.", ["hat", "haben", "hast"], "hat", "Bei sie Singular: hat."),
            G("___ ihr zum Arzt gegangen?", ["Seid", "Habt", "Bist"], "Seid", "gehen + sein."),
            G("Man ___ regelmäßig trinken.", ["sollte", "solltest", "sollt"], "sollte", "Allgemeiner Rat: sollte."),
            G("Mein Bein ___ weh.", ["tut", "tun", "tust"], "tut", "weh tun: es tut weh."),
            G("Ich ___ heute nicht arbeiten.", ["kann", "kannst", "können"], "kann", "Bei ich: kann.")),

        CreateLesson(5, "Wohnen und Nachbarschaft",
            V("Was ist eine Nachbarschaft?", ["Die Leute und Häuser in der Nähe", "Nur ein Flugzeug", "Nur ein Menü"], "Die Leute und Häuser in der Nähe", "Nachbarschaft = Umfeld."),
            V("Wer wohnt nebenan?", ["Die Nachbarn", "Die Züge", "Die Schlagzeilen"], "Die Nachbarn", "Nebenan = direkt daneben."),
            V("Was zahlst du für die Wohnung oft?", ["Miete", "Nur Trinkgeld im Bus", "Nur Eintritt ins Museum"], "Miete", "Miete = Wohnkosten."),
            V("Ein Mieter wohnt in einer ...", ["gemieteten Wohnung", "eigenen Insel immer", "Ampel"], "gemieteten Wohnung", "Mieter zahlt Miete."),
            V("Was ist eine Hausordnung?", ["Regeln im Haus", "Ein Kochrezept", "Ein Fahrplan"], "Regeln im Haus", "Hausordnung regelt Zusammenleben."),
            V("Der Hausmeister kümmert sich oft um ...", ["das Gebäude", "nur Nachrichten", "nur Rezepte"], "das Gebäude", "Hausmeister = Betreuung des Hauses."),
            V("Was stört Nachbarn oft?", ["Lauter Lärm am Abend", "Leises Lesen", "Ruhiges Schlafen"], "Lauter Lärm am Abend", "Lärm belastet Nachbarn."),
            V("Eine Etage ist ein ...", ["Stockwerk", "Getränk", "Beruf"], "Stockwerk", "Etage = Stock."),
            V("Was suchst du, wenn du umziehst?", ["Eine neue Wohnung", "Einen neuen Pass nur zum Essen", "Eine Ampel als Bett"], "Eine neue Wohnung", "Umzug = neuer Wohnort."),
            V("Im Treppenhaus bist du oft ...", ["auf dem Weg zur Wohnung", "im Flugzeug", "im Meer"], "auf dem Weg zur Wohnung", "Treppenhaus verbindet Etagen."),
            G("Ich ___ im dritten Stock.", ["wohne", "wohnst", "wohnt"], "wohne", "Bei ich: wohne."),
            G("Unsere Nachbarn ___ sehr nett.", ["sind", "ist", "bist"], "sind", "Nachbarn = Plural."),
            G("Die Wohnung ___ neben dem Park.", ["liegt", "liegen", "liegst"], "liegt", "Bei die Wohnung: liegt."),
            G("___ du dich mit den Nachbarn?", ["Verstehst", "Versteht", "Verstehen"], "Verstehst", "sich verstehen: verstehst du dich."),
            G("Wir ___ die Miete pünktlich.", ["zahlen", "zahlt", "zahlst"], "zahlen", "Bei wir: zahlen."),
            G("Es ___ im Haus eine Waschküche.", ["gibt", "ist", "sind"], "gibt", "Es gibt = vorhanden."),
            G("Bitte sei ___ den Nachbarn leise!", ["gegenüber", "durch", "ohne"], "gegenüber", "gegenüber + Dativ."),
            G("Er ___ seit Mai hier.", ["wohnt", "wohnen", "wohnst"], "wohnt", "Bei er: wohnt."),
            G("___ ihr die Hausordnung gelesen?", ["Habt", "Seid", "Bist"], "Habt", "lesen + haben."),
            G("Die Kinder ___ nicht im Flur.", ["spielen", "spielt", "spielst"], "spielen", "Negation: spielen nicht.")),

        CreateLesson(6, "Freizeit und Hobbys",
            V("Was ist Freizeit?", ["Zeit ohne Arbeit oder Schule", "Nur Arbeitszeit", "Nur Wartezeit am Schalter"], "Zeit ohne Arbeit oder Schule", "Freizeit = freie Zeit."),
            V("Was ist ein Hobby?", ["Eine liebe Beschäftigung in der Freizeit", "Eine Steuer", "Ein Verkehrsschild"], "Eine liebe Beschäftigung in der Freizeit", "Hobby = Lieblingsbeschäftigung."),
            V("Wer spielt oft Instrumente?", ["Musiker und Hobby-Musiker", "Nur Ärzte im OP", "Nur Busfahrer"], "Musiker und Hobby-Musiker", "Instrumente = Musik."),
            V("Was machst du gern am Wochenende?", ["Hobbys oder Treffen mit Freunden", "Nur Formalitäten ohne Pause", "Nur Ampel zählen"], "Hobbys oder Treffen mit Freunden", "Wochenende = oft Freizeit."),
            V("Lesen ist ein Hobby für Leute, die ...", ["Bücher mögen", "nur rennen müssen", "nur kochen dürfen"], "Bücher mögen", "Lesen = Bücher."),
            V("Sport in der Freizeit hält dich oft ...", ["fit", "krank", "müde ohne Pause immer"], "fit", "Bewegung unterstützt Fitness."),
            V("Ein Verein ist oft ein Ort für ...", ["gemeinsame Hobbys", "nur Steuern", "nur Nachrichten"], "gemeinsame Hobbys", "Verein = Organisation."),
            V("Was bedeutet: sich entspannen?", ["Zur Ruhe kommen", "Sehr stressen", "Nur arbeiten"], "Zur Ruhe kommen", "Entspannen = Stress abbauen."),
            V("Wer fotografiert gern?", ["Jemand mit Foto-Hobby", "Nur der Pass", "Nur die Miete"], "Jemand mit Foto-Hobby", "Fotografieren = Bilder machen."),
            V("Kino, Konzert oder Theater sind ...", ["Freizeitangebote", "nur Berufe", "nur Krankheiten"], "Freizeitangebote", "Kultur in der Freizeit."),
            G("Ich ___ in meiner Freizeit gern.", ["lese", "liest", "lesen"], "lese", "Bei ich: lese."),
            G("___ du ein Instrument?", ["Spielst", "Spielt", "Spielen"], "Spielst", "Bei du: spielst."),
            G("Wir ___ uns am Samstag.", ["treffen", "trifft", "triffst"], "treffen", "Bei wir: treffen."),
            G("Sie ___ lieber Wandern als Joggen.", ["mag", "mögen", "magst"], "mag", "Bei sie Singular: mag."),
            G("Er ___ Mitglied in einem Verein.", ["ist", "sind", "bist"], "ist", "Bei er: ist."),
            G("___ ihr am Abend fern?", ["Seht", "Sieht", "Sehen"], "Seht", "Bei ihr: seht."),
            G("Ich ___ mich nach der Arbeit.", ["entspanne", "entspannst", "entspannt"], "entspanne", "sich entspannen: ich entspanne mich."),
            G("Meine Freunde ___ oft Volleyball.", ["spielen", "spielt", "spielst"], "spielen", "Freunde = Plural."),
            G("Was ___ Sie in der Freizeit?", ["machen", "macht", "machst"], "machen", "Höflich: Sie machen."),
            G("Am Sonntag ___ wir ausschlafen.", ["können", "kann", "kannst"], "können", "Bei wir: können.")),

        CreateLesson(7, "Reisen und Verkehr",
            V("Was brauchst du oft für eine Reise?", ["Ticket und Ausweis", "Nur ein Sofa", "Nur Hausordnung"], "Ticket und Ausweis", "Reisen braucht Dokumente."),
            V("Wo steigt man in den Zug ein?", ["Am Bahnhof", "Im Kühlschrank", "Auf dem Sofa"], "Am Bahnhof", "Züge fahren vom Bahnhof."),
            V("Was ist ein Fahrplan?", ["Übersicht der Abfahrtszeiten", "Ein Rezept", "Eine Hausordnung"], "Übersicht der Abfahrtszeiten", "Fahrplan zeigt Zeiten."),
            V("Öffentlicher Verkehr sind oft ...", ["Bus, Bahn und Tram", "nur Privatautos immer", "nur Flugzeuge privat"], "Bus, Bahn und Tram", "ÖPNV = öffentliche Verkehrsmittel."),
            V("Verspätung bedeutet ...", ["später als geplant", "früher als geplant", "genau pünktlich immer"], "später als geplant", "Verspätung = Delay."),
            V("Was machst du am Check-in?", ["Dich für den Flug anmelden", "Nur kochen", "Nur joggen"], "Dich für den Flug anmelden", "Check-in vor dem Flug."),
            V("Ein Umsteigen ist nötig, wenn ...", ["du den Zug wechseln musst", "du nur zu Hause bleibst", "du nur liest"], "du den Zug wechseln musst", "Umsteigen = Wechseln."),
            V("Was ist eine Fahrkarte?", ["Berechtigung zur Fahrt", "Ein Hobby", "Ein Medikament"], "Berechtigung zur Fahrt", "Fahrkarte = Ticket."),
            V("Im Stau bist du ...", ["im stehenden Verkehr", "schon im Urlaubshotel", "im Fitnessstudio"], "im stehenden Verkehr", "Stau = stockender Verkehr."),
            V("Was bedeutet: abfahren?", ["Losfahren / starten", "Ankommen", "Nur warten ohne Ziel"], "Losfahren / starten", "Abfahren = starten."),
            G("Ich ___ morgen nach Berlin.", ["fahre", "fährst", "fahrt"], "fahre", "Bei ich: fahre."),
            G("___ du mit dem Bus oder der Bahn?", ["Fährst", "Fährt", "Fahren"], "Fährst", "Bei du: fährst."),
            G("Der Zug ___ um zehn ab.", ["fährt", "fahren", "fährst"], "fährt", "Bei der Zug: fährt."),
            G("Wir ___ in München um.", ["steigen", "steigt", "steigst"], "steigen", "Bei wir: steigen um."),
            G("___ ihr pünktlich angekommen?", ["Seid", "Habt", "Bist"], "Seid", "ankommen + sein."),
            G("Sie ___ das Ticket online.", ["hat gebucht", "ist gebucht", "bist gebucht"], "hat gebucht", "buchen + haben."),
            G("Wann ___ der Bus?", ["kommt", "kommen", "kommst"], "kommt", "Bei der Bus: kommt."),
            G("Ich ___ den Fahrplan nicht.", ["verstehe", "verstehst", "versteht"], "verstehe", "Bei ich: verstehe."),
            G("Man ___ im Zug nicht laut telefonieren.", ["sollte", "solltest", "sollt"], "sollte", "Empfehlung: sollte."),
            G("Wir ___ zwei Stunden gewartet.", ["haben", "sind", "bist"], "haben", "warten + haben.")),

        CreateLesson(8, "Essen und Ernährung",
            V("Was ist Ernährung?", ["Was und wie man isst", "Nur Sport", "Nur Verkehr"], "Was und wie man isst", "Ernährung = Essgewohnheiten."),
            V("Eine ausgewogene Ernährung enthält oft ...", ["verschiedene Nährstoffe", "nur Zucker", "nur Salz"], "verschiedene Nährstoffe", "Ausgewogen = vielfältig."),
            V("Was ist vegetarisch?", ["Ohne Fleisch", "Nur mit Fleisch", "Nur Getränke"], "Ohne Fleisch", "Vegetarisch = kein Fleisch."),
            V("Wo kaufst du frisches Obst?", ["Auf dem Markt oder im Laden", "Nur am Bahnhofsschalter", "Nur in der Apotheke immer"], "Auf dem Markt oder im Laden", "Obst gibt es in Läden."),
            V("Kalorien sagen etwas über ...", ["den Energiegehalt von Essen", "nur die Farbe", "nur den Preis immer"], "den Energiegehalt von Essen", "Kalorien = Energie."),
            V("Was bedeutet: Allergie?", ["Starke Reaktion auf bestimmte Stoffe", "Ein Hobby", "Ein Ticket"], "Starke Reaktion auf bestimmte Stoffe", "Allergie = Unverträglichkeit."),
            V("Frühstück, Mittagessen, Abendessen sind ...", ["Mahlzeiten", "Berufe", "Verkehrsmittel"], "Mahlzeiten", "Mahlzeiten strukturieren den Tag."),
            V("Wer kocht zu Hause?", ["Oft man selbst oder die Familie", "Nur der Zug", "Nur die Ampel"], "Oft man selbst oder die Familie", "Kochen = Essen zubereiten."),
            V("Fast Food ist oft ...", ["schnell, aber nicht immer gesund", "immer die gesündeste Wahl", "nur Medizin"], "schnell, aber nicht immer gesund", "Fast Food = schnell zubereitet."),
            V("Wasser trinken ist wichtig für ...", ["den Körper", "nur den Pass", "nur die Miete"], "den Körper", "Flüssigkeit braucht der Körper."),
            G("Ich ___ gern Gemüse.", ["esse", "isst", "essen"], "esse", "Bei ich: esse."),
            G("___ du Fleisch?", ["Isst", "Esse", "Essen"], "Isst", "Bei du: isst."),
            G("Wir ___ uns gesund.", ["ernähren", "ernährt", "ernährst"], "ernähren", "sich ernähren: wir ernähren uns."),
            G("Sie ___ keinen Zucker in den Tee.", ["tut", "tun", "tust"], "tut", "Bei sie Singular: tut."),
            G("Er ___ jeden Tag Obst.", ["kauft", "kaufen", "kaufst"], "kauft", "Bei er: kauft."),
            G("___ ihr vegetarisch?", ["Esst", "Isst", "Essen"], "Esst", "Bei ihr: esst."),
            G("Das Essen ___ lecker.", ["schmeckt", "schmecken", "schmeckst"], "schmeckt", "Bei das Essen: schmeckt."),
            G("Ich ___ heute Abend kochen.", ["werde", "wirst", "werden"], "werde", "Futur/Absicht: werde."),
            G("Man ___ zu viel Salz vermeiden.", ["sollte", "solltest", "sollt"], "sollte", "Rat: sollte."),
            G("Wir ___ schon zu Mittag gegessen.", ["haben", "sind", "bist"], "haben", "essen + haben.")),

        CreateLesson(9, "Umwelt und Klima",
            V("Was ist die Umwelt?", ["Natur und Umgebung um uns", "Nur das Büro innen", "Nur ein Menü"], "Natur und Umgebung um uns", "Umwelt = surroundings."),
            V("Klima beschreibt langfristig ...", ["Wetterbedingungen einer Region", "nur ein einzelnes Gewitter", "nur die Raumtemperatur heute"], "Wetterbedingungen einer Region", "Klima ≠ einzelnes Wetter."),
            V("Was schützt die Umwelt?", ["Weniger Müll und sparsamer Energieverbrauch", "Mehr unnötigen Müll", "Nur lautes Radio"], "Weniger Müll und sparsamer Energieverbrauch", "Umweltschutz spart Ressourcen."),
            V("Recycling bedeutet ...", ["Wiederverwertung von Materialien", "Alles wegwerfen", "Nur neu kaufen ohne Sinn"], "Wiederverwertung von Materialien", "Recyceln = erneut nutzen."),
            V("CO₂ hängt oft zusammen mit ...", ["Emissionen und Klimawandel", "nur Hobbys", "nur Miete"], "Emissionen und Klimawandel", "CO₂ beeinflusst das Klima."),
            V("Öffentliche Verkehrsmittel sind oft ...", ["umweltfreundlicher als viele Autos", "immer schädlicher", "nur für Tiere"], "umweltfreundlicher als viele Autos", "ÖPNV spart oft Emissionen."),
            V("Was ist erneuerbare Energie?", ["Energie aus Sonne, Wind u. a.", "Nur Kohle immer", "Nur Benzin"], "Energie aus Sonne, Wind u. a.", "Erneuerbar = nachwachsend nutzbar."),
            V("Plastikmüll ist ein Problem für ...", ["Meere und Tiere", "nur Grammatik", "nur Fahrpläne"], "Meere und Tiere", "Plastik belastet Ökosysteme."),
            V("Energie sparen heißt oft ...", ["Licht und Heizung bewusst nutzen", "alles den ganzen Tag anlassen", "Fenster immer offen im Winter ohne Grund"], "Licht und Heizung bewusst nutzen", "Sparen = weniger verbrauchen."),
            V("Was bedeutet nachhaltig?", ["Ressourcen schonend langfristig", "Nur kurzfristig verschwenden", "Nur einmalig laut"], "Ressourcen schonend langfristig", "Nachhaltig = dauerhaft tragfähig."),
            G("Wir ___ die Umwelt schützen.", ["sollten", "solltest", "sollt"], "sollten", "Bei wir: sollten."),
            G("Ich ___ den Müll trennen.", ["versuche", "versuchst", "versucht"], "versuche", "Bei ich: versuche."),
            G("Das Klima ___ sich.", ["ändert", "ändern", "änderst"], "ändert", "sich ändern: ändert sich."),
            G("___ du mit dem Fahrrad zur Arbeit?", ["Fährst", "Fährt", "Fahren"], "Fährst", "Bei du: fährst."),
            G("Viele Menschen ___ weniger Plastik.", ["verbrauchen", "verbraucht", "verbrauchst"], "verbrauchen", "Plural: verbrauchen."),
            G("Er ___ auf erneuerbare Energie.", ["setzt", "setzen", "setztst"], "setzt", "Bei er: setzt."),
            G("Recycling ___ Ressourcen.", ["spart", "sparen", "sparst"], "spart", "Bei Recycling: spart."),
            G("___ ihr das Licht aus?", ["Macht", "Machtst", "Machen"], "Macht", "Bei ihr: macht ... aus."),
            G("Man ___ öffentliche Verkehrsmittel nutzen.", ["kann", "kannst", "könnt"], "kann", "Man kann ..."),
            G("Wir ___ gestern Müll gesammelt.", ["haben", "sind", "bist"], "haben", "sammeln + haben.")),

        CreateLesson(10, "Schule und Lernen",
            V("Was ist eine Schule?", ["Ort zum Lernen für Schüler", "Nur ein Hotel", "Nur ein Fitnessstudio"], "Ort zum Lernen für Schüler", "Schule = Bildungsort."),
            V("Wer unterrichtet in der Klasse?", ["Der Lehrer / die Lehrerin", "Nur der Nachbar immer", "Nur der Busfahrer"], "Der Lehrer / die Lehrerin", "Lehrkräfte unterrichten."),
            V("Hausaufgaben macht man oft ...", ["nach dem Unterricht", "nur im Traum", "nur im Stau"], "nach dem Unterricht", "Hausaufgaben = Übungen zu Hause."),
            V("Was ist eine Prüfung?", ["Ein Test des Wissens", "Ein Rezept", "Ein Ticket"], "Ein Test des Wissens", "Prüfung prüft Können."),
            V("Eine Fremdsprache lernt man durch ...", ["Übung und Praxis", "nur Schlafen", "nur Warten"], "Übung und Praxis", "Lernen braucht Wiederholung."),
            V("Was bedeutet: sich konzentrieren?", ["Aufmerksam bei einer Sache bleiben", "Nur ablenken", "Nur laut reden"], "Aufmerksam bei einer Sache bleiben", "Konzentration = Fokus."),
            V("Noten bewerten oft ...", ["Leistungen in der Schule", "nur das Wetter", "nur die Miete"], "Leistungen in der Schule", "Noten = Bewertung."),
            V("Ein Wörterbuch hilft beim ...", ["Übersetzen und Nachschlagen", "Kochen ohne Rezept immer", "Parken"], "Übersetzen und Nachschlagen", "Wörterbuch = Wortliste."),
            V("Gruppenarbeit bedeutet ...", ["gemeinsam an einer Aufgabe arbeiten", "nur allein immer", "nur Pause ohne Ziel"], "gemeinsam an einer Aufgabe arbeiten", "Gruppe = zusammen."),
            V("Wer wiederholt den Stoff?", ["Schüler vor Prüfungen oft", "Nur Ampeln", "Nur Züge"], "Schüler vor Prüfungen oft", "Wiederholen festigt Wissen."),
            G("Ich ___ jeden Tag Vokabeln.", ["lerne", "lernst", "lernt"], "lerne", "Bei ich: lerne."),
            G("___ du die Hausaufgaben?", ["Machst", "Macht", "Machen"], "Machst", "Bei du: machst."),
            G("Wir ___ uns auf die Prüfung vor.", ["bereiten", "bereitet", "bereitest"], "bereiten", "sich vorbereiten: wir bereiten uns vor."),
            G("Der Lehrer ___ die Aufgabe.", ["erklärt", "erklären", "erklärst"], "erklärt", "Bei er: erklärt."),
            G("Sie ___ gut in Mathe.", ["ist", "sind", "bist"], "ist", "Bei sie Singular: ist."),
            G("___ ihr den Text bestanden?", ["Habt", "Seid", "Bist"], "Habt", "bestehen + haben."),
            G("Ich lerne Deutsch, ___ ich in Deutschland leben möchte.", ["weil", "oder", "aber"], "weil", "weil + Nebensatz."),
            G("Er ___ fleißig.", ["lernt", "lernen", "lernst"], "lernt", "Bei er: lernt."),
            G("Die Schüler ___ Fragen.", ["stellen", "stellt", "stellst"], "stellen", "Schüler = Plural."),
            G("Man ___ regelmäßig wiederholen.", ["sollte", "solltest", "sollt"], "sollte", "Rat: sollte.")),

        CreateLesson(11, "Gefühle und Beziehungen",
            V("Was sind Gefühle?", ["Emotionen wie Freude oder Angst", "Nur Möbel", "Nur Fahrpläne"], "Emotionen wie Freude oder Angst", "Gefühle = Emotionen."),
            V("Wann bist du froh?", ["Wenn etwas Positives passiert", "Nur bei Verspätung immer", "Nur bei Krankheit immer"], "Wenn etwas Positives passiert", "Froh = glücklich."),
            V("Traurig fühlt man sich oft bei ...", ["Verlust oder Enttäuschung", "nur Geburtstagen immer", "nur Sonnenschein immer"], "Verlust oder Enttäuschung", "Trauer = negatives Gefühl."),
            V("Eine Beziehung besteht oft zwischen ...", ["Menschen, die sich nahestehen", "nur Ampeln", "nur Tickets"], "Menschen, die sich nahestehen", "Beziehung = Verbindung."),
            V("Was bedeutet: sich streiten?", ["Uneinig sein und diskutieren", "Nur gemeinsam lachen", "Nur schweigen immer"], "Uneinig sein und diskutieren", "Streit = Konflikt."),
            V("Sich entschuldigen zeigt oft ...", ["Reue und Respekt", "nur Wut ohne Grund", "nur Desinteresse"], "Reue und Respekt", "Entschuldigung = Höflichkeit."),
            V("Freunde unterstützen sich in ...", ["guten und schweren Zeiten", "nur im Stau technisch", "nur bei Grammatik immer"], "guten und schweren Zeiten", "Freundschaft = Unterstützung."),
            V("Nervös bist du oft vor ...", ["wichtigen Terminen oder Prüfungen", "nur dem Mittagessen immer", "nur dem Sofa"], "wichtigen Terminen oder Prüfungen", "Nervosität = Anspannung."),
            V("Verliebt sein beschreibt ...", ["starke Zuneigung zu jemandem", "nur Hunger", "nur Miete"], "starke Zuneigung zu jemandem", "Verliebt = romantisch."),
            V("Was hilft bei Konflikten oft?", ["Ruhig reden und zuhören", "Nur schreien", "Nur weglaufen ohne Wort"], "Ruhig reden und zuhören", "Gespräch löst Konflikte."),
            G("Ich ___ mich heute gut.", ["fühle", "fühlst", "fühlt"], "fühle", "sich fühlen: ich fühle mich."),
            G("___ du dich über das Geschenk?", ["Freust", "Freut", "Freuen"], "Freust", "sich freuen: freust du dich."),
            G("Er ___ sich für den Fehler.", ["entschuldigt", "entschuldigen", "entschuldigst"], "entschuldigt", "sich entschuldigen: entschuldigt sich."),
            G("Wir ___ uns seit der Schule.", ["kennen", "kennt", "kennst"], "kennen", "Bei wir: kennen."),
            G("Sie ___ wütend auf ihn.", ["ist", "sind", "bist"], "ist", "Bei sie Singular: ist."),
            G("___ ihr euch oft?", ["Streitet", "Streitetst", "Streiten"], "Streitet", "sich streiten: streitet ihr euch."),
            G("Ich ___ dir.", ["vertraue", "vertraust", "vertraut"], "vertraue", "vertrauen + Dativ: ich vertraue dir."),
            G("Meine Freundin ___ mir.", ["hilft", "helfen", "hilfst"], "hilft", "helfen + Dativ."),
            G("Er ___ sich um seine Familie.", ["kümmert", "kümmern", "kümmerst"], "kümmert", "sich kümmern um."),
            G("Wir ___ uns wieder vertragen.", ["haben", "sind", "bist"], "haben", "sich vertragen + haben.")),

        CreateLesson(12, "Pläne und Zukunft",
            V("Was ist ein Plan?", ["Eine Absicht für die Zukunft", "Nur die Vergangenheit", "Nur ein Sofort-Zufall"], "Eine Absicht für die Zukunft", "Plan = Vorhaben."),
            V("Die Zukunft liegt ...", ["vor uns in der Zeit", "nur hinter uns", "nur im Kühlschrank"], "vor uns in der Zeit", "Zukunft = kommende Zeit."),
            V("Was bedeutet: vorhaben?", ["Etwas planen zu tun", "Etwas schon beendet haben", "Nur warten ohne Ziel"], "Etwas planen zu tun", "vorhaben = planen."),
            V("Ein Termin ist oft ...", ["eine feste Verabredung", "nur ein Gefühl", "nur ein Rezept"], "eine feste Verabredung", "Termin = Zeitpunkt."),
            V("Urlaub planst du oft ...", ["im Voraus", "erst nach der Rückkehr immer", "nur im Traum ohne Datum"], "im Voraus", "Planung vor der Reise."),
            V("Was drückt „ich werde …“ oft aus?", ["Zukunft oder Absicht", "Nur Perfekt", "Nur Imperativ streng"], "Zukunft oder Absicht", "werden + Infinitiv."),
            V("Wenn es regnet, bleibe ich oft ...", ["zu Hause", "im Freien ohne Grund", "auf dem Dach ohne Schutz"], "zu Hause", "Wetter beeinflusst Pläne."),
            V("Karrierepläne betreffen oft ...", ["Beruf und Weiterbildung", "nur das Frühstück", "nur den Fahrplan heute"], "Beruf und Weiterbildung", "Karriere = beruflicher Weg."),
            V("Ein Ziel ist etwas, das man ...", ["erreichen möchte", "nur vergisst", "nur vermeidet immer"], "erreichen möchte", "Ziel = angestrebtes Ergebnis."),
            V("Spontan bedeutet ...", ["ohne lange Planung", "mit festem Jahresplan immer", "nur schriftlich vor zehn Jahren"], "ohne lange Planung", "Spontan = aus dem Moment."),
            G("Ich ___ nächstes Jahr umziehen.", ["werde", "wirst", "werden"], "werde", "Bei ich: werde."),
            G("___ du bald eine Prüfung machen?", ["Wirst", "Wird", "Werden"], "Wirst", "Bei du: wirst."),
            G("Wir ___ im Sommer verreisen.", ["werden", "werde", "wirst"], "werden", "Bei wir: werden."),
            G("Er ___ Arzt werden.", ["möchte", "möchtest", "möchten"], "möchte", "Bei er: möchte."),
            G("___ ihr am Wochenende kommen?", ["Werdet", "Wirst", "Wird"], "Werdet", "Bei ihr: werdet."),
            G("Wenn ich Zeit ___, rufe ich dich an.", ["habe", "hast", "hat"], "habe", "wenn + Präsens."),
            G("Sie ___ nächste Woche starten.", ["plant", "planen", "planst"], "plant", "Bei sie Singular: plant."),
            G("Ich ___ vor, Deutsch zu lernen.", ["habe", "hast", "hat"], "habe", "vorhaben: ich habe vor."),
            G("Was ___ Sie morgen?", ["machen", "macht", "machst"], "machen", "Höflich: Sie machen."),
            G("Wir ___ uns später treffen.", ["wollen", "will", "willst"], "wollen", "Bei wir: wollen.")),
    ];

    private static QuizContentLesson CreateLesson(
        int number,
        string title,
        params (QuizCategory Category, string Prompt, string[] Options, string CorrectAnswer, string Explanation)[] questions)
    {
        var lessonId = Guid.Parse($"21212121-2121-2121-2121-{number:000000000000}");
        var baseQuestionId = number * 100 + 1;

        return new QuizContentLesson(
            new Lesson(lessonId, "Menschen", "A2.1", number, title),
            questions.Select((question, index) => new QuizQuestion(
                Guid.Parse($"24100000-0000-0000-0000-{baseQuestionId + index:000000000000}"),
                lessonId,
                question.Category,
                QuestionType.MultipleChoice,
                question.Prompt,
                question.Options,
                question.CorrectAnswer,
                question.Explanation)).ToList());
    }

    private static (QuizCategory Category, string Prompt, string[] Options, string CorrectAnswer, string Explanation) V(
        string prompt, string[] options, string correctAnswer, string explanation) =>
        (QuizCategory.Vocabulary, prompt, options, correctAnswer, explanation);

    private static (QuizCategory Category, string Prompt, string[] Options, string CorrectAnswer, string Explanation) G(
        string prompt, string[] options, string correctAnswer, string explanation) =>
        (QuizCategory.Grammar, prompt, options, correctAnswer, explanation);
}
